### ISSUE TITLE
Type <x> is abstract and can not be used to construct objects from dictionary values. Please register a conversion within the ValueConverter or for input graph types override ParseDictionary method

### ISSUE THREAD

**Issue by dmongitss** [graphql-dotnet/graphql-dotnet#3910] opened 2024-01-31 21:09 UTC
I have an error message that I cannot figure out. We are upgrading our .NET Console Apps (used as APIs) from GraphQL 2.4.0 using .NET Core 3.1 and .NET Standard 2.1 helper projects to GraphQL 7.7.2 with .NET 8. We also went from AutoMapper 9 to 12.

Originally we tried using the GraphQL documentation at https://graphql-dotnet.github.io/docs/migrations/ to go from v2 to v3 then v3 to v4 then v4 to v5 then v5 to v7. We punted that idea and just went all in from v2 to v7. We are in a state where our GraphQL Queries are working well but our Mutations are not.

## Summary
We are using a Mutation for Inserts/Updates and our Inserts/Updates but we are popping a 400 error with the InnerException message of: "Type 'IUser' is abstract and can not be used to construct objects from dictionary values. Please register a conversion within the ValueConverter or for input graph types override ParseDictionary method."

We googled the error message and I don't get much. I do see that part of the error is shown on https://graphql-dotnet.github.io/docs/migrations/migration4/ but I'll be honest that I'm new to GraphQL and I haven't touched .NET in 5 years. If my answer is on the migration4 link, I wouldn't know. 

I don't know what the error is saying. I thought maybe there was a problem with my Field statements. We had `Field("isActive", x => x.IsActive, type: typeof(BooleanGraphType));` but changed to `Field<BooleanGraphType>("IsActive");` thinking we were on to something. But, we have the same error. 

Any pointers?

Thanks!

**Comment by Shane32** [comment] 2024-01-31 21:30
If you’re using auto registering input graph type for an interface, version 2 would have stored incoming data in a dictionary until GetArgument was called. Version 4+ (?) will attempt to serialize it to a object immediately which is not possible to serialize to an interface. If you can confirm this I can provide the workaround. 

That’s my best guess so far. If you can post the exact stack trace of the underlying exception, I might have a better idea.

**Comment by Shane32** [comment] 2024-01-31 21:33
https://graphql-dotnet.github.io/docs/migrations/migration4/#input-object-custom-deserializers-aka-resolver

**Comment by Shane32** [comment] 2024-01-31 21:42
Two possible solutions then:

1. Change the clr type to a class instead of an interface

2. Use a derived class of AutoRegisteringInputObjectGraphType and override ParseDictionary to return the dictionary. 

For solution 2, assuming you have configured the schema to use DI, you can register a derived open generic class within DI so that all requests for the auto registering class get your derived version with the patch to make it work like v2

**Comment by dmongitss** [comment] 2024-01-31 21:46
That's interesting. We are configured to use DI and you sold me at "easiest fix", so I'll try option 2. I *think* I understand what you're putting down. Thank you.

**Comment by Shane32** [comment] 2024-01-31 21:46
The value converter solution mentioned in the error message is possible too, so long it’s always converting to the same type.

**Comment by Shane32** [comment] 2024-01-31 21:48
Let me know if you have any questions. I’m not at a pc just now but will be in an hour or so.

**Comment by dmongitss** [comment] 2024-01-31 21:50
Thank you, I'll let you know.

**Comment by dmongitss** [comment] 2024-01-31 21:59
Correct me if I'm wrong here but on a Mutation, the error is that my API call from my client is sending data to be mutated and GraphQL v7 (or 4+) is failing to parse/deserialize the incoming data? We are using the new way of setting up a mutation with an `InputObjectGraphType` with `Field<NonNullGraphType<StringGraphType>>("name");` What part of v2 is left behind to cause this error (perhaps a difficult question without seeing my code).

**Comment by Shane32** [comment] 2024-01-31 23:17
How the fields are configured have not really changed internally even though the recommended syntax is a bit different now.  If you want to post the before/after, I can confirm that it is being configured the same.

What's different (as it relates to your original issue here), is that the inputs are converted to their CLR types during validation rather than during execution.  This helps catch parsing errors before execution begins.  However, the GraphQL.NET engine has to guess at the `T` in `GetArgument<T>`, which it does so based on the `T` in `InputObjectGraphType<T>`.

For example:

```cs
public class User
{
    public string Name { get; set; }
}

public class MyInputType : InputObjectGraphType<User>
{
    public MyInputType
    {
        Field(x => x.Name);
    }

    protected override object? ParseDictionary(IDictionary<string, object?> dictionary)
    {
        // this is called during validation in v4, which by default calls ToObject to convert dictionary to User
        // if User was an interface (e.g. IUser), this would fail because ToObject cannot convert a dictionary
        // to an interface, as you can't create a new instance of IUser
        return base.ParseDictionary(dictionary);

        // in v2/3, this method did not exist, and essentially the dictionary itself was stored
        // until GetArgument<T> was called, at which point ToObject converts the dictionary to T

        // the workaround for v4+ for is then to just return the dictionary, so it is stored until GetArgument is called
        return dictionary;
    }
}
```

The issue would actually apply to both `InputObjectGraphType<T>` as well as `AutoRegisteringInputObjectGraphType<T>`.  However, `InputObjectGraphType` does not call `ToObject` (since it does not know what `T` is) and so it would be immune to this problem.

Note that the v8 beta compiles the `ToObject` code during schema initialization for faster execution and would notice the error then.  But not so for v7.

**Comment by Shane32** [comment] 2024-01-31 23:19
I'm not sure if that clarified anything further -- ??

**Comment by Shane32** [comment] 2024-01-31 23:29
If you use `InputObjectGraphType<T>` then the DI approach I mentioned previously won't help you unfortunately.   I'd probably do something like this:

```cs
public class UserType : MyInputObjectGraphType<IUser>
{
    public UserType
    {
        Field<NonNullGraphType<StringGraphType>>("name");
    }
}

// v4+ "fix" for interface types
public class MyInputObjectGraphType<T> : InputObjectGraphType<T>
{
    public override object ParseDictionary(IDictionary<string, object?> value) => value;
}
```

**Comment by dmongitss** [comment] 2024-02-01 00:37
Okay, so I was wrong. I thought I was using an `InsertObjectGraphType` but I am using `EntityInsertMutationTypeBase` instead.

**Comment by dmongitss** [comment] 2024-02-01 00:48
Aahhhhhh... `EntityInsertMutationTypeBase` is an internal class of an internal nuget package of ours. This just got a little deeper/problematic for me, hah.

**Comment by dmongitss** [comment] 2024-02-01 01:08
@Shane32 DUDE! MY DUDE! You saved me hours, at least!

```
        public override object ParseDictionary(IDictionary<string, object?> value)
        {
            return value;
        }
```

I must have some sort of Frankenstein input graph type even though not by specific name. Either way, that override satisfied the error. I would have never would have guessed the ParseDictionary signature let alone know to return value. The docs went clear over my head, too. 

I don't have an error and my data seems to have saved. I was too excited to even check the DB. I don't have errors!

Thank you so much!

**Closed** 2024-02-01 01:34 UTC
