### ISSUE TITLE
Asp.net Core GraphQL Middle ware issue

### ISSUE THREAD

**Issue by mohsin31** [graphql-dotnet/graphql-dotnet#902] opened 2018-11-10 00:30 UTC
I have an Asp.Net Core API with GraphQL middleware.
Issue when I host app to IIS.
Middleware works fine as long as I am not asking ISchema dependency.
If I remove this dependency and return static string from Invoke without calling next middleware it works.
As soon as I add this ISchema dependency app crash. I also have MVC middleware at the end I cannot even call MVC api end point when ISchema is present as a dependency to inject.
However, app works fine (even with ISchema  as dependency)  when I am using self hosting or Visual Studio development server IIS express
 public async Task Invoke(HttpContext context, ISchema schema)

Please help.

**Comment by joemcbride** [comment] 2018-11-10 00:39
What error are you getting and how are you registering your Schema with your DI container?  I’ve deployed this to IIS without issue so there is a problem with your setup.

**Comment by mohsin31** [comment] 2018-11-10 02:12
Hi Joe,
Thanks for your quick response.
Yes, using IServiceCollection.
Did you deploy using IIS as reverse proxy?
I a asking because when I self host this App using Http.sys middleware just work fine and same is the case with Kestrel.
I pasted entire ConfigureServices method.


  public void ConfigureServices(IServiceCollection services)
        {
            services.AddScoped<GKASContext>();
            services.AddScoped<IUnitOfWork, EFUnitOfWork>();

            services.AddScoped<IAppSettingRepository, AppSettingRepository>();
            services.AddScoped<IEmailMessageRepository, EmailMessageRepository>();
            services.AddScoped<IProfileRepository, ProfileRepository>();
            services.AddScoped<IEventRepository, EventRepository>();
            services.AddScoped<IProductShippingAddressRepository, ProductShippingAddressRepository>();
            services.AddScoped<IEventVolunteerRepository, EventVolunteerRepository>();
            services.AddScoped<IPatientRepository, PatientRepository>();
            services.AddScoped<IPatientProcedureRepository, PatientProcedureRepository>();
            services.AddScoped<IEventActualNumberRepository, EventActualNumberRepository>();
            services.AddScoped<IImageRepository, ImageRepository>();
            services.AddScoped<IReportingRepository, ReportingRepository>();

           


            services.AddScoped<IContactTypeRepository, ContactTypeRepository>();
            services.AddScoped<IParticipantTypeRepository, ParticipantTypeRepository>();
            services.AddScoped<IMinAgeRepository, MinAgeRepository>();
            services.AddScoped<IMaxAgeRepository, MaxAgeRepository>();
            services.AddScoped<IEventTypeRepository, EventTypeRepository>();
            services.AddScoped<IVolunteerTypeRepository, VolunteerTypeRepository>();
            services.AddScoped<IOptionsRepository, OptionsRepository>();
            services.AddScoped<ICDTCodeRepository, CDTCodeRepository>();

            services.AddScoped<IEventProductRepository, EventProductRepository>();
            services.AddScoped<IAdministrativeRepository, AdministrativeRepository>();
            services.AddScoped<ICDTCodePriceRepository, CDTCodePriceRepository>();     

            services.AddScoped<IGkasService, GkasService>();
            services.AddScoped<IAdministrationService, AdministrationService>();
            services.AddScoped<ILogService, LogService>();
            services.AddScoped<IReportingService, ReportingService>();
            services.AddScoped<IPublicService, PublicService>();
            services.AddScoped<IImageService, ImageService>();
            services.AddScoped<IMigrationService, MigrationService>();
            services.AddScoped<IAptifyService, AptifyService>();

            services.AddScoped<IDropDownService, DropDownService>();
            services.AddScoped<IProfileService, ProfileService>();
            services.AddScoped<IEventService, EventService>();


            services.AddSingleton<EventTypeViewType>();
            services.AddSingleton<MaxAgeViewType>();
            services.AddSingleton<MinAgeViewType>();

            services.AddScoped<optionSettingViewResolver>();

            services.AddScoped<ProfileViewType>();
            services.AddSingleton<ContactTypeViewType>();
            services.AddSingleton<ParticipantTypeViewType>();
            services.AddScoped<EventViewProfileType>();
            services.AddSingleton<VolunteerTypeViewType>();
            services.AddSingleton<EventProductViewType>();
            services.AddSingleton<CDTCodeViewType>();

            services.AddSingleton<AppSettingViewType>();
            services.AddSingleton<OptionsViewType>();

            services.AddSingleton<EventVolunteerViewType>();

            services.AddSingleton<AddEventResponseType>();
            services.AddSingleton<CreateEventInputType>();


            services.AddScoped<EventOptionViewType>();
            services.AddScoped<ProfileOptionViewType>();
            services.AddScoped<DuringEventOptionsViewType>();
            services.AddScoped<AfterEventOptionsViewType>();

            services.AddScoped<ProfileViewEventType>();

            services.AddScoped<EventViewType>();
            services.AddScoped<GkasGraphQLQueries>();
            services.AddScoped<ISchema, GkasSchema>();


            services.AddScoped<EventViewModelType>();
            services.AddSingleton<ProductShippingAddressViewType>();


            services.AddScoped<GKASMutation>();

            services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
            services.AddSingleton<IDocumentWriter, DocumentWriter>();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.AddMvc()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Formatting = Formatting.Indented;
                });

            var connection = @"Server=R9-0AHXAB;Database=GraphQL_GKAS_New;Trusted_Connection=True;ConnectRetryCount=0";
            string migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddDbContext<GKASContext>
                (options => options.UseLazyLoadingProxies().UseSqlServer(connection, migration => migration.MigrationsAssembly(migrationsAssembly)));


            services.AddDbContext<ApplicationDbContext>(options => {
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
            });

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddAuthentication(options => {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
            })
            .AddJwtBearer(options => {
                options.SaveToken = true;
                options.RequireHttpsMetadata = false;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = true,
                    ValidateAudience = true,
                    ValidIssuer = "JWTCore.Token",
                    ValidAudience = "JWTCore.Token",
                    IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("thisisasecuritykeyfortesting"))
                };
            });


            //ServiceProvider serviceProvider = services.BuildServiceProvider();
            services.AddScoped<IDependencyResolver>(
            c => new FuncDependencyResolver(type => c.GetRequiredService(type)));


            services.AddGraphQLAuthorization(_ =>
            {
                _.AddPolicy("AdminPolicy", p => p.RequireClaim("http://schemas.microsoft.com/ws/2008/06/identity/claims/role", "Admin"));
            });



            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

**Comment by SimonCropp** [comment] 2019-03-02 10:05
@mohsin31 can u answer joes question?

**Comment by sungam3r** [comment] 2019-09-05 21:26
Closed as can't reproduce.

@mohsin31 If the problem persists feel free to post Asp.Net Core issue to the [server project](https://github.com/graphql-dotnet/server).

**Closed by sungam3r** 2019-09-05 21:26 UTC
Labels: can't reproduce
