### ISSUE TITLE
IntGraphType is rounded for large numbers, only first 16 digits are correct

### ISSUE THREAD

**Issue by kristofytp** [graphql-dotnet/graphql-dotnet#1205] opened 2019-07-03 14:54 UTC
I have a IntGraphType field.

The value I put into that field is 636474637870330463

The value that we get on the client is 636474637870330400 (notice the 00 at the end)

If I make the value even larger (adding a number in the front) that will cause an extra 0 to appear at the end!

I have tested this with the debugger, the problem occurs somewhere in the resolve function of the field, even when I put hardcoded the correct value, the last 2 digits are converted to 0.

**Comment by sungam3r** [comment] 2019-07-03 21:26
@kristofytp I checked this issue on master branch. Everything works as it should.

**Comment by kristofytp** [comment] 2019-07-04 06:07
Hi,

I just updated to the latest nuget package version just to be sure, but I still have the problem...
![image](https://user-images.githubusercontent.com/37297985/60643148-7e896e00-9e32-11e9-9233-3a43c79cf98f.png)

When debugging I see the correct value being returned in the resolver:
![image](https://user-images.githubusercontent.com/37297985/60643185-93660180-9e32-11e9-87c2-b477bc953f85.png)

But the wrong value ends up on the client:
![image](https://user-images.githubusercontent.com/37297985/60643212-9f51c380-9e32-11e9-9832-ae52e9d5edbd.png)

Any ideas about what I can check to resolve this are very welcome!

**Comment by kristofytp** [comment] 2019-07-04 06:27
Something else I noticed, when I cast the long to a double and then back to a long, it looses some precision, and the last 3 digits become 871

Rounding that would cause the 9 to appear as 3rd last digit... So that would explain how it can get "rounded" from 811 to 900 at the end

Is it possible there happens some conversion to double somewhere along the line?

**Comment by sungam3r** [comment] 2019-07-04 07:00
Try https://www.nuget.org/packages/GraphQL/3.0.0-preview-1175 and appropriate server preview packages. Also problem may be not in graphql-dotnet but with Playground client - try send http request manually.

**Comment by kristofytp** [comment] 2019-07-04 08:08
Ok, I'll have to try that later.

When I try this I get a MissingMethodException when setting the UserContext, also I cannot use a preview version on our production server so I cannot use it for real anyway for now.

**Comment by sungam3r** [comment] 2019-07-04 17:08
MissingMethodException is a known problem. Use https://www.nuget.org/packages/GraphQL.Server.Transports.AspNetCore/3.5.0-alpha0014 and other packages with this version

**Comment by sungam3r** [comment] 2019-09-05 07:37
@kristofytp  Did you manage to solve the problem?

**Comment by sungam3r** [comment] 2019-09-08 19:25
@kristofytp I close this issue because I can not reproduce the error. I added the test to the master branch. As I said earlier you can use the latest graphql/server packages from [myget](https://myget.org/F/graphql-dotnet/api/v3/index.json). Feel free to reopen if the problem persists.

**Closed by sungam3r** 2019-09-08 19:25 UTC
Labels: needs investigation
