### ISSUE TITLE
Variable input of type [Seconds]! not parsing to array of TimeSpans

### ISSUE THREAD

**Issue by raphaabreu** [graphql-dotnet/graphql-dotnet#1312] opened 2019-09-22 17:53 UTC
## Description

Passing an array of ints as variable to a query that takes [Second]! throwing an exception.

### Steps to reproduce

Using the schema:
```
schema {
  query: TestQuery
}

type TestQuery {
  test(
    ranges: [Seconds]!
  ): [Test]
}

type Test {
  range: Seconds
}

scalar Seconds
```

Query:
```
query($ranges: [Seconds]!) {
  test(
    ranges: $ranges
  ) {
    range
  }
}
```

Variables:
```
{
  "ranges": [ 100, 200 ]
}
```

### Expected result

The ranges parameter should be parsed as an array of TimeSpan.

### Actual result

```
GraphQL.ExecutionError: Error trying to resolve isochrones. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: item
   at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
   at GraphQL.ObjectExtensions.GetPropertyValue(Object propertyValue, Type fieldType)
   at GraphQL.Types.ResolveFieldContext`1.GetArgument[TType](String name, TType defaultValue)
   at Wappa.Geo.Atlas.Api.GraphQL.AtlasQuery.<>c__DisplayClass0_0.<<-ctor>b__2>d.MoveNext() in C:\\Users\\raphael.abreu\\Projects\\geo.atlas\\Wappa.Geo.Atlas.Api\\GraphQL\\AtlasQuery.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at GraphQL.Instrumentation.MiddlewareResolver.Resolve(ResolveFieldContext context)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)
   --- End of inner exception stack trace ---
``` 

### Environment

```
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <PackageReference Include="GraphQL" Version="2.4.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.4.0" />
```

**Comment by sungam3r** [comment] 2019-09-22 20:04
@raphaabreu Please first try the latest (preview) versions of aforementioned packages from nuget.org

**Comment by raphaabreu** [comment] 2019-09-23 11:56
@sungam3r, I can't put a preview version in production. 2.4.0 is the latest available and by far the most used, is it already not supported any longer?

**Comment by sungam3r** [comment] 2019-09-23 20:46
All development goes in preview versions. I will write a test that reproduces your situation. Perhaps the error will persist.

**Comment by barticus** [comment] 2019-10-21 02:03
@sungam3r , apologies if this has been fixed (i haven't tried this on the preview branch) but I have created a small project to reproduce this issue, here: https://github.com/barticus/graphql-dotnet-timespan-bug
Please follow readme for instructions. The bug seems to be limited to variables being parsed from the request.

Hope this helps!
I would just write a PR to fix it but I'm still wrapping my head around how the library works.

**Comment by sungam3r** [comment] 2020-01-10 06:48
@barticus I have correct response using last preview:

```json
  "data": {
    "setItem": {
      "intField": 2000,
      "timeSpanField": 1500
    }
  }
```

**Comment by sungam3r** [comment] 2020-01-10 06:57
@raphaabreu I have correct response for `Seconds` array using last preview.

```graphql
mutation($input: [Seconds]!) {
  setItem(input: $input)
}
```

```json
{
  "input": [ 100, 200 ]
}
```

response
```json
 "data": {
    "setItem": [
      100,
      200
    ]
  }
```

schema:
```c#

            Field<ListGraphType<TimeSpanSecondsGraphType>>(
               "setItem",
               arguments: new QueryArguments(
                   new QueryArgument<NonNullGraphType<ListGraphType<TimeSpanSecondsGraphType>>> { Name = "input" }
               ),
               resolve: context =>
               {
                   var input = context.GetArgument<TimeSpan[]>("input");
                   return input;
               });
```

**Comment by sungam3r** [comment] 2020-01-10 06:59
> I can't put a preview version in production. 2.4.0 is the latest available 

In fact, the latest previews are much more stable (have less errors) than version 2.4.0. I have been using previews on production for a long time.

Closing this issue.

**Closed by sungam3r** 2020-01-10 06:59 UTC
Labels: bug
