### ISSUE TITLE
NULL_REFERENCE error from ApplyTypeReference in GraphTypesLookup

### ISSUE THREAD

**Issue by diouxis** [graphql-dotnet/graphql-dotnet#978] opened 2019-01-15 01:00 UTC
## Description

The system throw the `Object reference not set to an instance of an object.` and the whole API doesn't work anymore.

### Steps to reproduce

I have a GraphQL gateway API and with relay in the front end. The whole system works well in the beginning, but if I don't do any transaction in the front end for about 10~20 mins, and then refresh the page, this error comes. 
Beyond this, as long as I get this error, the whole API doesn't work anymore, and I have to restart the kestrel service. It will back to work after restarting, but the issue will still come again after.

### Expected result

The API works normally.

### Actual result

The whole API goes down, and have to restart kestrel service to make it back.
The following is the detail of the exception I got.
```json
{
  "errors": [
    {
      "message": "GraphQL.ExecutionError: Object reference not set to an instance of an object. ---> 
System.NullReferenceException: Object reference not set to an instance of an object.
at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass23_0.<ApplyTypeReference>b__0(IInterfaceGraphType i) 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 364
at System.Linq.Enumerable.SelectListIterator`2.ToList()   
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)   
at GraphQL.Types.GraphTypesLookup.ApplyTypeReference(IGraphType type) 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 349
at GraphQL.Types.GraphTypesLookup.ApplyTypeReferences() 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 325
at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter) 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 84 
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)   
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)   
at System.Lazy`1.CreateValue()
at GraphQL.Types.Schema.FindType(String name) 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\Schema.cs:line 208   
at GraphQL.Types.Schema.Initialize() 
  in repos\\graphql-dotnet\\src\\GraphQL\\Types\\Schema.cs:line 110  
at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) 
  in repos\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 123   
--- End of inner exception stack trace ---",
      "extensions": {
        "code": "NULL_REFERENCE"
      }
    }
  ]
}
```

### Environment

**GraphQL API**  
Graphql.Net 2.3/2.4, GraphQL.Server.Transports.AspNetCore 3.4, running on .NET Core 2.2
Host on kestrel via Nginx
OS: Ubuntu

**Front End**
React with Relay

**Comment by diouxis** [comment] 2019-01-23 00:02
**Update:**

I can see the issue is coming from the following code
https://github.com/graphql-dotnet/graphql-dotnet/blob/0917a2c8c3f7fc078ce4429f0edc3b051ef949c9/src/GraphQL/Types/GraphTypesLookup.cs#L349-L367
For some reason, `objectType.ResolvedInterfaces` might get one more additional null value at the end of `ResolvedInterfaces`, and this make the `interfaceType.AddPossibleType(objectType);` throw NULL_REFERENCE  exception.

I still have no idea how does the null value come, meantime I am doing the following to temporarily avoid the issue.
```c#
                objectType.ResolvedInterfaces = objectType
                    .ResolvedInterfaces
                    .Where(x => x != null)
                    .Select(i =>
```

**Comment by sungam3r** [comment] 2019-04-06 21:45
> I still have no idea how does the null value come.

Yes, in the code there was the possibility of accidentally or intentionally adding the `null` value through public api and thereby postpone the error until a later time, losing context.

**Comment by wanhchai** [comment] 2019-06-24 03:54
Any update on this issue? I have the same problem here.

**Comment by sungam3r** [comment] 2019-06-24 08:23
@wanhchai try the latest preview version of graphql nuget package

**Comment by wanhchai** [comment] 2019-06-24 08:30
I'm using version 2.4.0, although I can't re-create the issue once I restart the kestrel service(I was searching solution and tried what the poster did) so now it works but I can't be sure it won't happen again since I have not found the root cause yet.  I tried to wait the service to idle for like 1 hr.

**Comment by sungam3r** [comment] 2019-06-24 13:43
2.4.0 is rather old (stable or not) version. Since then, quite a few changes have been made, including on the described problem.

**Comment by wanhchai** [comment] 2019-07-09 05:33
Hi, I tried 3.0 it still has the same issue. is anyone facing the same issue?  we have micro-services and one of them is using Interface type which is the one that has this issue.

**Comment by PTangtanakul** [comment] 2019-07-11 12:20
Hello, I also have this issue even in 3.0.0-preview-1175

I can recreate this issue using the JMeter to fire multiple request to test it.
Just by having interface type in the schema will cause the issue to happen..
it will occur at some point no matter what you're querying for.

here's the list of dependencies I used.
I don't think some of this are related to the problem but... just in case

    <PackageReference Include="GraphQL" Version="3.0.0-preview-1175" />
    <PackageReference Include="GraphQL.Authorization" Version="3.0.35-preview-35" />
    <PackageReference Include="GraphQL.Client" Version="2.0.0-alpha.3" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0014" />
    <PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.5.0-alpha0014" />
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="3.5.0-alpha0014" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0014" />
    <PackageReference Include="GraphQL.Server.Ui.Voyager" Version="3.5.0-alpha0014" />

if you want any more info or which part of the code please tell me.

**Comment by sungam3r** [comment] 2019-08-30 20:46
@PTangtanakul I think that I found one more place where an error could have occurred. Please try to repeat issue when #1273 will be merged.

**Comment by sungam3r** [comment] 2019-10-12 10:56
@diouxis , @PTangtanakul Did you manage to solve this problem?

**Comment by diouxis** [comment] 2019-10-14 01:54
@sungam3r sorry, but I stopped using Interface feature for the meantime, and this problem was randomly happened in my case. So, it is hard for me to test or reproduce it.

**Comment by sungam3r** [comment] 2019-10-14 06:26
I think we can close this issue so as not to scatter attention. If it repeats on the latest versions of the package, then open a new task and we will figure it out.

**Closed by sungam3r** 2019-10-14 06:26 UTC
Labels: needs confirmation
