### ISSUE TITLE
Support System.Text.Json as default

### ISSUE THREAD

**Issue by bklooste** [graphql-dotnet/graphql-dotnet#1410] opened 2019-11-11 00:12 UTC
By default Core 3.0 apps now use this and it wont deserialize JObject , this can be a big issue as trivially you set up one serializer  and you cant just switch to newtsoft since it cant deserialize JsonElement which may be used by other apps / libs.

**Comment by joemcbride** [comment] 2019-11-11 02:08
Duplicate of #1148

**Closed by joemcbride** 2019-11-11 02:08 UTC
Labels: duplicate
