### ISSUE TITLE
Default variable values don't work with custom scalars

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/graphql-dotnet#2267] opened 2021-02-09 01:12 UTC
To repro, edit the sample chat app in the GraphQL.Server project slightly:

ChatQuery.cs - add a filter on SentAt:
``` csharp
using System;
using System.Linq;
using GraphQL.Types;

namespace GraphQL.Samples.Schemas.Chat
{
    public class ChatQuery : ObjectGraphType
    {
        public ChatQuery(IChat chat)
        {
            Field<ListGraphType<MessageType>>("messages",
                arguments: new QueryArguments(new QueryArgument(new DateGraphType()) { Name = "sentAt" }),
                resolve: context => chat.AllMessages.Where(m => m.SentAt == (DateTime)context.Arguments["sentAt"]));
        }
    }
}
```

IChat.cs line 25 - add dummy data:
``` csharp
AllMessages = new ConcurrentStack<Message>(new[]
{
    new Message { SentAt = new DateTime(2021, 2, 9), Sub = "sub", From = new MessageFrom { Id = "id", DisplayName = "name" }, Content = "content" }
});
```

Call with the following GraphQL query (no variables provided):
``` graphql
query ($sentAt: Date = "2021-02-09") {
  messages(sentAt: $sentAt) {
    from {
      id
    }
  }
}
```

Expect the dummy message to come back. Instead get an invalid cast exception in the resolver because it was parsed as a string rather than a DateTime.

**Comment by Shane32** [comment] 2021-02-09 05:21
@adamjones1 Variable parsing was considerably updated with version 4, which is about to be released any day now (just waiting on a couple bugs to be patched).  However, the server project has not been updated to work with version 4 yet.  I suggest we hold off on this issue until it can be tested with GraphQL.Net version 4.

**Comment by Shane32** [comment] 2021-02-24 00:24
@sungam3r We should check this out before v4 is released.  I'm concerned that in certain cases literal default values get converted to an AST node, then back into the original value.  If this happens - and is necessary - it should use a generic `ValueNode<T>` instance so that it will never be converted and always end up as the original data type.  We can then delete all of the unnecessary AST classes like Guid and SByte which are never used otherwise.

**Comment by Shane32** [comment] 2021-02-24 00:27
Truthfully we can probably fix this in 4.1 without breaking the api.

**Comment by Shane32** [comment] 2021-02-24 04:28
@sungam3r So I looked through this pretty extensively and wrote a bunch of code, then wondered if I should have, etc, etc.  The only actual bug I could find was as follows:

When you have a custom scalar type, and you are relying on `System.Text.Json` to serialize the custom type, then setting `DefaultValue` of a field will fail due to the "hack" in #1805 which was intended to fix #1795 .

https://github.com/graphql-dotnet/graphql-dotnet/blob/a1c639d1b21a9828f6a69e7e90d83cc731705897/src/GraphQL/Types/Fields/FieldType.cs#L21...L32

The code takes the value provided and converts it to an AST to validate it, which calls `ScalarGraphType.Serialize` and then takes the result and dumps it in an AST node.

https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/src/GraphQL/GraphQLExtensions.cs#L541

Since it can't find a match for the type returned by the custom scalar's Serialize method, it throws an exception.  However, this should not be a problem, as the custom scalar was relying on `System.Text.Json` to serialize the value.

One solution is to simply take the serialized value and dump it into a new `class UnknownValue : ValueNode<object>` instance.  Another is to revert the change in #1805.

**Comment by sungam3r** [comment] 2021-02-24 12:30
Now since we have schema validation visitors we _may_ validate `DefaultValue` for fields and arguments on schema initialization so in such context we have access to schema. So this hack can be removed as well as one from `QueryArgument.DefaultValue`. 
Checking when initializing a schema is much easier.

**Comment by sungam3r** [comment] 2021-02-24 13:35
I propose to gradually get rid of the `AstFromValue` method. It is used in few places. In some of them it can be removed entirely, and in the other part it can be replaced. I can take it upon myself.

**Comment by Shane32** [comment] 2021-02-24 21:43
Proposed fix in #2321

**Comment by sungam3r** [comment] 2021-03-05 22:27
@adamjones1 I think that the problem is in `(DateTime)context.Arguments["sentAt"]`. Change it to `context.GetArgument<DateTime>["sentAt"]`. Indeed, for input values dates are represented as strings. Also ping @Shane32 . Closing?

**Comment by Shane32** [comment] 2021-03-06 01:26
Default variables work properly with custom scalars now. See #2321 and #2341 . Also have a test within #2357 that demonstrates a default variable for a custom scalar within a code-first schema.

**Closed by Shane32** 2021-03-06 01:26 UTC
Labels: needs confirmation

**Comment by adamjones1** [comment] 2021-03-06 13:18
Thanks. A few questions:

1) In my original code where I encountered the error, I was actually getting the argument value from `context.FieldDefinition.Arguments`, not `context.Arguments`. Is the indexer on both of these equivalent? (ie. can I switch to `context.Arguments` without a change in behaviour and thus safely to `context.GetArgument<>()` with the improved behaviour?)

2) If `context.Arguments` and `context.FieldDefinition.Arguments` are both dangerous for resolvers to access because they don't carry the arguments in a type matching `context.FieldDefinition.Type`, should they be exposed to them at all?

3) In the use case of my original code it's more useful to me to have the arguments as a dictionary of objects, so I would end up reconstructing what I had expected `context.FieldDefinition.Arguments` to be by using the non-generic `context.GetArgument(Type, string, object)` method and passing in `context.FieldDefinition.Type` as the type. Not quite as simple but it's workable. Does this function 'correctly' like the generic `GetArgument` method does? \
\
Also, I notice it takes a default value for when the argument isn't present and so it's presumably impossible to distinguish here between a null value and a missing value. This is ok if I can obtain the list of present names elsewhere on the context. I could use `context.Arguments.Keys` but I notice `context.Arguments`' docs say the names in it might not be correct due to not having been passed through an `INameConverter`? Is there a recommended way to do what I'm attempting here?

**Comment by sungam3r** [comment] 2021-03-06 14:25
1. `FieldDefinition.Arguments` is arguments' _definitions_ (see `QueryArguments` type), not values. `context.Arguments` is `IDictionary<string, ArgumentValue>` i.e. _actual_ values.
2. They both are not "dangerous".
3. Both generic and non-generic `context.GetArgument` methods do the same.

> Also, I notice it takes a default value for when the argument isn't present and so it's presumably impossible to distinguish here between a null value and a missing value.

`context.HasArgument` may help.

**Comment by adamjones1** [comment] 2021-03-06 14:53
1. Apologies, brainfart, I misread my own code there 🤦. I do use `context.Arguments`.
2. What's the contract of the `context.Arguments` property? For it to be useful the resolver has to know what to expect the runtime types of its values to be, no? I had assumed these would be `context.FieldDefinition.Arguments["myArgument"].Type` for each one (correction to `context.FieldDefinition.Type` that I said above, clearly not having a good day today), but if not what should they be?
3. `context.HasArgument` does help, thanks.

**Comment by Shane32** [comment] 2021-03-06 15:14
The argument values’ .Net types are determined by the scalar or input object’s parsing function. There is no contract for what they will return. It might be convenient if the context.Arguments property returns the associated QueryArgument along with the value. But then it might be just as easy to look it up in the FieldDefinition.Arguments list.

**Comment by adamjones1** [comment] 2021-03-06 22:03
Hmm, ok - this wasn't the case in my initial repro though, as `DateGraphType.ParseValue` returns a `DateTime` - or were you saying above this is fixed in 4.0?

**Comment by Shane32** [comment] 2021-03-06 22:32
What are we talking about @adamjones1  ?  My last comment, I was just saying that there is no "Type" field that says that `DateTimeGraphType.ParseValue` will always return `DateTime`.  The method's return value is typed as an object.  You and I know from looking at the code that it will always return a `DateTime`.  But `IdGraphType.ParseValue` could return `int` or `long` or `string`.

**Comment by adamjones1** [comment] 2021-03-06 23:28
Sorry what I meant was - in the original code I quoted in this issue, in the sample chat app, it failed because `context.Arguments["sentAt"]` wasn't a `DateTime` - however you said just above that the arguments' .Net types are determined by the ScalarGraphType's parsing function. In this case, that parsing function is `DateGraphType.ParseValue`, which we know returns an instance of a `DateTime`, so it looks like something's off unless you were saying above in this thread (I didn't fully delve through) that this mismatch is fixed in 4.0.

**Comment by Shane32** [comment] 2021-03-06 23:35
Ahh. I’d have to take a look. We have done a lot of work across multiple large PRs that affect context.Arguments. Perhaps you could test against the v4 code in the develop branch and let me know if you experience the same problem. Note that context.Arguments now is a dictionary of ArgumentValue structs so they can convey the source of the value.

**Comment by adamjones1** [comment] 2021-03-07 13:18
Sure - I just checked in the `develop` branch (I assume this is the v4 code) and it looks fixed now!
