### ISSUE TITLE
Github example for schema first approach

### ISSUE THREAD

**Issue by sukruthakittur** [graphql-dotnet/graphql-dotnet#1728] opened 2020-07-15 19:32 UTC
Is there a decent example of using schema first approach? There are so many questions floating about, and all answers in issue, but no sample code (and I dont mean the docs). I am looking for a runnable example of schema first approach.

**Comment by sungam3r** [comment] 2021-03-11 22:24
Closed as duplicate of #1025

**Closed by sungam3r** 2021-03-11 22:24 UTC
Labels: question
