### ISSUE TITLE
LONG exposed as an INT causing errors in definitions

### ISSUE THREAD

**Issue by dtjason** [graphql-dotnet/graphql-dotnet#1171] opened 2019-06-06 00:29 UTC
## Description

**LONG**s are exposed as an **INT** in the generated documentation.

It appears this is by design but a couple of issues come from this. I found other posts mentioning that LONG should be mapped to the IntGraphType.

The code below seems to handle accepting LONG numbers submitted to the API but this is covering up a deeper issue.
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/IntGraphType.cs#L26

Returning LONG numbers on resources look like INTs. This is causing auto-generated GraphQL API explorer playground tools to throw validation errors when you type LONG numbers. They believe the API will only accept an INT when in reality this .NET implementation will accept it just fine.

Additionally clients who may be generating typed code will generate an INT field which will fail when the API responds with a LONG number.

### Steps to reproduce

Create a resource model which has a property of type LONG (ex. UserId)
Perform a query filtering this resource by that property name. (ex. UserId)

arguments: new QueryArguments(new QueryArgument<NonNullGraphType<**IntGraphType**>> { Name = "userId" })

### Expected result

A type other than INT should be documented

**Comment by joemcbride** [comment] 2019-06-06 00:32
Agreed - now that we have a bunch of other custom scalars we should add a `LongGraphType`.

**Comment by sungam3r** [comment] 2019-06-06 07:46
> I found other posts mentioning that LONG should be mapped to the IntGraphType.

@dtjason, do you mean "should NOT be mapped" ?

see #1022 

Source of problem [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Utilities/GraphTypeTypeRegistry.cs): 
```c#
[typeof(long)] = typeof(IntGraphType),
```

@joemcbride , do I understand correctly that this
> we should add a `LongGraphType`

also means that the above line of code now should look like
```c#
[typeof(long)] = typeof(LongGraphType),
```

**Comment by dtjason** [comment] 2019-06-06 16:21
> > I found other posts mentioning that LONG should be mapped to the IntGraphType.
> 
> @dtjason, do you mean "should NOT be mapped" ?
> 
> see #1022

Thanks! Yep, looks like we're all on the same page about the issue.
I was specifically referring to documentation here which states INT and LONG should be mapped to IntGraphType which I disagreed with.

https://graphql-dotnet.github.io/docs/getting-started/schema-types/#scalars

**Comment by joemcbride** [comment] 2019-09-25 16:21
Closing this as a duplicate of #1022

**Closed by joemcbride** 2019-09-25 16:21 UTC
Labels: enhancement
