### ISSUE TITLE
Question: merging/selecting schema from multiple sub-projects.

### ISSUE THREAD

**Issue by ghost** [graphql-dotnet/graphql-dotnet#348] opened 2017-06-09 11:06 UTC
Thanks for graphql-dotnet. Regarding modularization of the schema and schema handling. I see that the schema for StarWars is mostly encapsulated in the StarWars project. However, I the StarWarsSchema type being used explicitly as the only schema in the GraphiQL project. I'd like to have, for example, one project per series, like StarTrek and StarWars, and keep the schemas and thier handling locally encapsulated in each respective project. GraphiQL and Apps will need a combined query resolution at runtime. I can think of a way to select the desired scheme using polymorphism and a factory-class etc. but I am wondering if there is a best-practice pattern here (.net) or thoughts regarding schema partitioning and modularization. Thanks!

**Comment by joemcbride** [comment] 2017-07-07 22:46
Thanks for the question, pretty much a duplicate of #291

**Closed by joemcbride** 2017-07-07 22:46 UTC
Labels: duplicate
