### ISSUE TITLE
DataLoader deadlock with multiple awaits

### ISSUE THREAD

**Issue by Cooke** [graphql-dotnet/graphql-dotnet#945] opened 2018-12-06 20:31 UTC
## Description

When a field resolver awaits a data loader after another await (on anything) the resolver id deadlocked.

### Steps to reproduce

Query the following field:
```c#
         Field<BooleanGraphType, bool>()
                .Name("True")
                .ResolveAsync(async ctx =>
                {
                    await Task.Delay(1);

                    var loader = accessor.Context.GetOrAddLoader("GetTrue",
                        () => Task.FromResult(true));

                    return await loader.LoadAsync();
                });
```

### Expected result

No deadlock

### Actual result

Deadlock

**Comment by Cooke** [comment] 2019-01-24 15:11
@saborrie I'm no longer working on a fix for this. I closed my pull request. 

The deadlock happens because data loaders are only run "once" when the resolvers await the first time. Consecutive awaits will not trigger the data loaders to run. For more details please take a look at my pull requests.

**Comment by benmccallum** [comment] 2019-08-06 22:45
Just ran into this. Good thing I landed here. A bit of an unfortunate one. 

In my case I think I'll be able to Task.WhenAll the two async ops I have to do (thx for the tip!), but what if someone relied on the result of an initial async to call a second async? They'd be royally screwed?

**Comment by joemcbride** [comment] 2019-08-07 14:49
@johnrutherford would this be potentially fixed by the refactoring done in #976 ?

**Comment by teo78** [comment] 2019-08-19 09:49
While I was working on PR #1251 I came to think about this issue. I believe this deadlock occurs because the assumption in the `ParallelExecutionStrategy` is that all asynchronous nodes executed will always wait at the `LoadAsync` of the dataloader (if the field uses a dataloader).
In normal cases it will and the `OnBeforeExecutionStepAwaitedAsync` will cause the awaits on `LoadAsync` of the dataloader to complete. 

However if the field is not awaiting the dataloader, but another operation (Such as `await Task.Delay(1);` in this case). The call to `OnBeforeExecutionStepAwaitedAsync` will not do anything since the call to `LoadAsync` of the dataloader has not happened yet. And finally the await for the currentTasks to complete will result in execution resuming after `await Task.Delay(1);`, but the `await LoadAsync()` will never complete since `OnBeforeExecutionStepAwaitedAsync` is not called again.

I tested repro example provided and it deadlocks in #976 aswell.

To test the theory this code in ParallelExecutionStrategy method ExecuteNodeTreeAsync: 
```cs
                await OnBeforeExecutionStepAwaitedAsync(context)
                    .ConfigureAwait(false);

                // Await tasks for this execution step
                var completedNodes = await Task.WhenAll(currentTasks)
                    .ConfigureAwait(false);
```
was changed with this which made the repro example succeed:
```cs
                var allTasks = Task.WhenAll(currentTasks);
                while (!allTasks.IsCompleted)
                {
                    await OnBeforeExecutionStepAwaitedAsync(context)
                        .ConfigureAwait(false);

                    // Await tasks for this execution step
                    await Task.Delay(10).ConfigureAwait(false);
                }
                var completedNodes = await allTasks;
```
Instead of awaiting the nodes them self (which is the cause of the deadlock), I await a small delay causing execution of nodes to continue, and then when they reach the `LoadAsync` of the dataloader the subsequent call to `OnBeforeExecutionStepAwaitedAsync` will cause it to complete.

By no means am I proposing this change, but it illustrates the problem. I'm not sure how it should be dealt with.

**Comment by teo78** [comment] 2019-08-19 11:38
I didn't look to closely at the comments and suggested change by @Cooke, but he obviously also noticed the issue being dataloaders only kicked of at the first await.

 Logically I believe this is what is needed:
```cs
                // Await tasks for this execution step, either to be completed OR WAITING ON A DATALOADER
                // Would need another approach than Task.WhenAll...
                var completedOrWaitingForDataloaderNodes = await Task.WhenAll(currentTasks)
                    .ConfigureAwait(false);

                // Here all nodes are either completed or waiting on a dataloader, so this call will kick of the dataloader
                await OnBeforeExecutionStepAwaitedAsync(context)
                    .ConfigureAwait(false);

                // Then it's safe to await all tasks since they will not deadlock on waiting for dataloader any more
                var completedNodes = await Task.WhenAll(currentTasks)
                    .ConfigureAwait(false);
```

But not sure how awaiting until nodes are either complete or awaiting a dataloader can be accomplished. Or changing it similar to the code example above (Which also adds a while loop and awaiting a Task.Delay to force re-running the dataloaders).

**Comment by DaniilSokolyuk** [comment] 2019-08-19 22:20
we use greendonut data loaders from HotChocolate in graphql-dotnet, works great
[here example](https://github.com/DaniilSokolyuk/graphql-dotnet-afisharu)

**Closed** 2020-08-28 22:18 UTC
Labels: bug, data loader
