### ISSUE TITLE
Hosting on IIS as a subsite

### ISSUE THREAD

**Issue by RaySheikh** [graphql-dotnet/graphql-dotnet#664] opened 2018-05-21 22:35 UTC
Hello,
I am having an issue publishing the site. Is there a way to manually configure the GraphQL endpoint as a subsite. Currently it auto defaults to the site root.
Result is 404.

eg: http://siteroot.com/**subsite**/graphql returns 404

**Comment by joemcbride** [comment] 2018-05-21 22:52
What middleware/endpoint are you using to host the GraphQL endpoint?

**Comment by RaySheikh** [comment] 2018-05-22 17:49
We are using IIS on windows server 2012

**Comment by joemcbride** [comment] 2018-05-23 16:34
@RaySheikh That's the webserver it is deployed to.  How did you create your `/graphql` endpoint?  What framework did you use?  ASP.NET Core?  ASP.NET Web Api?  If .NET Core did you write your own middleware or did you use the server nuget package?  Is there a different application running at http://siteroot.com and `subsite` is a new application that hosts the `/graphql` endpoint?

Maybe this will help?

https://stackoverflow.com/questions/4747576/sub-website-in-iis-asp-net

**Comment by RaySheikh** [comment] 2018-05-23 16:55
Hi Joe, I am running Asp.net Core 2.0.  Started the project with the WebApi projects, using the graphql nuget package. The siteroot is an empty application. All our sites are under the site root. 

Your link.. feedback, Yes, i created a virtual directory to host each sub-site under the root.

Thanks, 

Ray

**Comment by joemcbride** [comment] 2018-05-23 19:35
🤷‍♂️ Not sure how I can help.  That setup isn't something this project has control over.  My only suggestion would be to check the middleware or endpoint you're using to ensure it isn't expecting absolute paths.

**Comment by joemcbride** [comment] 2018-06-15 16:42
Going to close this as it is not an issue with this project.

**Closed by joemcbride** 2018-06-15 16:42 UTC
Labels: question

**Comment by Wasseratem** [comment] 2019-09-02 13:04
Hi,

I have the same problem.

My ISS has a site and the graphQL as subsite.

I could reproduce it localy (I normaly would only have this on live / test stage).

My mainsite is 
http://localhost:90

My Sub is:
http://localhost:90/test

My entry point should be:
http://localhost:90/test/graphql

And the clue is, that there is an error within the second window:
https://i.imgur.com/oNbaKFB.png

BUT when you look at the console, you see, that the requested path is not 
http://localhost:90/test/graphql

it is 
http://localhost:90/graphql

So basicly, the problem seems to be, that the "test", means the subdirectory will be cuted.
![image](https://user-images.githubusercontent.com/20551244/64116551-e9074d80-cd92-11e9-8e70-de67cc8aaa0b.png)
