### ISSUE TITLE
How to set Execution Timeout using this package

### ISSUE THREAD

**Issue by amber-ashraf** [graphql-dotnet/graphql-dotnet#3560] opened 2023-03-05 06:39 UTC
## Summary
I have been trying to find an option to set Execution Timeout for GraphQL, but could not find anything - any request taking longer than 1100 ms throwing 504 gateway timeout

**Comment by sungam3r** [comment] 2023-03-05 07:29
Do you want to set timeout on client or server side?

**Comment by amber-ashraf** [comment] 2023-03-05 08:03
On server side

**Comment by Shane32** [comment] 2023-03-05 17:07
There is no execution timeout setting within GraphQL.NET. Requests may take any length of time to execute. In a prior version of GraphQL.NET Server there was a sample demonstrating how to add a timeout, but that code does not exist in any current samples. So unless your code is based on that specific old sample, it is quite unlikely that GraphQL.NET is the cause of the timeout. 

If you would like to provide the relevant bits of your Startup.cs file along with the version numbers of any GraphQL.NET NuGet packages you have installed, I can let you know if I see anything else. 

Note that some hosting environments such as Azure App Services impose a mandatory maximum execution time. But it should be much longer than 1100ms.

**Comment by Shane32** [comment] 2023-03-05 17:09
Perhaps you could also list your hosting environment.

**Comment by sungam3r** [comment] 2023-03-05 17:36
You can configure timeout setting `ExecutionContext.CancellationToken`. Execution strategies check this token as well as some other classes. Also this token is passed into resolvers as `IResolveFiekdContext.CancellationToken`.

**Comment by sungam3r** [comment] 2023-04-03 21:23
Closing. Feel free to ask further questions if any.

**Closed by sungam3r** 2023-04-03 21:23 UTC
Labels: question
