### ISSUE TITLE
Using FieldMiddleware on Document Executer throws GraphQL.ExecutionError

### ISSUE THREAD

**Issue by maxr96** [graphql-dotnet/graphql-dotnet#881] opened 2018-10-26 08:26 UTC
## Description

Adding FieldMiddleware on DocumentExecuter doesn't work. My assumption is that problem is in this piece of code of DocumentExecuter:
```
                if (!options.Schema.Initialized)
                {
                    using (metrics.Subject("schema", "Initializing schema"))
                    {
                        if (options.SetFieldMiddleware)
                        {
                            options.FieldMiddleware.ApplyTo(options.Schema);
                        }
                        options.Schema.Initialize();
                    }
                }
```
Because when I either initialize schema before running Execute or don't use FieldMiddleware everything works fine.
### Steps to reproduce
I have a custom directive to format string to upper case. This is my Directive type that is added to schema directives.
```
    public class StringToUpperDirectiveType : DirectiveGraphType
    {
        public StringToUpperDirectiveType()
            : base("toUpper", new[] { DirectiveLocation.Field })
        {
        }
    }
```

I have a ```StringToUpperDirectiveMiddleware``` class with 
``` public async Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next) ``` 
and add it to the return of my Query Executor like this
 ``` 
return await new DocumentExecuter().ExecuteAsync(options =>
                {                    options.FieldMiddleware.Use(typeof(StringToUpperDirectiveMiddleware));}
```

### Expected result

Using ```@toUpper``` directive on a field goes to ```StringToUpperDirectiveMiddleware``` resolver and the field value is uppercased.

### Actual result

It throws :   
```
ExecutionErrors [GraphQL.ExecutionError: User error: expected an IEnumerable list though did not find one.
   at GraphQL.Execution.ExecutionStrategy.SetArrayItemNodes(ExecutionContext context, ArrayExecutionNode parent)
   at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)]
```

**Comment by joemcbride** [comment] 2018-10-26 15:13
There is middleware provided by this project that works, so there must be something about your setup that is causing the error to occur. Can you please provide the full source for the middleware?

**Comment by joemcbride** [comment] 2018-10-26 15:17
https://github.com/graphql-dotnet/graphql-dotnet/blob/952b4ef6950e51bbfe009354f0520180c343e8d4/src/GraphQL/Execution/ExecutionStrategy.cs#L97

That error is from here, which indicates that your field expects a list, though it isn’t getting one. Are you perhaps calling ToUpper on a list?

**Comment by maxr96** [comment] 2018-10-30 13:00
@joemcbride Thank you very much for the help. The problem for me was using async/await in a resolve method of StringToUpperDirectiveMiddleware. I replaced it with Task.FromResult<object>(). And I should mention, that before updating from 2.0.0-alpha to 2.3 it was working.

**Comment by johnrutherford** [comment] 2018-10-30 16:18
@maxr96, could you share some sample code? I’m not sure how that would make a difference. Whether you’re using Async/await or not, the return type would be the same.

**Comment by ullmark** [comment] 2019-01-14 13:30
I can confirm that I also got this issue when trying to use a FieldMiddleware that runs an async function with an await in it.

Works;
```csharp
public Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
{
    Task.Run(() => Thread.Sleep(100)).Wait();
     return next(context);
 }
```

Doesn't Work (Causes error above);
```csharp
public async Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
{
    await Task.Run(() => Thread.Sleep(100));
    return next(context);
 }
```

**Comment by sungam3r** [comment] 2019-10-12 18:31
`FieldMiddlewareDelegate` is:
```c#
public delegate Task<object> FieldMiddlewareDelegate(ResolveFieldContext context);
```
When you write
```c#
public Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
{
    //Task.Run(() => Thread.Sleep(100)).Wait();
   // var t = 1+1;
  // whatever 
     return next(context);
 }
```
then you just pass further `Task<object>` received from `next` call.

When you write
```c#
public async Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
{
    await Task.Run(() => Thread.Sleep(100));
    return next(context);
 }
```
then everything is getting a little more interesting since compiler actually **captures** your result when building a state machine asynchronous execution. Your result is `next(context)`. It is `Task<object>` but it is also `object`. So resulting object from `Resolve` method become `Task<Task<object>>`. In fact, there will be even more complex internal types of TPL (`AsyncStateMachineBox`, etc.), but for just an example you will not give them.

All you have to do is to await result so it will be "unwrapped" from one `Task<object>` and then immediately "wrapped" back to second `Task<object>`:
```c#
public async Task<object> Resolve(ResolveFieldContext context, FieldMiddlewareDelegate next)
{
    await Task.Run(() => Thread.Sleep(100));
    return await next(context);
 }
```

This is a fairly common mistake, as it can be difficult to notice because the code compiles successfully although the intent of the developer was different. This is one of the pitfalls of asynchronous programming in C#.

**Comment by sungam3r** [comment] 2019-10-12 18:32
By the way, `options.SetFieldMiddleware` was removed.

**Comment by sungam3r** [comment] 2019-12-02 06:15
Closed as resolved. Feel free to reopen if not.

**Closed by sungam3r** 2019-12-02 06:15 UTC
Labels: needs confirmation, question
