### ISSUE TITLE
String with limited size

### ISSUE THREAD

**Issue by emulicus** [graphql-dotnet/graphql-dotnet#1460] opened 2019-12-20 18:00 UTC
## Summary
Need to be able to limit size of the string field on arguments or mutation input graphs. Ideally, this would be something graphql client would be able to see in the schema and also show errors in graphiQL when they enter the value that's over the limit.
## Relevant information
 Also, since we base most of our input graph types on the entity framework entities ideally this length would come from that StringLength attribute on the EF entity property.

We're using graph types first approach. 
2.4 version.

**Comment by joemcbride** [comment] 2019-12-20 18:29
I'm not sure about showing info in the schema (maybe you can just add the requirement to the description for the field), but here is a validation framework that @SimonCropp put together.  It currently targets 2.4.

https://github.com/SimonCropp/GraphQL.Validation

**Comment by sungam3r** [comment] 2019-12-20 19:20
@emulicus This is a great task to solve with graphql directives.
```graphql
directive @length(max: Int!) on FIELD_DEFINITION

input Payload {
  name: String! @length(max: 50)
}
```

There are no problems in establishing our own directive in schema. The problem is to provide information about this directive to the client. Now the specification does not explicitly describe the possibility of returning directives through introspection, but this is a fairly popular request from the community. See  graphql/graphql-spec#300 

Also you may be interested in #1332 and #1451. We have been successfully using this fork in production for some time. In fact, we were interested in providing information about authentication and authorization directives. Maclean is the next directive that interests us.

**Comment by emulicus** [comment] 2019-12-20 22:33
Thank you, guys. I will check out your resources.

**Comment by emulicus** [comment] 2019-12-20 22:54
> I'm not sure about showing info in the schema (maybe you can just add the requirement to the description for the field), but here is a validation framework that @SimonCropp put together. It currently targets 2.4.
> 
> https://github.com/SimonCropp/GraphQL.Validation

This is a little rough for us, because most of our graph types are based on entity framework entities. Not sure if we could have a single validator that would check the length of the input and compare it to the StringLength attribute from the entity.

**Comment by emulicus** [comment] 2019-12-20 22:56
> @emulicus This is a great task to solve with graphql directives.
> 
> ```graphql
> directive @length(max: Int!) on FIELD_DEFINITION
> 
> input Payload {
>   name: String! @length(max: 50)
> }
> ```
> 
> There are no problems in establishing our own directive in schema. The problem is to provide information about this directive to the client. Now the specification does not explicitly describe the possibility of returning directives through introspection, but this is a fairly popular request from the community. See [graphql/graphql-spec#300](https://github.com/graphql/graphql-spec/issues/300)
> 
> Also you may be interested in #1332 and #1451. We have been successfully using this fork in production for some time. In fact, we were interested in providing information about authentication and authorization directives. @Length is the next directive that interests us.

Got it. Yeah, maybe combination of these two could work for us. We're populating the description with the stringLength coming from the entity. Any example on how to define directives in graphtype first approach?

**Comment by sungam3r** [comment] 2019-12-21 11:04
> Any example on how to define directives in graphtype first approach?

Well, #1451 is all about graphtype first approach.

**Comment by SimonCropp** [comment] 2020-01-09 01:46
@emulicus 

> Not sure if we could have a single validator that would check the length of the input and compare it to the StringLength attribute from the entity.

why is this not possible?

**Comment by manoochehrkateb** [comment] 2020-07-22 12:13
> > Any example on how to define directives in graphtype first approach?
> 
> Well, #1451 is all about graphtype first approach.

Hello Ivan ,
I Clone that branch and tested . 
But when it comes to run with Playground get errors .

```
    public class HumanInputType : InputObjectGraphType
    {
        public HumanInputType()
        {
            Name = "HumanInput";
            Field<NonNullGraphType<StringGraphType>>("name").AddDirective(new UppercaseDirectiveVisitor());
            Field<StringGraphType>("homePlanet");
        }
    }
```

> Uncaught Error: Name "__DirectiveUsage" must not begin with "__", which is reserved by GraphQL introspection.
> 
> Name "__DirectiveArgument" must not begin with "__", which is reserved by GraphQL introspection.
>     at g (validate.mjs:49)
>     at l (validate.mjs:33)
>     at validateWithCustomRules.js:16
>     at ut (getDiagnostics.js:39)
>     at st (getDiagnostics.js:33)
>     at lint.js:40
>     at u (lint.js:154)
>     at lint.js:202

![image](https://user-images.githubusercontent.com/15786908/88174787-19b9d500-cc3a-11ea-9d96-2d7a82884260.png)

**Comment by sungam3r** [comment] 2020-07-22 14:01
Strange, I saw a similar message, but in a different UI, not Playground. You may be using the version of Playground that added more strict checks (just guessing). We use Playground UI from [server project](https://github.com/graphql-dotnet/server#graphql-for-net---subscription-transport-websockets), it works well.

**Comment by manoochehrkateb** [comment] 2020-07-25 06:01
> Strange, I saw a similar message, but in a different UI, not Playground. You may be using the version of Playground that added more strict checks (just guessing). We use Playground UI from [server project](https://github.com/graphql-dotnet/server#graphql-for-net---subscription-transport-websockets), it works well.

Now I install 3.5.0-alpha0046 playground but nothing change . and tested on Altair and graphiql , its the same . 
I am used the exactly code on **TypeFirstSchemaDirectives** brach .

**Comment by sungam3r** [comment] 2021-02-06 20:06
#1451 with a lot of hanges and additions was merged. GraphQL.NET now supports working with directives. See https://github.com/graphql-dotnet/graphql-dotnet/blob/develop/docs2/site/docs/migrations/migration4.md for more information.

**Comment by sungam3r** [comment] 2021-02-14 19:58
@emulicus @manoochehrkateb  See #2276 . This is exactly what you were talking about. Now we are at the stage of reviewing and writing documentation for v4. I suggest we track our progress in #2276 and close this task. It will be good if you give your comments.

**Closed by sungam3r** 2021-02-14 19:58 UTC
Labels: directives, question
