### ISSUE TITLE
Error about duplicate union type.

### ISSUE THREAD

**Issue by Heuts** [graphql-dotnet/graphql-dotnet#3087] opened 2022-04-15 11:24 UTC
## Summary

I sometimes stumble upon a strange error in our GraphQL schema related to union types. I did my best to search for answer but haven't find anyone with a similar issue so far, which warrants me to create this issue.

## Relevant information

The error is related to union types and looks as following:
```json
{
  "error": "Invalid schema Error:\nUnion type ProductDrawsResult can only include type UpstreamServiceFailed once."
}
```

I've seen this happen before for other union types in our schema, so it does not seem related to this specific type.

I'll post the code of this type nonetheless for you guys to take a look:

```csharp
internal sealed class ProductDrawsResultType : UnionGraphType
    {
        public ProductDrawsResultType()
        {
            Name = "ProductDrawsResult";

            Type<ProductDrawsType>();
            Type<UpstreamServiceFailedType>();
        }
    }
```

The query still works as expected, but I can't load the schema.

It puzzles me, does anyone have a clue?

### Environment (if relevant)

GraphQL 4.7.1, OS Linux, .NET 6.0

**Comment by Shane32** [comment] 2022-04-15 12:16
Do you use the ResolveType delegate?

**Comment by Heuts** [comment] 2022-04-15 12:22
No I don't.

**Comment by Heuts** [comment] 2022-04-15 12:24
I just found a duplicate registration of one of our GraphQL types (not related to one shown in the error though). Could it be related to that?

```csharp
serviceCollection.AddSingleton<ProductLabelType>();
serviceCollection.AddSingleton<ProductLabelType>();
```

**Comment by Shane32** [comment] 2022-04-15 13:00
No it cannot

**Comment by Shane32** [comment] 2022-04-15 13:03
Is ProductDrawsType and UpstreamServiceFailedType both ObjectGraphTypes?

**Comment by Heuts** [comment] 2022-04-15 13:35
Yes they both are

```csharp
internal sealed class ProductDrawsType : ObjectGraphType<List<Draw>>
```

```csharp
internal sealed class UpstreamServiceFailedType : ObjectGraphType<UpstreamServiceFailedResult>
```

**Comment by Shane32** [comment] 2022-04-15 14:50
Can you capture a stack trace from the exception when the schema is initialized?

**Comment by Shane32** [comment] 2022-04-15 14:51
Which exaxt nuget packages and versions are you using?  I am having trouble finding the code that printed the error message.

**Comment by Shane32** [comment] 2022-04-15 14:54
Oh, is this an error displayed in GraphiQL or Playground or similar?  Perhaps this is a client error not a server error -- probably caused by an incorrect introspection query being returned by the server though.

**Comment by Shane32** [comment] 2022-04-15 14:58
Try running an introspection query on the type and let's see what is returned

```gql
query {
  __type(name:"ProductDrawsResult") {
    kind 
    name
    description
    fields {
      name
    }
    interfaces {
      kind
      name
    }
    possibleTypes {
      kind
      name
    }
    ofType {
      kind
      name
    }
  }
}
```

**Comment by sungam3r** [comment] 2022-04-16 21:59
Regarding this `internal sealed class ProductDrawsType : ObjectGraphType<List<Draw>>`. I'm not sure that `List<Draw>` is a right type to be used here. Try switch to  `ProductDrawType : ObjectGraphType<Draw>` and use `ListGraphType<ProductDrawType>` in other places.

**Comment by Heuts** [comment] 2022-04-17 17:46
> Can you capture a stack trace from the exception when the schema is initialized?

I unfortunately have not been able to reproduce this error locally so I didn't catch the exception yet. I've seen the error only a couple of times in our testing and acceptance environments and we're having issue with our logs there the past week so I could not capture the logs there. I will update once I find it. 

> Which exact GraphQL nuget packages and versions are you using? I am having trouble finding the code that printed the error message.

```
<PackageReference Include="GraphQL" Version="4.7.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="4.7.1" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.2.0" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.2.0" />
<PackageReference Include="GraphQL.Server.Transports.Subscriptions.WebSockets" Version="5.2.0" />    
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.2.0" />    
<PackageReference Include="GraphQL.SystemTextJson" Version="4.7.1" />
```

> Oh, is this an error displayed in GraphiQL or Playground or similar? Perhaps this is a client error not a server error -- probably caused by an incorrect introspection query being returned by the server though.

Yes this error is displayed in the playground.

> Try running an introspection query on the type and let's see what is returned

Alright that that and this is the response I'm getting, nothing looks out of the ordinary I believe

```json
{
  "data": {
    "__type": {
      "kind": "UNION",
      "name": "ProductDrawsResult",
      "description": "This query is used to retrieve the draws.",
      "fields": null,
      "interfaces": null,
      "possibleTypes": [
        {
          "kind": "OBJECT",
          "name": "ProductDraws"
        },
        {
          "kind": "OBJECT",
          "name": "UpstreamServiceFailed"
        }
      ],
      "ofType": null
    }
  }
}
```

> Regarding this internal sealed class ProductDrawsType : ObjectGraphType<List<Draw>>. I'm not sure that List<Draw> is a right type to be used here. Try switch to ProductDrawType : ObjectGraphType<Draw> and use ListGraphType<ProductDrawType> in other places.

I could give that a try but I don't think that could be related to the error I'm seeing?

**Comment by Shane32** [comment] 2022-04-17 17:53
I assume your schema is a singleton, correct?

I would look and see if you can find any graph types that use DI to inject another graph type (besides the root Query, Mutation and Subscription types), or anywhere you are manually instantiating a graph type.  It caused a problem with another user because graph types register as transients by default, not singletons.

**Comment by sungam3r** [comment] 2022-04-17 21:33
https://github.com/graphql/graphql-js/blob/15040d02eb3c5ce2122c9329d26df5cde5ff5b3f/src/type/validate.ts#L466

**Comment by Heuts** [comment] 2022-04-18 13:40
> I assume your schema is a singleton, correct?

Our schema is actually registered as scoped at the moment, could that be a problem?

> I would look and see if you can find any graph types that use DI to inject another graph type (besides the root Query, Mutation and Subscription types), or anywhere you are manually instantiating a graph type. It caused a problem with another user because graph types register as transients by default, not singletons.

I've checked our graph types and we're not using DI to inject other graph types anywhere in our project. We just reference to other graph types by using the `Field<>` syntax.

**Comment by Shane32** [comment] 2022-04-18 13:49
@Heuts You can read more about DI and how it is used by GraphQL.NET here:

https://graphql-dotnet.github.io/docs/getting-started/dependency-injection

**Comment by Shane32** [comment] 2022-04-18 13:50
Just FYI, a singleton schema is recommended for performance, but then you will need to make changes if your graphs depend on scoped services, since scoped services can't safely be pulled from a singleton.

**Comment by Heuts** [comment] 2022-04-18 13:52
Thanks for the info. Yeah I believe that's the reason why we went for a scoped schema, since we are dependent on scoped services in our domain layer. I see there are some recommendations in the documentation that you linked so we might be able to resolve these scoped dependencies following those steps.

**Comment by Heuts** [comment] 2022-04-18 13:53
You are amazingly quick at responding btw! 🙌

**Comment by Shane32** [comment] 2022-04-18 13:53
When I'm available 👍

**Comment by Shane32** [comment] 2022-04-18 13:55
To get up and running right now, just change all your graph type registrations to transient, such as the one you showed above:

```cs
serviceCollection.AddTransient<ProductLabelType>();
```

The you don't need to change them again if you switch to a singleton schema.  The only restriction on transient is you can't pull them into a graph type -- which is necessary when you use the `ResolveType` delegate -- which you're not using.

**Comment by Heuts** [comment] 2022-04-18 14:01
Thanks for the suggestion, I'll try to convince my team ;)

I just checked out the playground again and I get the following error now

```json
"error": "Invalid or incomplete schema, unknown type: MobileApiQuery. Ensure that a full introspection query is used in order to build a client schema."
```

Could this also be related to scoped schema with singleton graph types that we are having now?

**Comment by Shane32** [comment] 2022-04-18 14:05
Yes.  You're getting concurrency issues: every time a request comes in, the schema initializes all of the graph types, creating links between them all.  If another request comes in _at the same time_, it is initializing those same graph type instances again, and concurrency problems can cause internal lists to contain duplicate entries or be missing entries.  You probably don't see it in dev because you don't typically have two schemas initializing at the same time.

**Comment by Shane32** [comment] 2022-04-18 14:07
Also if some of your graph types are scoped and some are singleton, you can end up with situations where request A is accessing a singleton graph type that holds a pointer to a scoped graph type which was intended to be part of request B.  So then that particular request is using a scoped service from request B's service scope.  You might then get an ObjectDisposedException if request B ends early, or other concurrency issues inside of those scoped services.  Basically, a lot can go terribly wrong.

**Comment by Heuts** [comment] 2022-04-18 18:22
Yeah I'm starting to feel our DI registration is a bit of a mess and is causing all of these issues. Once again thanks for my eyes to this, I'll definitely revisit our graphql types DI registration.

**Comment by sungam3r** [comment] 2022-04-18 22:03
@Heuts I close this but you may ask additional questions if any.

**Closed by sungam3r** 2022-04-18 22:03 UTC
Labels: question
