### ISSUE TITLE
Map input fields.

### ISSUE THREAD

**Issue by SebastianStehle** [graphql-dotnet/graphql-dotnet#684] opened 2018-06-05 21:36 UTC
Hi, 

I have the following use case:

My objects are nested dictionaries (JObjects). But the keys are not always valid for GraphQL,e g. the contain dashes or underscores.

But of course I can easily map them:

	string key; // From internal schema definition.
	
	var resolver = new FuncFieldResolver<object>(c =>
	{
		if (((JObject)c.Source).TryGetValue(key, out var value))
		{
			return fieldInfo.Resolver(value, c);
		}
		else
		{
			return fieldInfo;
		}
	});

	AddField(new FieldType
	{
		Name = key.ToCamelCase(),
		Resolver = resolver,
		ResolvedType = fieldInfo.ResolveType,
	});

But I cannot do something similar for the input types, because I just get a nested IDictionary<string, object>. Is there a solution I don't see, except than converting the final dictionary? It would be great to have something like a reverse resolver so that I can also skip the generation of the IDictionary and create the objects manually or set the properties.

**Comment by joemcbride** [comment] 2018-06-06 00:37
I'm not sure I'm fully understanding what you're trying to do.  You are trying to dynamically build a Schema based on JObjects?  Or are you fetching data, returned as JObjects, and you're trying to return those values in the resolver?  Can you provide an example of what you're expecting the input arguments to look like in GraphQL Schema syntax?

Ex:

```
input CreateInput {
  name: String
  age: Int
}

type Query {
  person(id: String): Person
  createPerson(input:CreateInput): Person
}
```

In this case `id` and `input` are the arguments.

**Comment by SebastianStehle** [comment] 2018-06-06 05:06
I have a custom schema for my  JObjects. The schema could say that there is a field with name `benutzer-straße`. The field name is in German and contains the dash and the letter `ß` which should be replaced with `ss`. So to stay in your example it would become this schema.

	input CreateInput {
	  benutzerStrasse: String
	}

	type Query {
	  person(id: String): Person
	  createPerson(input:CreateInput): Person
	}

In my queries this mapping is easy to do with the resolvers, I can just change the field name with `key.ToCamelCase().Replace(...)` and it works fine. But for mutation I can not make this (reverse) mapping very easily. Because graphql-dotnet always uses the field Name to add the values to the dictionary. Of course I can process the input object in the mutation but I think it should be the responsibility of the input scheme to make this mapping.

**Comment by joemcbride** [comment] 2018-06-06 05:27
So are you trying to go from the `benutzerStrasse` input field back to `benutzer-straße` in a mutation?

**Comment by SebastianStehle** [comment] 2018-06-06 05:31
Yes

**Comment by joemcbride** [comment] 2018-06-06 05:57
👍 My first recommendation would be to write a small object model around that `JObject`.  Then it could handle that mapping fairly easily for you.

```csharp
public class Benutzer
{
    public Benutzer(JObject json)
    {
        Json = json;
    }

    public string BenutzerStrasse
    {
        get => Json.TryGetString("benutzer-straße");
        set => Json.SetString("benutzer-straße", value);
    }

    public JObject Json { get; }
}

public static class JObjectExtensions
{
    public static JToken TryGetValue(this JObject json, string name)
    {
        if (json != null && json.TryGetValue(name, StringComparison.OrdinalIgnoreCase, out JToken value))
        {
            return value;
        }

        return null;
    }

    public static string TryGetString(this JObject json, string name)
    {
        JToken value = json.TryGetValue(name);
        return value?.ToString();
    }

    public static void SetString(this JObject json, string name, string value)
    {
        json[name] = value;
    }
}
```

If it needs to be more dynamic than that, you could perhaps add the mapping as `Metadata` on the `GraphType` or the `FieldType`.

```csharp
var field = new FieldType
{
    Name = key.ToCamelCase(),
    Resolver = resolver,
    ResolvedType = fieldInfo.ResolveType,
};
field.Metadata["mappedName"] = key;
```

The `FieldType` can be accessed in the resolver with `context => context.FieldDefinition.Metadata["mappedName"]`.

**Comment by SebastianStehle** [comment] 2018-06-06 06:06
The schema is not known at build time. Therefore I use the JObject for my data. The metadata approach is probably the same idea like my approach: To process the input Dictionary in my mutation-resolver.  You can use the metadata for that but I also have my custom schema, which I can use. But I think there should be a something like a reverse-resolver for input types.

**Comment by saborrie** [comment] 2018-08-15 22:01
+1 for the reverse resolver

**Comment by joemcbride** [comment] 2018-08-15 22:56
> skip the generation of the IDictionary and create the objects manually or set the properties

There are several things that happen related to the Arguments + Variables to conform to the GraphQL spec and get those specific values to the specified resolver.

I'm not sure I want to try to deal with this with this framework.

That said, if this is really wanted can you provide a proposal on what you would expect that API to look like and how it would behave?

**Comment by saborrie** [comment] 2018-08-16 13:00
Maybe there's already a way to do this nicely, but essentially it would be good to define how input types deserialise into the models that they are for. For example, it would be nice to have a way of replacing this:

```
    public class MyInputType: InputObjectGraphType<MyInputModel>
    {
        public MyInputType()
        {
            Field(_ => _.Payload);
        }
    }

    public class MyInputModel
    {
        public string Payload { get; set; } // actually just a JSON serialised payload
    }
```

With this:
```
    public class MyInputType: InputObjectGraphType<MyInputModel>
    {
        public MyInputType()
        {
            // something along these lines:
            Field(_ => _.Payload).Deserialize(_ => JsonConvert.DeserializeObject<dynamic>(_));
        }
    }

    public class MyInputModel
    {
        public dynamic Payload { get; set; } // the deserialised payload object
    }
```

**Comment by AmbroiseCouissin** [comment] 2018-10-23 04:00
Would love this as well. This would clean a lot of our DTOs.

**Comment by sungam3r** [comment] 2020-02-27 16:25
> Since I'd never actually want to "resolve" a field on an input type, I'm not sure why it has Resolve methods

It is a design flaw.

**Comment by sungam3r** [comment] 2020-02-27 16:29
Relates to #1107

**Comment by sungam3r** [comment] 2020-02-27 16:34
@saborrie I understand your idea. API will look different, but the functional purpose will be just that.

**Comment by sungam3r** [comment] 2020-02-27 20:09
Well, I think this issue will be resolved after merging #1577 . You can register any conversion delegate through `ValueConverter.Register` and it will be called from `context.GetArgument<YourDTO>`. Note that this applies to any nesting level of properties in the input argument, not root only.

**Comment by sungam3r** [comment] 2020-02-27 20:11
I was wrong, changes are required for the complex type.

**Comment by sungam3r** [comment] 2020-02-29 17:38
Duplicate of #669

**Closed** 2020-03-01 22:21 UTC
Labels: question

**Comment by sungam3r** [comment] 2020-03-01 22:24
@SebastianStehle Done in #1582 . You can try the latest preview.
