### ISSUE TITLE
AspNetSynchronizationContext is not persisted when requesting multiple queries/mutations

### ISSUE THREAD

**Issue by vitaliitylyk** [graphql-dotnet/graphql-dotnet#1021] opened 2019-02-22 10:48 UTC
## Description

The issue is happening with async queries/mutations. In case you use multiple queries/mutations in the same GraphQL request, the first executed query/mutation would have `AspNetSynchronizationContext `(meaning `HttpConext.Current` is available, etc), while other queries mutations will not have the synchronization context set.

### Steps to reproduce

1) Define multiple **async** queries or mutations, which access `HttpContext.Current`
2) Issue a GraphQL request with multiple queries/mutations, e.g:

```
query {
  authors {
    getAuthors(){ id }
  }

  books {
    getBooks(){ id }
  }
}
```

**Note:** the issue is only happening when queries are placed on different "levels". Meaning, in the following case issue is not reproducible:

```
query {
 getAuthors(){ id }
 getBooks(){ id }
}
```

**However**, with mutations, the issue is reproducible even when they are placed on the same level.

### Expected result

Both queries have access to `HttpContext.Current` and `SynchronizationContext.Current` is set to `AspNetSynchronizationContext`.

### Actual result

In second query (and subsequent one, if there are more) `HttpContext.Current` and `SynchronizationContext.Current` are null.

### The cause

The cause of the issue lies in the internals of the `ParallelExecutionStrategy `and `SerialExecutionStrategy`.   The code inside these classes uses `ConfigureAwait(false)` in between executing queries/mutations, e.g:

```
 await OnBeforeExecutionStepAwaitedAsync(context)
                    .ConfigureAwait(false);

 await task.ConfigureAwait(false);
```

While this is a good practice in some cases, in this particular case the `ConfigureAwait(false)` should not be used to make sure all parallel queries/mutations have access to HttpContext and synhronization context is captured.

So the fix would be to remove `ConfigureAwait(false)` calls from these 2 classes. I have tried this change in my project, so can confirm that this fixes the issue. Alternatively, you can make this behavior configurable so that developers could choose whether they need to persist synchronization context or not.

If you agree to one of these solutions, I can make a PR ;)

**Comment by SimonCropp** [comment] 2019-03-02 07:23
Would it be better to pass the current httpcontext in to the graphql context when u initially execute the query? Then it will be accessible from all query/mutation parts

**Comment by vitaliitylyk** [comment] 2019-03-04 10:48
It could be a solution, but it won't cover the case when `HttpContext.Current` (and potentially other stuff flowing in `SynchronizationContext`) is used within some libraries/services, which are called from queries/mutations. Also, in ASP.NET core scenario I assume developers would use `IHttpContextAccessor`, so probably passing `HttpContext `within graphql context would not be very useful for that scenario as well.

**Comment by SimonCropp** [comment] 2019-03-04 11:16
@vitaliitylyk does placing resolving IHttpContextAccessor from the container not work in graphql?

**Comment by SimonCropp** [comment] 2019-03-04 11:18
@vitaliitylyk  i much prefer to flow the state https://www.planetgeek.ch/2016/04/26/avoid-threadstatic-threadlocal-and-asynclocal-float-the-state-instead/ rather than relying on ThreadStatic, ThreadLocal or AsyncLocal

**Comment by vitaliitylyk** [comment] 2019-03-04 11:37
I am not using ASP.NET Core on my project (not yet unfortunately ;) ), but I assume injecting `IHttpContextAccessor` would work just fine with GraphQL. But for now I have to deal with `HttpContext.Current`.

> i much prefer to flow the state

Yes indeed, flowing the state is a better solution and more future proof. Unfortunately for legacy ASP.NET it will not always be possible since you don't have control over all code where `HttpContext.Current` is used (e.g some external libraries).

So maybe if you're focusing more on .NET Core it makes sense to not change anything. In this case it might be nice to mention this behavior in the documentation?

What I did for now in my project is implemented custom `ParallelExecutionStrategy` and `SerialExecutionStrategy` classes by removing `ConfigureAwait` calls, which works fine for me.

**Comment by sungam3r** [comment] 2019-10-12 20:59
First of all this is (`ConfigureAwait(false)` usage) the intended behaviour.

> It could be a solution, but it won't cover the case when `HttpContext.Current` (and potentially other stuff flowing in SynchronizationContext) is used within some libraries/services, which are called from queries/mutations.

It is bad design for libraries to rely on `HttpContext` things. This is a tight binding to a specific transport. Also there is no `SynchronizationContext` in ASP.NET Core apps - https://blog.stephencleary.com/2017/03/aspnetcore-synchronization-context.html 

> Unfortunately for legacy ASP.NET it will not always be possible since you don't have control over all code where HttpContext.Current is used (e.g some external libraries).

Yes. Indeed there **may** be problems for some **REALLY old** legacy libraries. But in the general case, the problem of http state transfer can be solved. However the semantics of http transport should remain at the top level of the application (ASP things: controllers, filters, routing, middlewares, etc.) and not leak into the underlying layers.

> Alternatively, you can make this behavior configurable so that developers could choose whether they need to persist synchronization context or not.

Well, it **can be** actually done, but this will be of little value, especially in comparison with what it will take to do. We need to consider/apply this mode switch of `ConfigureAwait` in all places all over the codebase, not just in the one you specify. It will litter the code. Also keep in mind that this is all being done as a solution to **potential** problems for very old projects.

You can do something like your own `IHttpContextAccessor`. There is nothing complicated, just look at the .NET Core implementation.

@vitaliitylyk I think we can close this issue. If you still have questions, then I will be happy to answer them.

**Closed by sungam3r** 2019-10-12 20:59 UTC
Labels: wontfix
