### ISSUE TITLE
Input 

### ISSUE THREAD

**Issue by baluubas** [graphql-dotnet/graphql-dotnet#118] opened 2016-07-15 16:09 UTC
I'm having some trouble with input variables that can be null and InputGraphObject. I have a mutation similar to this:

```
new QueryArguments(new[] {
      new QueryArgument<MyInput> { Name = "input" }
}) 

...

public class MyInput : InputObjectGraphType
{
	public MyInput()
	{
		Name = "MyInput ";
		Field<NonNullGraphType<StringGraphType>>("id");
		Field<StringGraphType>("foo");
		Field<StringGraphType>("bar");
	}
}
```

If I pass a null value for foo or bar I get: 
`Variable '$input_0' expected value of type 'MyInput'`

From what I can tell from the source code, this doesn't seem to be supported. I'm I thinking all wrong here or is this something that should be possible?

**Comment by joemcbride** [comment] 2016-07-15 16:19
This should be supported - can you also post the GraphQL mutation you are using?  The query language portion of it.

**Comment by baluubas** [comment] 2016-07-15 16:24
From the schema?

**Comment by joemcbride** [comment] 2016-07-15 16:26
The actual GraphQL mutation text that is being sent from the application to the server.

ex:

```
mutation M {
  first: immediatelyChangeTheNumber(newNumber: 1) {
    theNumber
  }
}
```

**Comment by baluubas** [comment] 2016-07-15 16:41
Ok, this the actual code I'm using and not the example code (react-relay is building these). The structure is the same though.

```
mutation UpdateOrganizationWebPresenceMutation($input_0:UpdateOrganizationWebPresenceInput!) {
     updateOrganizationWebPresence(input:$input_0) {
          clientMutationId,
          ...F1  
     }
}

fragment F0 on Organization {
  id,
  webPresence {
    website,
    careerPage, 
    facebook,
    instagram,
    twitter
  }
}

fragment F1 on UpdateOrganizationPayload {
  organization {
    ...F0  
  }
}

```

And variables:

```
{
  "input_0":{
    "id":"15a29266-fb7e-4c85-a8c0-3190e017e893",
    "__dataID__":"client:-18344258881",
    "website":"google.com",
    "careerPage":"google.com",
    "facebook":"adf",
    "instagram":null,
    "twitter":"asdf",
    "clientMutationId":"0"
  }
}
```

Note, the `instagram` null value which is causing the error..

**Comment by joemcbride** [comment] 2016-07-15 16:49
Thanks, you may have indeed found a bug.  I believe I've been able to duplicate this, will see if it is a quick fix.

**Comment by joemcbride** [comment] 2016-07-15 17:21
I don't see a quick fix, though I do believe I see what is happening.  I'll post here once I find a fix.  No ETA for when that will be.

**Comment by baluubas** [comment] 2016-07-15 18:30
Cool, thanks for the help.

**Comment by joemcbride** [comment] 2016-07-22 01:41
@baluubas I just realized what the issue is.

```
Name = "MyInput ";
```

The name is defined with a space in it.  If you remove that space, it should be fixed.  I'll see if I can make sure to fix that, though that is probably your issue.

**Comment by joemcbride** [comment] 2016-07-22 03:50
This should be fixed with https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.10.0.325

**Comment by baluubas** [comment] 2016-07-22 07:07
That was just a contrived example. The actual name of the input doesn't have space. 

I'll try and see if I can't make a failing test.

**Comment by joemcbride** [comment] 2016-07-22 07:23
Here is the test I wrote to try to try to reproduce: https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Bugs/Bug118SpacesInTypeNameTests.cs

**Comment by baluubas** [comment] 2016-07-22 08:04
Ok here is a runnable example that fails due to input variable "foo" being null

```
using GraphQL;
using GraphQL.Types;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GraphQL_NET_Null_Property
{
	public class MyQuery : ObjectGraphType
	{
		public MyQuery()
		{
			Name = "Root";
		}

	}
	public class MySchema : Schema
	{
		public MySchema()
		{
			Query = new MyQuery();
			Mutation = new MyMutation();
		}
	}

	public class MyInput : InputObjectGraphType
	{
		public MyInput()
		{
			Field<StringGraphType>("foo");
		}
	}

	public class MyMutation : ObjectGraphType
	{
		public MyMutation()
		{
			Field<AMutionPayload>(
				"a_mution",
				arguments: new QueryArguments(new[] {
					new QueryArgument<MyInput> { Name = "input" }
				}),
				resolve: ctx => new { bar = "Hello world" }
			);
		}
	}

	public class AMutionPayload : ObjectGraphType
	{
		public AMutionPayload()
		{
			Name = "AMutionPayload";
			Field<StringGraphType>("bar");
		}
	}


	class Program
	{
		static void Main(string[] args)
		{
			Task.Run(Execute).Wait();
			Console.ReadKey();
		}

		private static async Task Execute()
		{

			var query = @"
				mutation MyMutationReference($input_0:MyInput!) {
					a_mution(input:$input_0) {
						bar
					}
				}";


			var executer = new DocumentExecuter();
			var schema = new MySchema();
			var inputs = new Inputs(
				new Dictionary<string, object>{
					{ "input_0", new Dictionary<string, object> { {  "foo", null } } }
			});

			try
			{
				var result = await executer.ExecuteAsync(schema, null, query, null, inputs);

				if (result.Errors != null)
				{
					Console.WriteLine("Execution error from ExecuteAsync");
					foreach (var error in result.Errors)
					{
						Console.WriteLine(error.Message);
					}
					Console.WriteLine("Execution error from ExecuteAsync");
				}
				else
				{
					Console.WriteLine("Success");
				}
			}
			catch (Exception e)
			{
				Console.WriteLine("Runtime exception from ExecuteAsync");
				Console.WriteLine(e.ToString());
			} 
		}
	}
}

```

**Comment by tlil87** [comment] 2016-07-22 08:28
Does it work if you change `$input_0:MyInput!` to `$input_0:MyInput`?

**Comment by baluubas** [comment] 2016-07-22 08:34
Yes it does :) 

I still get the error if I change the input parameter to 
`new QueryArgument<NonNullGraphType<MyInput>> { Name = "input" }`

**Comment by joemcbride** [comment] 2016-07-22 15:41
`$input_0:MyInput!` is the culprit.  There may be some bad logic there.  Relay likes to add `!` everywhere, though seems like that should still be valid in this case.

**Comment by joemcbride** [comment] 2016-07-22 18:46
I believe I squashed this.  Can you give v0.10.0.332 nuget a try?

Download direct here:
https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/0.10.0.332/artifacts

Download via nuget feed:
https://ci.appveyor.com/nuget/graphql-dotnet

**Comment by baluubas** [comment] 2016-07-24 09:10
Yes, that did the trick. Good work!

**Closed** 2016-07-24 15:16 UTC
Labels: bug
