### ISSUE TITLE
Unable to break down query as per documentation

### ISSUE THREAD

**Issue by denis-troller** [graphql-dotnet/graphql-dotnet#2033] opened 2020-12-03 16:19 UTC
## Summary
I am trying to introduce a level in my root query to group queries per domains, as per [the documentation](https://graphql-dotnet.github.io/docs/getting-started/query-organization). 
However, my query types require some services injected in their constructor.
I get a `System.Exception: Failed to call Activator.CreateInstance.` when attempting to get the docs.

## Relevant information
Here is my root Query and "sub-query" iobjects. They are both registered in the DI system (.net Core):
```
    public class Queries : ObjectGraphType<object>
    { 
        public Queries(IServiceProvider provider)
        {
            Name = "Query";
            

            Field<Alarms.AlarmsQueries>(
                "Alarms",
                resolve: context => provider.GetService(typeof(Alarms.AlarmsQueries)));
        }

    }
```
```
namespace Alarms 
{
    public class AlarmsQueries : ObjectGraphType<object>
    {
        public AlarmsQueries(IAlarmsService svc)
        {
            Name = "Alarms";
            this.svc = svc;

            Field<ListGraphType<PendingAlarmType>>(
                "PendingAlarms",
                resolve: context => svc.GetPendingAlarms());
        }

        private IAlarmsService svc;
    }
}
```
Here is the full stacktrace of the exception:
```
System.Exception: Failed to call Activator.CreateInstance. Type: InNova.API.GraphQL.Alarms.AlarmsQueries
 System.MissingMethodException: No parameterless constructor defined for type InNova.API.GraphQL.Alarms.AlarmsQueries.
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at GraphQL.DefaultServiceProvider.GetService(Type serviceType) in /_/src/GraphQL/DI/DefaultServiceProvider.cs:line 23
   --- End of inner exception stack trace ---
at GraphQL.DefaultServiceProvider.GetService(Type serviceType) in /_/src/GraphQL/DI/DefaultServiceProvider.cs:line 27
at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 38
at GraphQL.Types.Schema.\u003CCreateTypesLookup\u003Eb__68_1(Type type) in /_/src/GraphQL/Types/Schema.cs:line 314
at GraphQL.Types.GraphTypesLookup.\u003C\u003Ec__DisplayClass11_0.\u003CCreate\u003Eb__0(Type t) in /_/src/GraphQL/Types/GraphTypesLookup.cs:line 116
at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in /_/src/GraphQL/Types/GraphTypesLookup.cs:line 442
at GraphQL.Types.GraphTypesLookup.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in /_/src/GraphQL/Types/GraphTypesLookup.cs:line 365
at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/GraphTypesLookup.cs:line 281
at GraphQL.Types.GraphTypesLookup.Create(IEnumerable\u00601 types, IEnumerable\u00601 directives, Func\u00602 resolveType, INameConverter nameConverter, Boolean seal) in /_/src/GraphQL/Types/GraphTypesLookup.cs:line 126
at GraphQL.Types.Schema.CreateTypesLookup() in /_/src/GraphQL/Types/Schema.cs:line 311
at System.Lazy\u00601.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy\u00601.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy\u00601.CreateValue()\r\n   at System.Lazy\u00601.get_Value()
at GraphQL.Types.Schema.get_AllTypes() in /_/src/GraphQL/Types/Schema.cs:line 127
at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema) in /_/src/GraphQL/Instrumentation/FieldMiddlewareBuilder.cs:line 71
at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 74
--- End of inner exception stack trace ---
```

I get the same error if I do a direct injection of AlarmQueries in the Queries constructor, as I believe the problem originate when calling the `Field<AlarmQueries>()` method, where the system seems to attempt to create the type directly through Activator.Createinstance.

It actually works if, instead of using DI I remove the dependency on my service and access it through Context.RequestServices, but It seems to me it should work.
Please note all my types are registered Scoped (schema, Queries, AlarmQueries) or Singleton (IAlarmService)

### Environment (if relevant)
.Net 5 Web application
GraphQL 3..1.6

**Comment by Shane32** [comment] 2020-12-03 16:26
Change `public Queries(IServiceProvider provider)` to `public Queries(IServiceProvider provider) : base(provider)`

**Comment by Shane32** [comment] 2020-12-03 16:27
Sorry, no, you need to do that for the `Schema`, not the query type.  The schema's constructor needs to pass the service provider back to its base.  The problem is that GraphQL.Net is using its built-in simplistic DI system instead of your DI system.

**Comment by Shane32** [comment] 2020-12-03 16:28
Here's the sample of `StarWarsSchema` from the samples included in the project:
```cs
    public class StarWarsSchema : Schema
    {
        public StarWarsSchema(IServiceProvider serviceProvider)
            : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<StarWarsQuery>();
            Mutation = serviceProvider.GetRequiredService<StarWarsMutation>();

            Description = "Example StarWars universe schema";
        }
    }
}
```

**Comment by Shane32** [comment] 2020-12-03 16:39
Also, the resolve parameter should return an object to be used as the `Source` for the descendant graph type.  You also do not need to pass in an instance of the graph type itself.  So this code here:
```cs
resolve: context => provider.GetService(typeof(Alarms.AlarmsQueries)));
```
could be something like this:
```cs
resolve: context => new object();
```
But you will still get the same error with GraphQL.Net failing to resolve `Alarms.AlarmsQueries` until you fix the schema constructor.

Finally, I recommend that you register all your graph types as singletons.  If you need to register `IAlarmsService` as scoped or transient (which it appears you do not), then eliminate `IAlarmsService` from the constructor and change this:
```cs
resolve: context => svc.GetPendingAlarms());
```
to this:
```cs
resolve: context => context.RequestServices.GetRequiredService<IAlarmsService>().GetPendingAlarms());
```
Then it will only create `IAlarmsService` when `PendingAlarms` is requested, and within the correct scope.

**Comment by denis-troller** [comment] 2020-12-03 21:45
Yes, thank you very much for your answer.
I ended up going the way of RequestServices, as this is what te documentation indicates as best practice performance-wise.

now my problem is, in my subscription, I tried using RequestServices as well but it is null, whereas in my Query it is not. 
Any idea why ?

**Comment by sungam3r** [comment] 2020-12-03 23:17
Please provide your example for subscription.

**Comment by Shane32** [comment] 2020-12-04 00:33
I’m sorry; I have yet to use subscriptions, so I can’t answer.

**Comment by AntonioFalcao** [comment] 2020-12-04 03:05
> Yes, thank you very much for your answer.
> I ended up going the way of RequestServices, as this is what te documentation indicates as best practice performance-wise.
> 
> now my problem is, in my subscription, I tried using RequestServices as well but it is null, whereas in my Query it is not.
> Any idea why ?

The `ExecuteAsync` on `SubscriptionManager` is not propagating `RequestServices` (IServiceProvider), but will only affect it if you have a custom `Executer` overriding `ExecuteAsync` and are using `RequestServices` on it.

```c#
public class SubscriptionManager : ISubscriptionManager
{
    ...

    private async Task<Subscription> ExecuteAsync(
        string id,
        OperationMessagePayload payload,
        MessageHandlingContext context)
    {
        ...

        var result = await _executer.ExecuteAsync(
            payload.OperationName,
            payload.Query,
            payload.Variables?.ToInputs(),
            context,
            null // TODO: find later a better way to specify services
        ).ConfigureAwait(false);

        ...
    }

    ...
}

```

About your `Subscriber` or `AsyncSubscriber` in `AddField` the `EventStreamResolver<T>` will provides the `RequestServices` after her construction. If you try to use it on the delegate, you will see that the property will not be available yet.

You can receive IServiceProvider on your Subscription constructor and resolve the dependency in this way. Even resolve a scoped dependency on a singleton subscription.

```c#
public ChatSubscriptions(IServiceProvider serviceProvider)
{
    AddField(new EventStreamFieldType
    {
        Name = "messageAdded",
        Type = typeof(MessageType),
        Resolver = new FuncFieldResolver<Message>(fieldContext
            => fieldContext.Source as ReviewMessage),
        AsyncSubscriber = new AsyncEventStreamResolver<Message>(streamContext
            => serviceProvider
                .GetRequiredService<IChat>()
                .MessagesAsync()),
    });
}
```

**Comment by denis-troller** [comment] 2020-12-04 08:55
@AntonioFalcao Thanks for this
So I gather that, provided I get the IServicePRovider in my Shcema class and call base(provider) as explained by @shane32, it should all work ?
How can an IServiceProvider injected on construction on a singleton object (the Schema and derived types) resolve scoped services ?

My second problem when I do that is that I get an error about an enumeration.
I have an enum in my system, returned by one of my propreties. Until now it seems graphql was happy auto-generating the proper graph type. As soon as I require IServiceProovider and pass it to the base constructor of Shema, I get  this:

```
GraphQL.Execution.UnhandledError: Error executing document.
 ---> System.InvalidOperationException: Required service for type GraphQL.Types.EnumerationGraphType`1[Alarms.AlarmLevelConstants] not found
```

I tried to add this:
```
public class AlarmLevelType : EnumerationGraphType<AlarmLevelConstants>
    {

    }
```
but it still gives the error...

**Comment by Shane32** [comment] 2020-12-04 09:01
You need to register AlarmLevelType in your DI container as a singleton

**Comment by denis-troller** [comment] 2020-12-04 09:17
Oups, my bad. 
Since type registration in the DI does not seem mandatory for first level types, I did not do that...
Thank you !

Any explanation on the Scoped vs Singleton problem ?
I changed my schema object to be singleton, as per @Shane32's suggestion.
If I do that, however, all my types become de facto singletons.
So how can an ÌServiceProvider` injected as a singleton serve scoped services ?

I do not understand why RequestServices is provided automatically in a Query, but not in a Subscription...
Is there a difference ? And if I really need this, I am not sure I understand your previous comment on SubscriptionManager.
Do I need to register my own SubscriptionManager in the DI container ? 

I had this:
```
public class Subscriptions : ObjectGraphType<object>
    {
        public Subscriptions(IServiceProvider serviceProvider)
        {
            Name = "Subscription";

            this.provider = serviceProvider;
            
            AddField(new EventStreamFieldType
            {
                Name = "PendingAlarmEvent",
                Type = typeof(PendingAlarmType),
                Resolver = new FuncFieldResolver<PendingAlarm>(ResolveAlarm),
                Subscriber = new EventStreamResolver<PendingAlarm>(Subscribe)
            });
        }

        private IServiceProvider provider;

        private PendingAlarm ResolveAlarm(IResolveFieldContext context) 
        {
            var pendingAlarm = context.Source as PendingAlarm;
            return pendingAlarm;
        }

        private IObservable<PendingAlarm> Subscribe(IResolveEventStreamContext context)
        {
            var svc = context.RequestServices.GetRequiredService<Alarms.IAlarmsService>();
            return svc.GetPendingAlarmEventStream();
        }
    }
```

**Comment by denis-troller** [comment] 2020-12-04 10:17
Nevermind, I guess I understand where the problem lies.
 And, I guess since my subscription is long-lived, it makes sense to only access singleton services in it.
I just need to refactor my quickly thrown together attempt to separate Scoped (query) and long-lived (subscriptions)
Thanks @Shane32 and  @AntonioFalcao for your help !

**Comment by AntonioFalcao** [comment] 2020-12-04 14:09
> Nevermind, I guess I understand where the problem lies.
> And, I guess since my subscription is long-lived, it makes sense to only access singleton services in it.
> I just need to refactor my quickly thrown together attempt to separate Scoped (query) and long-lived (subscriptions)
> Thanks @Shane32 and @AntonioFalcao for your help !

Take a look at this topic, and also on the project, i think it will give you some insights about your questions:
https://github.com/AntonioFalcao/Dotnet5.GraphQL3.WebApplication#resolving-scoped-dependencies-with-singleton-schema

**Comment by Shane32** [comment] 2020-12-04 15:48
No problem @denis-troller !  If you're all set, please close this issue.

**Closed** 2020-12-07 09:38 UTC
Labels: question
