### ISSUE TITLE
Nullable Int32 Convert issue.

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [graphql-dotnet/graphql-dotnet#1940] opened 2020-10-23 16:23 UTC
When I try to load a nullable field that is in fact null - I get:

"Input string was not in a correct format."
```
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)\r\n   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)\r\n   at GraphQL.ValueConverter.<>c.<.cctor>b__1_4(String value) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Conversion\\ValueConverter.cs:line 32\r\n   at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Conversion\\ValueConverter.cs:line 207\r\n 
......

```

I'm making the field like:

```
....
Type tEffective = typeof(Int32?);
tEffective = Nullable.GetUnderlyingType(tEffective);
tGraphType = tEffective.GetGraphTypeFromType(true);
Field(tGraphType, "foofield");
....

```
Is there a different syntax I should be using?

**Comment by sungam3r** [comment] 2020-10-23 17:53
It seems that your value is not null but some string value because aforementioned conversion hits only in such a case. Could you provide a minimum repro?

**Comment by OpenSpacesAndPlaces** [comment] 2020-10-23 18:34
```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using GraphQL.Resolvers;
using GraphQL.Types;
using Shouldly;
using Xunit;

namespace GraphQL.Tests.Bugs
{
    public class Bug1940 : QueryTestBase<Bug1940Schema>
    {
        [Fact]
        public async Task should_not_throw_error()
        {
            Bug1940Schema s =  new Bug1940Schema();
            s.Initialize();

            var de = new DocumentExecuter();
            var valid = await de.ExecuteAsync(new ExecutionOptions
            {
                Query = "query  { foo_list { id } }", Schema = s, OperationName = null,
                ThrowOnUnhandledException = true
            });


            string sErrors = string.Join(",", valid.Errors.Select(p => p.Message));

            if (!string.IsNullOrEmpty(sErrors))
            {
                throw new Exception(sErrors);
            }
            else
            {
                try
                {
                    valid.Data.ShouldNotBeNull();

                    dynamic o = valid.Data;

                    throw new Exception(o.error);
                }
                catch (Exception e)
                {
                    //TODO
                }
            }

            return;
        }
    }

    public sealed class Table1940 : ObjectGraphType<object>
    {
        public Table1940()
        {
            Name = "Table";

            FieldType nameField = Field(typeof(StringGraphType), "Name");
            nameField.Resolver = new QueryNameFieldResolver1940();

            Type tEffective = typeof(int?);
            tEffective = Nullable.GetUnderlyingType(tEffective);
            Type tGraphType = tEffective.GetGraphTypeFromType(true);
            FieldType idField = Field(tGraphType, "Id");
            idField.Resolver = new QueryNameFieldResolver1940();
        }
    }

    public class QueryNameFieldResolver1940 : IFieldResolver
    {
        public object Resolve(IResolveFieldContext context)
        {
            var source = context.Source;

            if (source == null)
            {
                return null;
            }

            Type t = source.GetType();
            bool bIsDictionary = source is IDictionary &&
                                 t.IsGenericType &&
                                 t.GetGenericTypeDefinition().IsAssignableFrom(typeof(Dictionary<,>));
            var name = char.ToUpperInvariant(context.FieldAst.Name[0]) + context.FieldAst.Name.Substring(1);
            var value = bIsDictionary
                ? GetDictionaryPropValue((IDictionary)source, name)
                : GetObjectPropValue(t, source, name);

            value = value != null ? value : string.Empty;

            return value;
        }

        private static object GetObjectPropValue(Type t, object src, string propName)
        {
            PropertyInfo pi = t.GetProperty(propName, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);
            return pi?.GetValue(src);
        }

        private static object GetDictionaryPropValue(IDictionary src, string propName)
        {
            return src.Contains(propName) ? src[propName] : null;
        }
        
    }

    public sealed class FakeClass1940
    {
        public string Name { get; set; }
        public int? Id { get; set; }
    }

    public sealed class QueryFieldResolver1940 : IFieldResolver
    {
        public object Resolve(IResolveFieldContext rfc)
        {
            if (rfc.FieldName.Contains("_list"))
            {
                return (object)new List<FakeClass1940>()
                {
                    new FakeClass1940()
                    {
                        Name = "List",
                        Id = null
                    }
                };
            }
            else
            {
                return (dynamic)new FakeClass1940()
                {
                    Name = "Object",
                    Id = null
                };
            }
        }
    }

    public sealed class QueryType1940 : ObjectGraphType<object>
    {
        public QueryType1940()
        {
            QueryFieldResolver1940 fieldResolver = new QueryFieldResolver1940();
            Table1940 tableType = new Table1940();
            AddField(new FieldType
            {
                Name = "foo", 
                Type = tableType.GetType(), 
                ResolvedType = tableType,
                Resolver = fieldResolver
            });

            //Definition of List Query/Return Type
            ListGraphType listType = new ListGraphType<Table1940>() { ResolvedType = tableType };//new ListGraphType(qttGraphType); //Alternate Syntax per https://github.com/graphql-dotnet/graphql-dotnet/issues/1927 
            AddField(new FieldType
            {
                Name = $"foo_list", 
                Type = listType.GetType(),
                ResolvedType = listType, 
                Resolver = fieldResolver
            });
        }
    }

    public class Bug1940Schema : Schema
    {
        public Bug1940Schema()
        {
            Query = new QueryType1940();
        }
    }
}

```

**Comment by OpenSpacesAndPlaces** [comment] 2020-10-23 18:35
GraphQL.Tests.Bugs.Bug1940.should_not_throw_error
   Source: Bug1940.cs line 17
   Duration: 121 ms

  Message: 
    System.FormatException : Input string was not in a correct format.
  Stack Trace: 
    Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
    Int32.Parse(String s, IFormatProvider provider)
    <.cctor>b__1_4(String value) line 32
    <>c__DisplayClass7_0`2.<Register>b__0(Object v) line 207
    ValueConverter.TryConvertTo(Object value, Type targetType, Object& result, Type sourceType) line 166
    ValueConverter.ConvertTo(Object value, Type targetType) line 144
    IntGraphType.ParseValue(Object value) line 21
    ScalarGraphType.Serialize(Object value) line 28
    ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) line 266
    ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node) line 189
    ParallelExecutionStrategy.ExecuteNodeTreeAsync(ExecutionContext context, ExecutionNode rootNode) line 34
    ExecutionStrategy.ExecuteAsync(ExecutionContext context) line 21
    DocumentExecuter.ExecuteAsync(ExecutionOptions options) line 223
    Bug1940.should_not_throw_error() line 23
    --- End of stack trace from previous location where exception was thrown ---

**Comment by Shane32** [comment] 2020-10-23 22:00
You've set `Id = null` for the source, but then in the field resolver you return an empty string instead of the `null` here:

```cs
value = value != null ? value : string.Empty;
```

Because you've defined `idField` as a nullable `IntGraphType`, the library tries to coerce the empty string to an integer, which fails and throws an exception.

If this code worked previously, it may be due to the changes in #1701 .  Additional changes were made in #1773 .  Also see #1699 .  This behavior is by design.

**Comment by sungam3r** [comment] 2020-10-23 22:05
> "Input string was not in a correct format."

I wonder if we should make the error message more verbose?

**Comment by Shane32** [comment] 2020-10-23 22:12
I wouldn't change it.  `int.Parse` is throwing the exception, and that's the .Net standard error message for that type of problem.  It seems pretty clear to me.  It properly gets encapsulated with a "Error trying to resolve field 'id'." message, with the inner exception set to the underlying exception, path and location properties.

**Comment by sungam3r** [comment] 2020-10-23 22:46
OK. Closing.

**Closed by sungam3r** 2020-10-23 22:46 UTC
Labels: question

**Comment by OpenSpacesAndPlaces** [comment] 2020-10-24 00:58
Thanks for the help. It did work before - it's likely I did it to overcome some issue (though I neglected to comment as to what).
Working great now!

Thanks again to both of you for helping me through the oddball items here!
