### ISSUE TITLE
UTC Dates in inputs are serialized with wrong "Kind"

### ISSUE THREAD

**Issue by lngr** [graphql-dotnet/graphql-dotnet#197] opened 2016-10-21 14:20 UTC
In a recent commit (32a4a3dad7322c), the method `ObjectExtensions.ConvertValue()` was changed such that the input `value` is converted to a `string` representation via `.ToString()` and then converted back to the target type.

This breaks inputs with JSON date strings such as "2016-10-21T13:32:15.753Z", whereas it worked with previous versions of GraphQL.NET (e.g. 0.11.0).

The reason is that the conversion to string is lossy.  In particular, if a `DateTime` object is converted to `string` via `ToString()` and parsed afterwards, the `Kind` changes from `DateTimeKind.Utc` to `DateTimeKind.Unspecified` because the timezone information is lost in the string representation.

Thus, `ObjectExtensions. ConvertValue()` gets a `DateTime` with the correct `Kind` as input and outputs a `DateTime` with the wrong kind (in particular, Json.NET does correctly deserialize the date string to a UTC `DateTime`).

The attached PR is a quick fix, but in general I suggest the conversion should be limited to  `IConvertible` types (or similar), since I'm pretty sure other types are affected as well (such as floats with unpredicted locale settings etc). The previous implementation looked more sane to me in this regard but I don't know about .NET Core compatibility.

**Comment by joemcbride** [comment] 2016-10-28 16:49
Thanks for this - yes, the issue is .NET Core compatibility.  I think the fix you have is pretty close to what we want.  I think one step further would be to check if the existing `DateTime` object is UTC and if not to convert it to it instead of just keeping the existing kind.  Can you think of a use case where you wouldn't want it to be UTC?

**Comment by lngr** [comment] 2016-10-28 19:23
Yes, indeed I think it's unsafe to force UTC. In fact we originally transferred all dates in our local timezone (servers and clients are known to be in the same TZ) before we switched to UTC throughout the stack.

Newtonsoft's JSON-converter is actually pretty good at figuring that stuff out, it'll use Unspecified if the "Z" or another time zone identifier is missing and use UTC if "Z" is specified.  And you can already set global config settings that forces UTC serialization in JSON.NET, no need to duplicate that in GraphQL.NET IMO.  I would leave that issue to the JSON converter. :)

**Comment by joemcbride** [comment] 2016-10-28 19:34
I can see wanting to not force to UTC on input like this.  The `DateGraphType` does currently force to UTC on output, though if someone needs different behavior they can create their own custom scalar so I guess that is covered.

**Comment by joemcbride** [comment] 2016-11-16 17:09
Initial fix with https://github.com/graphql-dotnet/graphql-dotnet/pull/198 - I want to look at this closer though.

**Comment by holm0563** [comment] 2017-01-16 21:47
I also have a case where we dont want it converted to UTC. We report dates for another countries with its local time. So say its 1-2-2016 5:00 (EST). Converting it to UTC is based on the server time zone (MST). To make it even worse DateTimeOffsets do not work because we would like this iso format returned to the client "2016-09-19T17:00:00-07:00" instead we would get a zulu time "2016-09-20T00:00:00Z" and now the client cant display the local time value. The hours aren't accurate in my examples but you get the idea. 

Noda time support for c# would help with these issues.

**Comment by joemcbride** [comment] 2017-01-17 16:58
What I'm thinking the best solution would be is to provide hooks so that you guys, or anyone else, could provide the behavior you want for any type.  Couple that with a custom scalar type and you're good to go.

**Comment by holm0563** [comment] 2017-01-17 23:07
This is how we are currently solving the issue:
https://github.com/holm0563/graphql-schemaGenerator/blob/AsReference/src/GraphQl.SchemaGenerator/Types/OriginalDateGraphType.cs
https://github.com/holm0563/graphql-schemaGenerator/blob/AsReference/src/GraphQl.SchemaGenerator.Tests/Tests/DateTests.cs

**Comment by rolfwessels** [comment] 2018-07-28 09:52
@holm0563 thanks for the fix. Works great. 

Is there a way that I can set that as the default type for date time?

They way it is written now:
`Field(d => d.CreateDate,type: typeof(OriginalDateGraphType)).Description("Create date.");`

Preferred:
`Field(d => d.CreateDate).Description("Create date.");`

**Comment by rolfwessels** [comment] 2018-07-31 06:41
Hi,

I'm on the latest version.

```
<PackageReference Include="GraphQL" Version="2.0.0-alpha-952" />
<PackageReference Include="GraphQL.Authorization" Version="1.0.16-alpha-16" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.1.0-alpha0022" />
```

I have a test setup where I pass the same data to WebAPI model and to the GraphQL object. The WebAPI  shows the date "2016-09-17T09:46:37.749+02:00" and graphQL date system shows it as "2016-09-17T09:46:37.749Z".

**Comment by joemcbride** [comment] 2018-07-31 06:48
@rolfwessels Are you able to provide a failing unit test, or push an example project to github that demonstrates the issue?  Also a few questions:

* What `GraphType` are you using?  `DateTimeGraphType` or `DateTimeOffsetGraphType`?
* What value are you sending to the server?
* What culture is the site running under?

**Comment by rolfwessels** [comment] 2018-07-31 06:59
@joemcbride Sure, Let me see what I can do about the sample code. To answer some of the questions

1) I use `Field(d => d.CreateDate).Description("Create date.");` do I believe it uses DateTimeGraphType
2) The data comes from mongo db. I have two interfaces over the same data ( web api and graphql )
3) I have never set any specific culture so it will use my system settings. Which are set to +2h and standard date time format for my current region "south africa"

**Comment by joemcbride** [comment] 2018-07-31 07:14
If the .NET type of `CreateDate` is `DateTime` then it should be using `DateTimeGraphType`.  It should always serialize to UTC so that would be expected.  Of course it shouldn't be dropping the time zone though.  `DateTimeOffsetGraphType` would display the `+02:00` format.

See the examples in #662

**Comment by rolfwessels** [comment] 2018-08-02 12:42
Hi,

So I have gone ahead and created a branch where I remove the OriginalDateTimeType. 

https://github.com/rolfwessels/CoreDocker/tree/bug/date-utc

I have also setup a test to show what is expected.
https://github.com/rolfwessels/CoreDocker/blob/755289dee2cf27f02b5f5cd9f66c06b1aebfcd03/test/CoreDocker.Sdk.Tests/WebApi/UserApiClientTests.cs#L159

Whats a bit strange is that it now seems to use the DateType. Actually the behavior has changed some how. Before I was on the latest alpha version I had the issue where we were 2hours out (based on +2h). No it seems to map my date to a Date without time. clearly I'm doing something wrong with the setup.

Some pointers 
* Sorry but these are integration tests so they currently require a local mongodb connection :-/
* IOC is in  https://github.com/rolfwessels/CoreDocker/blob/bug/date-utc/src/CoreDocker.Api/AppStartup/IocApi.cs#L45
* Specification https://github.com/rolfwessels/CoreDocker/blob/bug/date-utc/src/CoreDocker.Api/Components/Users/UserSpecification.cs#L27


Not sure what else you need. Please let me know if you see something obvious.

**Comment by Shane32** [comment] 2020-08-28 02:28
This issue was opened 4 years ago without any comments in the last 2 years.  I propose we close this issue.

**Comment by sungam3r** [comment] 2020-08-28 07:23
Do we have tests covering the problem?

**Comment by Shane32** [comment] 2020-08-28 15:06
We have tests covering the deserialization to Utc, and other stuff that defines the current behavior pattern.  To make any changes would change the tests (and defined behavior).

**Comment by sungam3r** [comment] 2020-08-28 16:25
Ok, closing.

**Closed** 2020-08-28 18:57 UTC
Labels: needs investigation
