### ISSUE TITLE
Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by jgrandydev** [graphql-dotnet/graphql-dotnet#343] opened 2017-05-31 03:33 UTC
This is for a Windows Service with standard Autofac init sequence that has been working for years in prod.

In dev it continues to work fine with latest code updates.  But on a staging server we now get startup exception.  For testing , all DLLs are copied direct from dev machine to staging server.

```
Windows Server 2012
.NET Framework 4.5.2
```

```
Application: OurApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Autofac.Core.DependencyResolutionException
Stack:
   at Autofac.Core.Resolving.ResolveOperation.Execute(Autofac.Core.IComponentRegistration, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
   at Autofac.ResolutionExtensions.ResolveService(Autofac.IComponentContext, Autofac.Core.Service, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
   at Autofac.ResolutionExtensions.Resolve[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Autofac.IComponentContext, System.Collections.Generic.IEnumerable`1<Autofac.Core.Parameter>)
   at OurApp.Service.Program.Main(System.String[])

```

**Comment by joemcbride** [comment] 2017-05-31 14:59
That stacktrace doesn't show any code from this project.  What makes you think the issue is GraphQL .NET?  Is there a more detailed inner exception?

**Comment by joemcbride** [comment] 2017-07-10 16:13
I'm going to close this issue.  Feel free to re-open if you can provide more information.  Thanks!

**Closed by joemcbride** 2017-07-10 16:13 UTC
