### ISSUE TITLE
How to get RequestServices In Resolver Type of Subscription

### ISSUE THREAD

**Issue by vansangnguyen1998** [graphql-dotnet/graphql-dotnet#3812] opened 2023-12-11 15:18 UTC
## Summary
**I use dotnet 6 and graphql version 7.**
I have implement subscription, query, mutation in my application.
Logic subscription look like image: 
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/44341211/c21276a4-496c-44ed-8948-f26a4d8df2e3)

But with logic response type HRMChangeCandidateResponseType have logic get some property from repository and I have get repository from RequestServices .
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/44341211/b5efc0c8-b30b-422b-8b11-b649613720d8)
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/44341211/cf527da4-ebe4-46e0-ad47-692bface26bf)

But when I debug subscription response type in line **x.GetServiceRegister<Type>();** will be exception, because IServiceProvider is disposed.

Can you help me, to can get other service from subscription.

**Comment by Shane32** [comment] 2023-12-11 16:35
The `IObservable` returned from the `Subscribe` method must originate from a singleton service (or otherwise be application-scoped), as the service provider within the `IResolveFieldContext` will be disposed once the method completes.  This is by design.  However, you can configure GraphQL to create a scoped service while resolving data events.  This should fix your issue.  To do so, configure the schema in your DI config with:
```cs
.AddScopedSubscriptionExecutionStrategy(/* true for serial execution, false for parallel execution */)
```

Once done, you can pull services just as you would for any other part of your GraphQL schema, as follows:

For serial execution, pull services from `IResolveFieldContext` like this:

```cs
var service = x.GetRequiredService<IHRMNotesRepository>();
```

For parallel execution, pull services from `IResolveFieldContext` like this:

```cs
using var scope = x.CreateScope();
var service = scope.GetRequiredService<IHRMNotesRepository>();
```

Write your extension methods like this:

```cs
public static T GetRequiredService<T>(this IResolveFieldContext ctx)
    => ctx.RequestServices!.GetRequiredService<T>();

public static IServiceScope(this IResolveFieldContext ctx)
    => ctx.RequestServices!.CreateScope();
```

It is critical not to put the `CreateScope` method inside the extension method, or else the scope will not be disposed, nor will any of the services that were created from that scope.

You can also use field builders to indicate scoped services for parallel execution:

```cs
Field<...>(...)
    .Resolve()
    .WithScope()
    .WithService<IHRMNotesRepository>()
    .Resolve((ctx, service) => { ... });
```

If you're using parallel execution, you'd likely find that the scope gets disposed before your data loader executes.  You need to create and dispose of the service scope inside the data loader.  Here is an example:

```cs
public class MyObject : ObjectGraphType
{
    public MyObject(IServiceScopeFactory scopeFactory) // pull the service scope factory from the root scope
    {
        Field<ListGraphType<HRMNotesResponseType>>(nameof(HRMInterviewee.ListNote))
        .Resolve(x =>
        {
            var loader = dataAccessor.Context.GetOrAddCollectionBatchLoader<...>(userIds =>
                {
                    using var scope = scopeFactory.CreateScope();
                    var service = scope.GetRequiredService<IHRMNotesRepository>();
                    return service.GetDataForUserIds(userIds);
                });
            return loader.LoadAsync(x.Source.Id);
        }
    }
}
```

Typically when I deal with scoped services, I use serial execution, as it simplifies much of this kind of code.  You may be able to write some extension methods for data loaders here.  Keep in mind that multiple requests will run in parallel even with serial execution.

**Comment by vansangnguyen1998** [comment] 2023-12-12 02:04
First of all, thanks for your solution. @Shane32 
I have implement 
   `         .AddScopedSubscriptionExecutionStrategy(false)`
in config startup of my application and subscription can be get service from IResolveFieldContext .
hmm, I am confusing about the performance with your solution.
Can you give me some documentation about the solution or sample for subscription use 
   `         .AddScopedSubscriptionExecutionStrategy(false)`

Best regards,
Sang

**Comment by Shane32** [comment] 2023-12-12 02:51
I'm not sure exactly what you're wondering.  I can explain the flow of GraphQL.NET as follows:

When a subscription requests comes in, this happens:
1. Incoming WebSocket connection arrives
2. ASP.NET Core creates service scope (A) within HttpRequest.RequestServices which will be disposed when the connection is terminated
3. GraphQL.NET Server sets up the connection and processes the connection initialization request, authenticates the request, etc
4. The websocket connection can handle multiple concurrent query, mutation or subscription requests; this flow assumes it is only used for a single subscription request
5. The subscription request arrives
6. GraphQL.NET Server creates a service scope (B) for the request
7. The request is resolved, with `IResolveFieldContext.RequestServices` being the provider from scope B
8. The request returns an `IObserverable`.
9. Service scope B is disposed

Each time the `IObservable` produces some data, it triggers another sequence:
1. Because of `AddScopedSubscriptionExecutionStrategy`, a service scope (C) is created
2. The resolvers (and data loaders) are executed for the data request, with `IResolveFieldContext.RequestServies` being the provider from scope C
3. Service scope C is disposed and the data is returned

Once the client shuts down the connection:
1. The `IObservable` is disposed
2. ASP.NET Core disposes of the service scope it created
3. The connection is closed

**Comment by Shane32** [comment] 2023-12-12 03:13
All of my other suggestion are merely to ensure two things:
1. Code inside a scoped service does not execute concurrently with other code.  This is necessary or else you will run into concurrency problems when you scale up your application.  When running with a parallel execution strategy, at any time multiple resolvers or multiple data loaders may be executing concurrently.  Note that any singleton services should be fine to pull and use directly from `IResolveFieldContext.RequestServices` as singleton services are generally designed for concurrent use.
2. All service scopes are dispose of properly.  Otherwise memory leaks may occur.

If you use a serial execution strategy, you can safely use any service pulled from `IResolveFieldContext.RequestServices` within any field resolver or data loader, as they will not be running concurrently with any other code in the same service scope.

**Comment by Shane32** [comment] 2023-12-12 03:24
> performance with your solution

Disposing of service scopes properly should provide better performance.

Ensuring that code within scoped services does not execute concurrently is necessary, regardless of performance.

Choosing a serial or parallel execution plan will affect performance.  A serial execution plan may in some scenarios provide better overall throughput, even if the response time of each individual request is generally slower.  This is due to reduced need to create service scopes and their services and possible utilize caching by those services (e.g. EF Core).  However, a properly implemented parallel execution plan is likely preferred, reducing the execution time of individual requests.  It all would depend greatly on your specific implementation, however -- a short-lived service scope (parallel execution) could also reduce the amount of generation 2 garbage collections, even if there are more generation 1 objects.

**Comment by Shane32** [comment] 2023-12-12 03:34
> Can you give me some documentation

I don't see that we have any documentation regarding proper use of `AddScopedSubscriptionExecutionStrategy` unfortunately.

It should added to this page probably: https://graphql-dotnet.github.io/docs/getting-started/dependency-injection/

**Comment by vansangnguyen1998** [comment] 2023-12-12 03:41
I got it,
Thanks for your answer, I hope that you will update documenttation ASAP.

**Comment by vansangnguyen1998** [comment] 2023-12-18 08:48
@Shane32 ,
I have reuse resolver type for subscription and resolver type for mutation.
But, when i run mutation and in the mutation have response type and subscription have the same class.
And recieve error:
`System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.    at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()    at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToDictionaryAsync[TSource,TKey,TElement](IQueryable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)    at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToDictionaryAsync[TSource,TKey,TElement](IQueryable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer, CancellationToken cancellationToken)    at Web.GraphQL.Repositories.AccountRepo.AccountRepository.GetLazyLoadAccountGraphqlType(IEnumerable`1 accountsIds) in /src/Web.GraphQL/Repositories/AccountRepo/AccountRepository.cs:line 1316    at GraphQL.DataLoader.BatchDataLoader`2.FetchAsync(IEnumerable`1 list, CancellationToken cancellationToken)    at GraphQL.DataLoader.DataLoaderPair`2.GraphQL.DataLoader.IDataLoaderResult.GetResultAsync(CancellationToken cancellationToken) in /_/src/GraphQL.DataLoader/DataLoaderPair.cs:line 93    at GraphQL.Execution.ExecutionStrategy.CompleteDataLoaderNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 540`.

i guess that, because resolver subscription and mutations have the same dataloader for IAccountRepository.
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/44341211/a681e1b9-27a6-4760-9603-3ec93cfaece9)

![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/44341211/61832933-50fd-4b65-b961-ff20a7e55ac6)

**Comment by Shane32** [comment] 2023-12-19 21:45
If you are going to use a parallel execution strategy for your query and subscription operations, you must create a service scope within each field resolver and within each data loader fetch delegate.  If you use a serial execution strategy, you do not need to.  Please see my post from a week ago which includes a code sample of how to do this.

**Comment by Shane32** [comment] 2023-12-19 21:47
![image](https://github.com/graphql-dotnet/graphql-dotnet/assets/6377684/647992cc-568f-4a6e-b062-7ea57730bf12)

**Comment by Shane32** [comment] 2023-12-19 21:48
In the sample you provided, the last line would be `return service.GetLazyLoadAccountGraphqlType(userIds);`

**Comment by Shane32** [comment] 2023-12-31 16:21
Let me know if you have further questions

**Closed by Shane32** 2023-12-31 16:21 UTC
Labels: documentation
