### ISSUE TITLE
WebSocketException: Intermittently the web socket disconnecting after upgrading the GraphQl package from 3.3.2 to 4.6.1

### ISSUE THREAD

**Issue by ManaseePatra** [graphql-dotnet/graphql-dotnet#2913] opened 2022-02-07 11:14 UTC
Hi joemcbride, we are trying to upgrade the graphql package from 3.3.2 to the latest 4.6.1, the performance is good as mentioned in the release note. But we observed that even the performance is fast  facing web socket disconnection issue intermittently. It's working fine with the older version. Can you Please suggest here?

**Comment by Shane32** [comment] 2022-02-07 14:36
Which version of the server project are you using?

**Comment by ManaseePatra** [comment] 2022-02-07 14:39
> Which version of the server project are you using?

currently it's the latest one version 5.1.1

**Comment by ManaseePatra** [comment] 2022-02-08 05:59
@Shane32 ,any suggestion or any idea please?

**Comment by joemcbride** [comment] 2022-02-08 06:51
@ManaseePatra Are you able to provide a small project that reproduces the issue?  That would go a long way in tracking down what the problem is. Without an example to reproduce the issue, it may be hard to help you figure out what is happening.

**Comment by ManaseePatra** [comment] 2022-02-08 07:41
> @ManaseePatra Are you able to provide a small project that reproduces the issue? That would go a long way in tracking down what the problem is. Without an example to reproduce the issue, it may be hard to help you figure out what is happening.

@joemcbride , Thank you. soon we will come back with a sample application and provide you.

**Comment by Shane32** [comment] 2022-02-08 13:11
@ManaseePatra issues with websockets are pretty hard to diagnose. Do you have a bit more description of what’s happening, environment details, server logs and so on. I’ll await the sample as well. Are you willing to spend the time necessary to work on this? The last websockets issue took a couple months to figure out. I usually only have only weekends available, at most, so if it’s anything difficult I won’t be able to help quickly.

I would suggest trying other versions of 4.x and Server 5.x to try to identify which exact version the problems started occurring within.  Specifically, try the server version immediately prior to 5.2.0. 

If you are able to send a sample that replicates the problem, and if we can reproduce the problem, we should be able to fix whatever the issue is quickly. Let’s hope that is the case. 

Ref:
- https://github.com/graphql-dotnet/server/issues/621

**Comment by Shane32** [comment] 2022-02-08 13:15
> > Which version of the server project are you using?
> 
> currently it's the latest one version 5.1.1. please let me know in case you need any more info. need your to rectify this issue.

Actually 5.1.1 isn’t the latest. Try server 5.2.0. It has all the websockets fixes from the aforementioned issue. Maybe it will fix your issue as well. You might also try the latest GraphQL.NET 4.7.1 but I don’t think websockets changed there at all from 4.6.1

**Comment by ManaseePatra** [comment] 2022-02-08 13:34
@Shane32 Thank you. let me quickly give a try with your above suggestion and going through the issue #621. I am in progress to developing a sample one also. Will update you soon.

**Comment by ManaseePatra** [comment] 2022-02-09 11:48
@Shane32 while upgrading to server version 5.2.0, i can see some classes obsolete like DefaultGraphQLExecuter, GraphQLBuilderCoreExtensions, ServiceCollectionExtensions and also some other. Is there any substitute is there exposed to reuse for those?

**Comment by Shane32** [comment] 2022-02-09 13:52
They will be fully supported throughout the server 5.x lifetime; you may find it easiest to ignore the error for now. There is a new set of builder methods included in the main project to replace the builder methods in the server project. The obsolete methods will be removed in the next major version.

**Comment by ManaseePatra** [comment] 2022-02-14 06:56
Hi @Shane32, even i have included the builder methods from main project still there are some which I'm not getting any solution .AddRelayGraphTypes() and .AddUserContextBuilder<GraphQLUserContextBuilder>(). and also it's not supporting .AddWebSockets() in main graphql. How to handle this can you please help?

**Comment by ManaseePatra** [comment] 2022-02-14 06:59
Also getting the below issue after adding .AddGraphQL() from the GraphQL.MicrosoftDI package(version- 4.7.1).The call is ambiguous between the following methods or properties: 'GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddGraphQL(Microsoft.Extensions.DependencyInjection.IServiceCollection)

**Comment by Shane32** [comment] 2022-02-14 07:11
Unfortunately there is a conflict so you will need to explicitly reference the extension method you wish to use - either the older one from the server project (marked as obsolete) or the new one from the GraphQL.NET project. 

You may simply wish to continue to use the old method. It is fully supported through the lifetime of the current version. It will be removed in the next major version. If you use the old method, you won’t need to change any of your existing code (other than to explicitly reference the extension method). It will continue to work just as it did before.  

The new builder methods are a bit different than the old ones. If you have a question on a specific method, I can answer it tomorrow probably. Offhand I believe that AddRelayGraphTypes is unnecessary now. Not sure why you’d have a problem with the others, but I’m not at a pc just now.

**Comment by ManaseePatra** [comment] 2022-02-14 13:39
@Shane32 Thank you. for the timing we are going with the older implementation(means with obsolete methods) and continuing my verification regarding the web socket issue. we will update you.

**Comment by Shane32** [comment] 2022-02-14 17:20
I looked up the methods you mentioned.  I really don't know why AddUserContextBuilder or AddWebSockets wouldn't work for you; there were new methods added for the new builder interface.  Let me know if you want to try the new builder methods again, and we can investigate further.  I would first suggest ensuring that all nuget package references are updated and then "rebuild" your solution to ensure that intellisense is working properly.

**Comment by sungam3r** [comment] 2023-04-06 22:06
@ManaseePatra graphql.net v7.x is here with completely rewritten websockets stuff. I suggest to read migration guides. Please close this one if it's not actual anymore.

**Comment by Shane32** [comment] 2023-04-06 22:49
If there are any issues with GraphQL.NET v7, I may be able to help diagnose the issue.  The server implementation is completely rewritten as @sungam3r indicated, and fixes many issues present in the old version.

**Closed** 2023-04-24 01:39 UTC
Labels: subscriptions
