### ISSUE TITLE
Throw exceptions during execution

### ISSUE THREAD

**Issue by wingsking** [graphql-dotnet/graphql-dotnet#650] opened 2018-05-03 01:22 UTC
What the DocumentExecuter does right now is that any exceptions occur during execution will be swallowed and put into ExecutionResult.Errors as ExecutionError. In my case, I would like to throw non-ExecutionErrors intentionally, so that my service can return 500 InternelServerError to clients.

What do you think is the best way to support this? Should we add an switch to ExecutionOption? 
I'm thinking about something like this:
```
catch (Exception ex)
            {
                if (options.ThrowExceptions)
                {
                    throw ex;
                }

                result = new ExecutionResult
                {
                    Errors = new ExecutionErrors()
                    {
                        new ExecutionError(ex.Message, ex)
                    }
                };
            }

```

Thoughts?

**Comment by joemcbride** [comment] 2018-05-03 04:09
Duplicate of #607 - can you add your comments there?  Thanks!

**Closed by joemcbride** 2018-05-03 04:09 UTC
