### ISSUE TITLE
Instead of requiring RequiredAttribute respect nullable reference types

### ISSUE THREAD

**Issue by SimonCropp** [graphql-dotnet/graphql-dotnet#2486] opened 2021-04-08 00:00 UTC
In the context of nullable reference types a property can be determined to be required from reflection, and no need the attribute.

Thoughts?

**Comment by Shane32** [comment] 2021-04-08 00:26
It’s a bit of a pain but I got it going in my helper library, fully tested. 

https://github.com/Shane32/GraphQL.DI/blob/d506165c1f343881fd3124475b8cd7ffb8d3bdd9/src/GraphQL.DI/DIObjectGraphType.cs#L296

I’m not sure in what locations this would best apply, but there’s probably multiple.

**Comment by Shane32** [comment] 2021-04-08 00:30
It could also likely be improved further in the GetGraphTypeFromType method so that the enumerated types’ nullability properties can be properly transferred to graph types, which is not possible now at all.

**Comment by sungam3r** [comment] 2021-04-08 19:56
see #1229

**Comment by sungam3r** [comment] 2022-02-04 23:31
@Shane32, done?

**Comment by Shane32** [comment] 2022-02-04 23:57
Yes I believe so. It’s possible that the issue is referring to some other part of code besides the auto graph types …

**Comment by sungam3r** [comment] 2022-02-05 09:29
@SimonCropp, please provide an example of feature you want so we can ensure

**Comment by sungam3r** [comment] 2022-02-13 09:21
I'll close this one after month (+/-) of inactivity or after v5 release.

**Closed** 2022-05-22 22:13 UTC
Labels: needs confirmation
