### ISSUE TITLE
variable support issue in mutations: "Variable '$input' is invalid. Unable to parse input as a 'heroInput' type. Did you provide a List or Scalar value accidentally?"

### ISSUE THREAD

**Issue by RyanGhd** [graphql-dotnet/graphql-dotnet#2202] opened 2021-01-21 04:30 UTC
## Description

Looks like the new version of graphql-dotnet does not support variables in mutation as it used to do.
it throws:
```
Variable '$input' is invalid. Unable to parse input as a 'heroInput' type. Did you provide a List or Scalar value accidentally?
```

### Steps to reproduce

Here is the sample
Server side impl:
```
public class Hero
    {
        public string Name { get; private set; }
        public string SuperPower { get; private set; }

        public Hero(string name, string superPower)
        {
            Name = name;
            SuperPower = superPower;
        }
    }

    public class HeroGraphType : AutoRegisteringObjectGraphType<Hero>
    {
        public HeroGraphType():base()
        {
            this.Name = "hero";
        }
    }

    public class HeroInputGraphType : AutoRegisteringInputObjectGraphType<Hero>
    {
        public HeroInputGraphType():base()
        {
            this.Name = "heroInput";
        }
    }

    public class UpdateHeroMutation : ObjectGraphType
    {
        public UpdateHeroMutation()
        {
            this.FieldAsync<HeroGraphType>("updateHero", "Updates hero",
                new QueryArguments(new QueryArgument<HeroInputGraphType> { Name = "input" }),
                ctx =>
                {
                    var input = ctx.GetArgument<Hero>("input");
                    // ...
                    return Task.FromResult<object>(new Hero(input.Name, input.SuperPower));
                });
        }
    }
```

client side mutation:
```
mutation($input:heroInput){
  	updateHero(input:$input){
 		name superPower
  }
}
```
client side variable:
```
{
  "input": {
    "name": "superman",
    "superPower": "laser eyes"
  }
}
```
### Expected result
to return the following:
```
{
  "data": {
    "updateHero": {
      "name": "superman",
      "superPower": "laser eyes"
    }
  }
}
```

### Actual result
it returns :
```
{
  "errors": [
    {
      "message": "Variable '$input' is invalid. Unable to parse input as a 'heroInput' type. Did you provide a List or Scalar value accidentally?",
      "locations": [
        {
          "line": 1,
          "column": 11
        }
      ],
      "extensions": {
        "code": "INVALID_VALUE",
        "codes": [
          "INVALID_VALUE"
        ]
      }
    }
  ]
```

it may worth mentioning that the following client side mutation syntaxes work fine:
1-
```
mutation{
  	updateHero(input:{
      name: "superman",
      superPower: "laser eyes"
    }){
 		name superPower
  }
}
```
2-
```
mutation($input: heroInput = {
  name: "superman",
  superPower: "laser eyes"
}){
  	updateHero(input:$input){
 		name superPower
  }
}
```

### Environment
```
TargetFramework net5.0

GraphQL 3.3.1
GraphQL.Authorization 3.1.0
GraphQL.Server.Transports.AspNetCore 4.4.1
GraphQL.Server.Transports.AspNetCore.SystemTextJson 4.4.1
GraphQL.Server.Ui.Altair 4.4.1
GraphQL.SystemTextJson 3.3.1
```

**Comment by Shane32** [comment] 2021-01-21 07:02
What if you change the hero class to have writable properties - does it work then?

**Comment by RyanGhd** [comment] 2021-01-21 23:01
@Shane32 , I tried it with public setters on Hero the result was the same.
 
The other 2 syntaxes (that I mentioned above) work fine. They convert the same json object (heroInput) to the associated type (Hero). is it not like, the issue should have happened in those cases if the problem was related to private setters?

Also context.Arguments property is a Dictionary<string,object> that holds input properties as recursive Dictionary<string,object>. Not sure where and why it tries to cast the variable (heroInput json object) to the assiciated type (Hero).

**Comment by Shane32** [comment] 2021-01-21 23:23
Right. I guess I’m just not sure without testing the code what the problem is. I have lots of input models that work fine as variables. Like you said, it does seem to have something to do with variable parsing. Good news is that I recently completely revamped the variable parsing code for 4.0, which should be released within a week or so.

**Comment by RyanGhd** [comment] 2021-01-21 23:45
@Shane32 , that's great, I'll give it a test after your release and let you the result.

**Comment by Shane32** [comment] 2021-01-22 20:56
@RyanGhd I created a test for your scenario and was unable to reproduce your error.  Perhaps you can review the code to see if there are any differences compared to your implementation.  Tested with v3.3.1.

```cs
using System.Threading.Tasks;
using GraphQL.SystemTextJson;
using GraphQL.Types;
using Xunit;

namespace GraphQL.Tests.Bugs
{
    // https://github.com/graphql-dotnet/graphql-dotnet/issues/2202
    public class Issue2202VariableParsing : QueryTestBase<Issue2202Schema>
    {
        [Fact]
        public void Validate_Mutation() => AssertQuerySuccess(
            "mutation($input:heroInput) { updateHero(input:$input) { name superPower } }",
            @"{ ""updateHero"": { ""name"": ""superman"", ""superPower"": ""laser eyes"" } }",
            @"{ ""input"": { ""name"": ""superman"", ""superPower"": ""laser eyes"" } }".ToInputs());

    }

    public class Issue2202Schema : Schema
    {
        public Issue2202Schema()
        {
            Query = new Issue2202Query();
            Mutation = new Issue2202UpdateHeroMutation();
        }
    }

    public class Issue2202Query : ObjectGraphType
    {
        public Issue2202Query()
        {
            Field<Issue2202HeroGraphType>("hero", resolve: context => new Issue2202Hero("test", "flying"));
        }
    }

    public class Issue2202Hero
    {
        public string Name { get; private set; }
        public string SuperPower { get; private set; }

        public Issue2202Hero(string name, string superPower)
        {
            Name = name;
            SuperPower = superPower;
        }
    }

    public class Issue2202HeroGraphType : AutoRegisteringObjectGraphType<Issue2202Hero>
    {
        public Issue2202HeroGraphType() : base()
        {
            Name = "hero";
        }
    }

    public class Issue2202HeroInputGraphType : AutoRegisteringInputObjectGraphType<Issue2202Hero>
    {
        public Issue2202HeroInputGraphType() : base()
        {
            Name = "heroInput";
        }
    }

    public class Issue2202UpdateHeroMutation : ObjectGraphType
    {
        public Issue2202UpdateHeroMutation()
        {
            FieldAsync<Issue2202HeroGraphType>("updateHero", "Updates hero",
                new QueryArguments(new QueryArgument<Issue2202HeroInputGraphType> { Name = "input" }),
                ctx =>
                {
                    var input = ctx.GetArgument<Issue2202Hero>("input");
                    return Task.FromResult<object>(new Issue2202Hero(input.Name, input.SuperPower));
                });
        }
    }
}
```

**Comment by sungam3r** [comment] 2021-01-22 22:23
May be related to #2189

**Comment by sungam3r** [comment] 2021-02-22 13:07
Closed as resolved. @RyanGhd If the error persists in v4, then reopen this issue.

**Closed by sungam3r** 2021-02-22 13:07 UTC
