### ISSUE TITLE
Implementing GraphQL in MVC solution - Never returns

### ISSUE THREAD

**Issue by VikingRedleg** [graphql-dotnet/graphql-dotnet#2748] opened 2021-12-10 23:15 UTC
I have added a few classes to send requests and handle responses from an external GraphQL web API, which use the GraphQL package from NuGet as well as HttpClient to connect to the API. The classes live in one project of my solution ("providers"). I have also added Test classes and methods to test the functionality of the service classes. The Tests all work as expected - results come back and they match the same queries made in Postman. Having success with the tests, I added references to the service classes to the main project which is an MVC web application in order to supplement user search capabilities - so calling a method from the same project as the Api helper classes within a controller in the MVC application. This is when I started having issues.

As an aside I did not have to add any of the GraphQL packages to the Test project, and it was able to work fine by just referencing the provider project that contains the api helper class. So it seems a bit like overkill in the first place that I had to add all that to the MVC project.

Initially, I was getting errors such as "ReadAsAsync doesn't exist" (this is a method of the System.Net.Http.HttpContent class I think?). This method was used in other classes that consume other external web services using HttpClient in the same project. In fact the method that was failing was nearly identical to ones in other classes that had been working for years at this point. So I thought it was strange it stopped working at this time. I eventually concluded it had something to do with all the dependencies added by adding the GraphQL nuget packages to the "providers" project.

I then added those same GraphQL packages to the MVC project to see if that resolved the issue. This added some issues where it couldn't find some System.IO libraries. I had seen this before in another project where I had to update the .NET version and the solution in that case was to remove the offending dependentAssembly entries in the web.config file. I did that here. Now, I load the web application in debug mode, and can click through to the page where the controller action to search using the new API class is located. The original search actions still work - I am able to get results using them. But the new API method does not. It does not throw an exception. It does not return results. The execution simply stops or seems to stop after the call to the API happens. The GraphQLHttpClient.SendQueryAsync just never comes back. It could just be that I'm not waiting long enough, but I gave it 10 minutes at one point for a query that runs in seconds in the test project, and also in seconds in postman. The application remains operational, though. I can still use other functions of the site after clicking on this.

I guess the question is - how can I find out what the problem is here? Or correct it in some way? I'm currently trying removing different dependentAssembly entries in the MVC project but that isn't really working out very well so far. Some of those entries are needed by the application. But not all of them.

**Comment by sungam3r** [comment] 2021-12-11 12:34
A minimal repro is appreciated.

**Comment by VikingRedleg** [comment] 2021-12-13 21:38
> A minimal repro is appreciated.

Understood, what would you consider to be a suitable minimal repro? Do I need to provide a solution with two projects, the class to consume the graphql service, the provider class, and then the web app with a controller that calls the provider, along with all the different nuget packages?

An alternative solution would be "how do I make a request to a graphql service without using this library"  - just by posting a plain-text content to the endpoint?  I literally only need one specific query so there is probably a lot of overkill in the 15 nuget packages that got installed here.

**Comment by sungam3r** [comment] 2021-12-13 22:39
It can be solution of any size - as you prefer. Or it can be even a PR adding test in this project. The main thing is to demonstrate a bug by some means. Of course, it is desirable to minimize the amount of secondary code not related to the problem itself.

**Comment by Shane32** [comment] 2021-12-13 22:52
It seems to me that the issue here has to do with the GraphQL.Client nuget package, as it seems to be the client that is not finishing the await?  So if it is possible to reproduce the issue accessing either a public GraphQL server or the sample Harness sample included in this repo, then a simple console app demonstrating the issue would be sufficient.

If you're unable to reproduce the issue as described above, I would suggest forking this repo and making as few necessary changes to the Harness sample as possible in order to reproduce the issue with the sample client console app.  Then it will be easy to see the changes required to the Harness sample that in conjunction with the client sample code, caused the bug to manifest itself.

Bottom line is that I think we would need to see enough code to reproduce the problem.

Reading through the original issue, I think it is very interesting that you are/were getting errors with "ReadAsAsync doesn't exist" and "it couldn't find some System.IO libraries".  Typically when you import a nuget package, all the required dependencies are automatically installed.  Which version of .NET or the .NET Framework are you using?  GraphQL.Client should support .NET Framework 4.6.1+ and .NET Core 2.0+ (by nature of suporting .NET Standard 2.0).  Are you using the Newtonsoft serializer or System.Text.Json and which version?  Are there any build warnings that relate to the nuget restore process?  Are you attempting to use GraphQL.Client within a runtime-based "plugin" type system to another project, where the dependencies may not be installed in the parent project?

**Comment by VikingRedleg** [comment] 2021-12-14 04:14
@Shane32 You are correct it is the GraphQL.Client nuget package - and the large quantity of attendant Nuget packages that had to be installed along with it.  The code that implements the GraphQL.Client exists in a dll project.  The web application project then calls this within a controller action, and that is the context in which the errors or non-completion occur.  The unit-tests project calls the same code with slightly less abstraction without needing any of the nuget packages or really any config changes other than the URL of the GraphQL endpoint.

So the structure is like

- Solution
- - Object Project
- - - Search Provider Interface
- - Data Project
- - - GraphQL helper class <- only class in entire solution that directly uses GraphQL libraries
- - - General Search Provider class (implements interface)
- - Data Tests project
- - - GraphQL helper tests (works)
- - Web App (MVC) project
- - - SearchController - calls graphql method of search provider via interface using Unity Dependency Injection (does not work)

.NET version is 4.6.2, Newtonsoft serializer is 4.0.1.0.  I will go through the warnings and get back to you. I did notice one from another project in the solution which may be related to the Unity piece. But there are generic warnings relating to naming convention choices and things of that like so a lot of lines to go through.  I will also attempt to get a sample solution put together.  I probably won't re-implement the Unity part of it so if I do all that and it runs without Unity in the middle  I guess I will have a good idea of that part of the problem.  I am assuming the sample harness is easy to include, as this is my first time even being aware that GraphQL exists let alone being aware of any public repositories.

**Comment by Shane32** [comment] 2021-12-15 03:57
Are you using subscriptions or communicating via websocket?  If not -- if it's a basic GET or POST request -- it's very easy to whip up your own wrapper for GraphQL calls.  You're basically just calling a REST API and using System.Text.Json to convert the resulting data stream to a typed object.  Then you don't have to deal with any nuget dependencies at all, and you could write it in probably under 50 lines of code.  Sorry my implementation has a whole bunch of logging and stuff, or I'd copy and paste it in.

**Comment by VikingRedleg** [comment] 2021-12-15 05:12
@Shane32 that would be ideal to skip all this library stuff I don't really need.  I'm not sure what you mean by subscription.  The sample I have works in Postman.  And in my code I'm using the SendQueryAsync<T> method of the GraphQLHttpClient class, which I am assuming basically does a simple HTTP POST.  But when I try to send it as text with HttpClient it doesn't really work, either.  I also don't have really any good examples to work from, though.  I have to wonder if maybe I'm not sending the right headers.  I was using application/json but also tried application/graphql.  This is something I've been tinkering with alongside trying to put together the minimal example solution.

**Comment by Shane32** [comment] 2021-12-15 05:18
Maybe I can whip up a sample for you if I have some time soon.

**Comment by Shane32** [comment] 2021-12-15 17:27
Here is a working sample with .NET Framework 4.6.2 and Newtonsoft.Json 4.0.1:

```cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Client
{
    internal class Program
    {
        static void Main(string[] args)
        {
            MainAsync(default).Wait();
        }

        static async Task MainAsync(CancellationToken cancellationToken)
        {
            Console.WriteLine("Searching for city 'detroit'...");
            var result = await CallGraphQlAsync<MyResponseData>(
                new Uri("https://graphql-weather-api.herokuapp.com/"),
                HttpMethod.Post,
                "query ($city: String!) { getCityByName(name: $city) { name country } }",
                new
                {
                    city = "detroit",
                },
                cancellationToken);
            // note that errors produced by the GraphQL endpoint will be returned in result.Errors
            Console.WriteLine($"Found city {result.Data.GetCityByName.Name}, {result.Data.GetCityByName.Country}");
            Console.WriteLine("Press enter to exit");
            Console.ReadLine();
        }

        private class MyResponseData
        {
            public MyResponseGetCityByName GetCityByName { get; set; }
        }

        private class MyResponseGetCityByName
        {
            public string Name { get; set; }
            public string Country { get; set; }
        }

        private static HttpClient httpClient = new HttpClient();

        static async Task<GraphQlResponse<TResponse>> CallGraphQlAsync<TResponse>(Uri endpoint, HttpMethod method, string query, object variables, CancellationToken cancellationToken)
        {
            var content = new StringContent(SerializeGraphQlCall(query, variables), Encoding.UTF8, "application/json");
            var httpRequestMessage = new HttpRequestMessage
            {
                Method = method,
                Content = content,
                RequestUri = endpoint,
            };
            //add authorization headers if necessary here
            httpRequestMessage.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            var response = await httpClient.SendAsync(httpRequestMessage, cancellationToken);
            if (response.IsSuccessStatusCode)
            {
                var responseString = await response.Content.ReadAsStringAsync(); //cancellationToken supported for .NET 5/6
                return DeserializeGraphQlCall<TResponse>(responseString);
            }
            else
            {
                throw new ApplicationException($"Unable to contact '{endpoint}': {response.StatusCode} - {response.ReasonPhrase}");
            }
        }

        public class GraphQlErrorLocation
        {
            public int Line { get; set; }
            public int Column { get; set; }
        }

        public class GraphQlError
        {
            public string Message { get; set; }
            public List<GraphQlErrorLocation> Locations { get; set; }
            public List<object> Path { get; set; } //either int or string
        }

        public class GraphQlResponse<TResponse>
        {
            public List<GraphQlError> Errors { get; set; }
            public TResponse Data { get; set; }
        }

        private static string SerializeGraphQlCall(string query, object variables)
        {
            var sb = new StringBuilder();
            var textWriter = new StringWriter(sb);
            var serializer = new JsonSerializer();
            serializer.Serialize(textWriter, new
            {
                query = query,
                variables = variables,
            });
            return sb.ToString();
        }

        private static GraphQlResponse<TResponse> DeserializeGraphQlCall<TResponse>(string response)
        {
            var serializer = new JsonSerializer();
            var stringReader = new StringReader(response);
            var jsonReader = new JsonTextReader(stringReader);
            var result = serializer.Deserialize<GraphQlResponse<TResponse>>(jsonReader);
            return result;
        }
    }
}
```

**Comment by Shane32** [comment] 2021-12-15 17:39
Note that some GraphQL endpoints do not return a 200 status code if there are any errors in the response.  You also may need authentication headers or other changes.  If using GraphQL.NET as the back-end, there is additional information in the extensions property of the error object that is available.  And if you're trying to read queries with interfaces or unions in the response, then parsing the data can get messy.  Bottom line: you will need to tailor this code to suit your needs.

**Comment by VikingRedleg** [comment] 2021-12-15 19:40
OK, I have a minimum reproduction should I zip it up or just dump all the files here?

**Comment by VikingRedleg** [comment] 2021-12-15 19:41
@Shane32 your version is much more seemingly complicated than mine, regarding the httpclient.  However, perhaps that is part of my problem.  I will attempt to adapt your solution to my scenario.

**Comment by VikingRedleg** [comment] 2021-12-15 20:17
[GraphQLDemo.Web.zip](https://github.com/graphql-dotnet/graphql-dotnet/files/7722442/GraphQLDemo.Web.zip)

**Comment by sungam3r** [comment] 2021-12-15 20:47
I'll check it.

**Comment by sungam3r** [comment] 2021-12-15 20:55
What should I do to reproduce ?

**Comment by sungam3r** [comment] 2021-12-15 21:16
Nevermind, it's a classic deadlock issue with `.Result` in web app.

**Comment by sungam3r** [comment] 2021-12-15 21:21
Change 
`var gqlResponse = client.SendQueryAsync<GqlData>(gqlRequest).Result;`
to
`var gqlResponse = await client.SendQueryAsync<GqlData>(gqlRequest);`

and 
`public static GqlResponse GetGqlResponse(string name)`
to
`public static async Task<GqlResponse> GetGqlResponse(string name)`

and use
```
 public async Task<ActionResult> Index()
        {
            var city = await GraphQlApi.GetGqlResponse("Detroit");
            return View(city);
        }
```

**Comment by sungam3r** [comment] 2021-12-15 21:23
By the way, https://github.com/graphql-dotnet/graphql-client/pull/370 should solve this issue too.

**Comment by sungam3r** [comment] 2021-12-15 21:25
ping @rose-a , it seems the time for release.

**Comment by VikingRedleg** [comment] 2021-12-15 23:05
I use NuGet so would have to wait for the release if this is a known bug that will be fixed.

However, using this seems to have worked:

```
    var task = Task.Run(async () => await client.SendQueryAsync<GqlData>(gqlRequest));
    var gqlResponse = task.Result;

```
I tried this rather than modifying the controller and a bunch of other methods in my main code to make them async.

**Comment by VikingRedleg** [comment] 2021-12-15 23:17
Well I'm reading now that this is not ideal either as it can cause problems in web applications, which is my exact context.  So back to the drawing board we'll see how it goes tomorrow.

**Comment by sungam3r** [comment] 2021-12-15 23:17
>  if this is a known bug 

It's not a bug in library code. Actually it's a bug in your code. Read [this](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

>  var task = Task.Run(async () => await client.SendQueryAsync<GqlData>(gqlRequest));

You will make the code even worse.

**Comment by Shane32** [comment] 2021-12-15 23:52
I'm pretty sure that the original issue was due to the `SynchronizationContext` being unable to be restored during the asynchronous task flow of the `HttpClient`.  Your thread is locking on `.Result`, blocking the synchronization context created by ASP.NET, so that once the response is received by the HttpClient, it is unable to restore the context onto a new worker thread to finish execution, as the context is still in use on the first thread.  Classic deadlock scenario.

By using `Task.Run`, you are creating an asynchronous flow that does not use a synchronization context.  So although you have not solved the underlying issue of blocking the synchronization context, it does not matter to the `HttpClient` because it will continue to execute without a context until complete.  Then the `task.Result` will unblock and you can use the result.

So the solution you came up with is a completely valid workaround, even if not preferred.

This is also the reason that @sungam3r said that the updated release of the GraphQL.Client library would fix the problem.  It is because adding `ConfigureAwait(false)` tells .NET not to restore the synchronization context when finishing execution of the asynchronous execution.  But it would be necessary for every single `await` call, including all those inside `HttpClient` and so on, to have `ConfigureAwait(false)` in there.

Note that ASP.NET Core has no synchronization context.  Only ASP.NET running on .NET Framework has a synchronization context.  Other application types that have a synchronization context include a Windows Forms app or a WPF app.  Console apps never have a synchronization context.  I don't think Windows Service apps have a synchronization context either, but I'm not sure.

Finally, the code sample I provided does not fix the issue, because it is also missing the necessary `.ConfigureAwait(false)` methods, and is an asynchronous code sample.  Ideally synchronous code should never call asynchronous methods, but `HttpClient` does not include synchronous methods.  The proper solution for you would really to use `WebRequest`, which has synchronous methods, instead of using `HttpClient`.

See: https://docs.microsoft.com/en-us/dotnet/api/system.net.webrequest?view=net-6.0

Note that although `WebRequest` is not listed as deprecated, Microsoft recommends to use `HttpClient` for all new code.

I will update the sample above to include `.ConfigureAwait(false)` and it should work properly for you without having to use `Task.Run`.

**Comment by VikingRedleg** [comment] 2021-12-16 18:25
I hear you guys. I think what the plan is, is to make this process asynchronous as a controller action can just be asynchronous.  That will probably resolve the problem.  I don't want to use WebRequest if I don't have to.

**Comment by rose-a** [comment] 2021-12-16 19:59
> ping @rose-a , it seems the time for release.

done...

**Comment by sungam3r** [comment] 2021-12-16 21:52
Thanks. Closing as resolved.

**Closed by sungam3r** 2021-12-16 21:52 UTC
Labels: question, needs confirmation

**Comment by VikingRedleg** [comment] 2021-12-17 20:24
Just want to say thanks guys.  I don't think I have encountered this deadlock issue before, So it was a good lesson going forward.
