### ISSUE TITLE
Error: The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[Newtonsoft.Json.Linq.JToken]. Path: $.variables | LineNumber: 0 | BytePositionInLine: 116.

### ISSUE THREAD

**Issue by fulviocanducci** [graphql-dotnet/graphql-dotnet#1439] opened 2019-11-28 15:28 UTC
### Example:
![graphql-error](https://user-images.githubusercontent.com/25593291/69817575-a90d0680-11d9-11ea-8403-420530bd7379.png)

### Json Error Complete
```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "|dbaac12a-46633a6f98c669bc.",
  "errors": {
    "$.variables": [
      "The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[Newtonsoft.Json.Linq.JToken]. Path: $.variables | LineNumber: 0 | BytePositionInLine: 84."
    ]
  }
}
```

## Relevant information

I noticed that there is no request in the controller, I think it is in the middleware!

### Environment (if relevant)
- Visual Studio 2019
- Last Version GrapQL
- .NET Core

#

Class Map
```
public class StateMapType : ObjectGraphType<State>
{
      public StateMapType()
      {
         Name = "state";
         Field(x => x.Id).Name("id");
         Field(x => x.Uf).Name("uf");
         Field<ListGraphType<CountryMapType>>().Name("country");
      }
}
```
GraphQLQuery
```
Field<ListGraphType<StateMapType>>(
           name: "states",
           arguments: new QueryArguments(
             new QueryArgument<BooleanGraphType>() { Name = "load", DefaultValue = false }
           ),
           resolve: context =>
           {
              bool load = context.GetArgument<bool>("load");
              IQueryable<State> query = DatabaseAccess.State.AsQueryable();
              if (load)
              {
                 query = query.Include(x => x.Country);
              }
              return query.AsNoTracking().ToList();
       }
 );
```

What could it be?

Note: I'm developing a package and it already worked the Query part, but this part of passing variables I can't make it work

https://www.nuget.org/packages/Canducci.GraphQLQuery/

**Comment by sungam3r** [comment] 2019-11-28 16:04
Can you show any server logs?

> Last Version GrapQL

2.4.0 or latest 3.0.0-preview ?

**Comment by fulviocanducci** [comment] 2019-11-28 16:08
Test on both versions 2.4.0 e 3.0.0-preview !!!

**Comment by fulviocanducci** [comment] 2019-11-28 17:22
@sungam3r 

```
System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by fulviocanducci** [comment] 2019-11-28 17:28
@sungam3r Other Example:

```
{"query":"{state_find(id:$id){state{id,uf}}}","variables": "{\"id\":1}"}
```

Error:

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|1eca12b9-47b16751bde8dba1.",
    "errors": {
        "$.variables": [
            "The JSON value could not be converted to System.Collections.Generic.IEnumerable`1[Newtonsoft.Json.Linq.JToken]. Path: $.variables | LineNumber: 0 | BytePositionInLine: 90."
        ]
    }
}
```
Obs:

I made several attempts but all unsuccessfully ...

It is worth remembering that passing or direct value in the functioning perfectly

**Comment by sungam3r** [comment] 2019-11-29 06:53
You have not declared a variable. 
https://graphql.org/learn/queries/#variables

**Comment by sungam3r** [comment] 2019-11-29 06:57
> 
> 
> @sungam3r this:
> 
> ```
> System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
>    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
>    at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
>    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> ```

It seems that this is a different error, here another serializer is used.

**Comment by fulviocanducci** [comment] 2019-11-29 14:32
> You have not declared a variable.
> https://graphql.org/learn/queries/#variables

Yes the variable was declared

**Comment by fulviocanducci** [comment] 2019-11-29 14:53
> > @sungam3r this:
> > ```
> > System.Text.Json.JsonException: A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.
> >    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerCycleDetected(Int32 maxDepth)
> >    at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
> >    at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
> >    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
> >    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
> > --- End of stack trace from previous location where exception was thrown ---
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
> >    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
> >    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
> >    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
> >    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
> >    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
> > ```
> 
> It seems that this is a different error, here another serializer is used.

So the test was done GraphiQL and Google PostMan and gives errors like that. By the time I move to variables already the problem rolls.

Is there an example somewhere on how to pass to variables?

**Comment by sungam3r** [comment] 2019-11-29 18:15
{"query":"{state_find(id:$id){state{id,uf}}}","variables": "{\"id\":1}"}

> Yes the variable was declared

No, this is a query without variable declaration.

**Comment by pekkah** [comment] 2019-11-29 19:02
Are you using system.text.json? It doesn't mix well with json.net. I don't think this project yet supports it unless you create a custom converter for the variables which is tricky as the system.text.json does not support dictionary of objects yet. My not so pretty converter can be found here https://github.com/pekkah/tanka-graphql/blob/master/src/graphql.server.links/DTOs/ObjectDictionaryConverter.cs

**Comment by fulviocanducci** [comment] 2019-11-29 22:48
> {"query":"{state_find(id:$id){state{id,uf}}}","variables": "{"id":1}"}
> 
> > Yes the variable was declared
> 
> No, this is a query without variable declaration.



> Are you using system.text.json? It doesn't mix well with json.net. I don't think this project yet supports it unless you create a custom converter for the variables which is tricky as the system.text.json does not support dictionary of objects yet. My not so pretty converter can be found here https://github.com/pekkah/tanka-graphql/blob/master/src/graphql.server.links/DTOs/ObjectDictionaryConverter.cs


This error comes from the Visual Studio log, so I didn't program it.

**Comment by fulviocanducci** [comment] 2019-11-29 22:49
> {"query":"{state_find(id:$id){state{id,uf}}}","variables": "{"id":1}"}
> 
> > Yes the variable was declared
> 
> No, this is a query without variable declaration.

Tem algum exemplo?

**Comment by fulviocanducci** [comment] 2019-11-29 23:01
@pekkah and @sungam3r 

![Sem título](https://user-images.githubusercontent.com/25593291/69892319-004ace00-12e3-11ea-873c-026d6b0f98d5.png)

**Comment by sungam3r** [comment] 2019-11-30 10:46
Change `id: 1` to `id: $id` - it will be right. But honestly, I still don’t understand what was going on.

**Comment by fulviocanducci** [comment] 2019-11-30 13:27
> Change `id: 1` to `id: $id` - it will be right. But honestly, I still don’t understand what was going on.

GraphiQL->

![abcdef](https://user-images.githubusercontent.com/25593291/69901060-f9f83880-135a-11ea-9d01-1a3cd775447d.png)

Me neither!


If there are passing variables of this problem.

**Comment by sungam3r** [comment] 2019-11-30 15:13
Try to send the same request via GraphQL Playground. Maybe you use old version of GraphiQL ?

**Comment by fulviocanducci** [comment] 2019-11-30 15:53
> Try to send the same request via GraphQL Playground. Maybe you use old version of GraphiQL ?

I tried and it didn't work either. Also did test on Google PostMan and the same error.

**Comment by joemcbride** [comment] 2019-11-30 16:17
Looking at the error, it is trying to create an `IEnumerable<JToken>`.  You’re not passing a JSON array, you’re passing a Object (as you should).  What does the code look like that is handling the HTTP request?  Are you using the GraphQL-sever project or did you write your own middleware/controller?

**Comment by fulviocanducci** [comment] 2019-11-30 16:26
> Looking at the error, it is trying to create an `IEnumerable<JToken>`. You’re not passing a JSON array, you’re passing a Object (as you should). What does the code look like that is handling the HTTP request? Are you using the GraphQL-server project or did you write your own middleware/controller?

Package:

https://github.com/graphql-dotnet/graphql-dotnet

### Documentation:

https://graphql-dotnet.github.io/

### GraphiQL

https://graphql-dotnet.github.io/docs/getting-started/graphiql



### Nothing but that.

The test is done in GraphIQL as it is in the link



In short: nothing but what the package offers me and its documentation.

Understood?

**Comment by joemcbride** [comment] 2019-11-30 16:37
No, I don’t understand, because this project does not provide a MVC Controller or Middleware to use, so you would need to write that yourself (which appears to be where this error is coming from).  This error does not look like an error due to this project but your own code.

So please post a screenshot of the csproj file so we can see the exact nuget packages you’re using  and the code you wrote to handle the HTTP request.

**Comment by fulviocanducci** [comment] 2019-11-30 16:49
> No, I don’t understand, because this project does not provide a MVC Controller or Middleware to use, so you would need to write that yourself (which appears to be where this error is coming from). This error does not look like an error due to this project but your own code.
> 
> So please post a screenshot of the csproj file so we can see the exact nuget packages you’re using and the code you wrote to handle the HTTP request.

Code: 
[What is in the documentation](https://graphql-dotnet.github.io/docs/getting-started/graphiql)

```csharp
using GraphiQl; 

public void Configure(
	IApplicationBuilder app, 
	IWebHostEnvironment env, 
	ILoggerFactory loggerFactory
)
{
	 loggerFactory.AddFile("C:/Temp/logs/myapp-{Date}.txt");
	 if (env.IsDevelopment())
	 {
		app.UseDeveloperExceptionPage();
	 }
	 app.UseCors(options =>
	 {
		options.AllowAnyOrigin();
		options.AllowAnyMethod();
		options.AllowAnyHeader();
	 });

	 app.UseGraphiQl("/graphql");   //Add Configuration 
	 app.UseRouting();
	 app.UseAuthorization();
	 app.UseEndpoints(endpoints =>
	 {
		endpoints.MapControllers();
	 });
}
```

no Controller:

Base:

```csharp
using Newtonsoft.Json.Linq;
namespace QL.Support
{
  public sealed class GraphQLQuery
  {
    public string OperationName { get; set; }
    public string NamedQuery { get; set; }
    public string Query { get; set; }
    public JObject Variables { get; set; }
  }
}
```
#

```csharp
public async Task<IActionResult> Post([FromBody]GraphQLQuery query)
{
	try
	{
		Inputs inputs = query.Variables.ToInputs();
		ExecutionResult result = null;
		using (Schema schema = new Schema())
		{
		   schema.Query = new QueryTypes(DatabaseAccess);
		   void options(ExecutionOptions x)
		   {
			  x.Schema = schema;
			  x.Query = query.Query;
			  x.OperationName = query.OperationName;
			  x.Inputs = inputs;
		   }
		   DocumentExecuter documentExecuter = new DocumentExecuter();
		   result = await documentExecuter.ExecuteAsync(options);
		   if (result?.Errors?.Count > 0)
		   {
			  return BadRequest(result.Errors);
		   }
		}
		return Ok(result?.Data);
	}
	catch (System.Exception ex)
	{
		return BadRequest(ex);
	}
}
```

Code Example: https://github.com/graphql-dotnet/examples/tree/master/src/AspNetCoreCustom


Everything is in the package documentation.

A valid point, it does not arrive at the controller. Only comes when you take variables

**Comment by joemcbride** [comment] 2019-11-30 17:45
@fulviocanducci just in case you aren’t aware, I was the one that wrote those docs and the example.  So no, you’re not using that example code.  That example code uses middleware.  You wrote a MVC controller.  Your project is also using .NET Core 3.0 and the examples are still in 2.2.

Have you configured your project to use JSON.NET as described here?

https://stackoverflow.com/a/58020971/279764

Once you do that, you will also have to enable `AllowSynchronousIO`, as described here: #1116

This project does not yet support System.Text.Json.

Your controller is also not using `IDocumentWriter`, so it is not returning results according to the GraphQL spec.

**Comment by fulviocanducci** [comment] 2019-11-30 17:55
@


> Have you configured your project to use JSON.NET as described here?
> 
> https://stackoverflow.com/a/58020971/279764
> 
> Once you do that, you will also have to enable `AllowSynchronousIO`, as described here: #1116
> 
> This project does not yet support System.Text.Json.
> 
> Your controller is also not using `IDocumentWriter`, so it is not returning results according to the GraphQL spec.

I'm not using JSON.NET.

**Comment by fulviocanducci** [comment] 2019-11-30 18:01
> just in case you aren’t aware, I was the one that wrote those docs and the example. So no, you’re not using that example code. That example code uses middleware. You wrote a MVC controller. Your project is also using .NET Core 3.0 and the examples are still in 2.2.
> 
> Have you configured your project to use JSON.NET as described here?


It's the same as middleware, and if it didn't work it wouldn't return that:

![sbddd](https://user-images.githubusercontent.com/25593291/69904145-ef04ce80-1381-11ea-9d78-6fa5f61defa4.png)


If you had problem would not return the information!
![retorno](https://user-images.githubusercontent.com/25593291/69904158-13f94180-1382-11ea-9287-b77cb969b643.png)

What you in a middlweare I did in a controller is the same.

But, okay, I won't question it anymore.

**Comment by joemcbride** [comment] 2019-11-30 19:21
> What you in a middlweare I did in a controller is the same.

No, it’s not the same, and we have been trying to help you fix it.  We can’t help you if you don’t want to be helped.

Closing as this is not a problem with this project.

**Closed by joemcbride** 2019-11-30 19:21 UTC

**Comment by GrangerAts** [comment] 2020-03-11 18:49
@fulviocanducci - Like @joemcbride  and @sungam3r mentioned earlier, Gql.Net is not having the problem. The problem is with the Controller's model binder. You're using a .Net Core 3.x project, which uses Micrsoft's System.Text.Json by default instead of Newtonsoft. It can't deserialize a `JObject` (and it also can't serialize Gql.Net's `ExecutionResult`).

A quick/simple way to confirm this is to change your controller from this:
```
public async Task<IActionResult> Post([FromBody]GraphQLQuery query)
{
	// original code...
}
```
to this:
```
public async Task<IActionResult> Post([FromBody] System.Text.Json.JsonElement rawQuery)
{
	string rawJson = rawQuery.ToString();
	var query = JsonConvert.DeserializeObject<GraphQLQuery>(rawJson);
	// original code...
}
```

**Comment by sungam3r** [comment] 2020-03-11 20:42
Now both GraphQL-dotnet and server projects have System.Text.Json support. Serialization/deserialization parts were moved to external packages. See readme here and in the server project.

**Comment by AhmedKhalil777** [comment] 2020-07-28 00:26
> @fulviocanducci - Like @joemcbride and @sungam3r mentioned earlier, Gql.Net is not having the problem. The problem is with the Controller's model binder. You're using a .Net Core 3.x project, which uses Micrsoft's System.Text.Json by default instead of Newtonsoft. It can't deserialize a `JObject` (and it also can't serialize Gql.Net's `ExecutionResult`).
> 
> A quick/simple way to confirm this is to change your controller from this:
> 
> ```
> public async Task<IActionResult> Post([FromBody]GraphQLQuery query)
> {
> 	// original code...
> }
> ```
> 
> to this:
> 
> ```
> public async Task<IActionResult> Post([FromBody] System.Text.Json.JsonElement rawQuery)
> {
> 	string rawJson = rawQuery.ToString();
> 	var query = JsonConvert.DeserializeObject<GraphQLQuery>(rawJson);
> 	// original code...
> }
> ```

# This is the best solution to this Issue Thanks, but is there are a way to handle the coming query as an strongly typed object

**Comment by sungam3r** [comment] 2020-07-28 14:41
This question is not specific to this project, it is better to ask the authors of System.Text.Json serializer.

**Comment by ovidiubuligan** [comment] 2022-03-10 20:18
@fulviocanducci  can you tell us what approach did you use to add the traceId alongside the errors ?

**Comment by Shane32** [comment] 2022-03-11 23:43
I suggest reading https://graphql-dotnet.github.io/docs/guides/serialization/#error-serialization if you want to customize serialization of errors.
