### ISSUE TITLE
How to get sub table when changing Foreign Key

### ISSUE THREAD

**Issue by ryanlaclaire** [graphql-dotnet/graphql-dotnet#1751] opened 2020-07-30 21:32 UTC
I am running into an issue where when I update a Foreign Key on one table and try to get the new information back I get null.

To keep it simple, I have two tables  Show and Contact. Every show has a contact assigned to it. The problem comes when I run a mutation to change the FK of Contact. The mutation runs and updates the DB, but the returned data shows Contact as null. However the contactId is changed correctly and comes back just fine.

Here is my query:
query ($id: ID!) {
  csw12 (id: $id) {
    id
    onsiteContact
    contactId
    contact {
      id
      contactHat
      firstName
      lastName
      active
      cellPhone
      officePhone
      fax
      email
      notes
    }
  }
}
My GraphQL mutation is nearly identical. 
I update the contactId and if I reload my page, I get the correct data, but initially I get back null. I need the updated information for updating my store in Angular. I am using Apollo with  Angular 8 on the front end. .Net Core 2.2 for the server with GraphQL 2.4 and SQL Server for the DB. 

Does anyone know what I am doing wrong?

**Comment by sungam3r** [comment] 2020-07-31 15:48
Please try the latest 3.0.0 preview first.

**Comment by ryanlaclaire** [comment] 2020-07-31 19:45
@sungam3r  I am unable to fully upgrade to the latest 3.0. I can only upgrade to preview 1141 before I start getting other errors. 

For some reason I am asked to accept these below, but the whole thing crashes and I have to revert to 1141.

![image](https://user-images.githubusercontent.com/43187889/89071025-f8489f80-d343-11ea-9f5d-681e6dd4766c.png)

**Comment by sungam3r** [comment] 2020-07-31 20:31
Yes, 3.0.0 has breaking changes. Nevertheless, from your description I can conclude that the problem is somewhere on your side. GraphQL has nothing to do with databases, only you decide from where and what data to receive. If any of your fields are null, then you need to look at what the server gives in this field. That's all that can be answered according to your description.

**Comment by ryanlaclaire** [comment] 2020-08-03 13:48
@sungam3r . I realized I wasn't making myself completely clear. When I first open the page I get a full contact. Everything is initially correct, so I get all of the data from the database. When I go to update the FK is when the problem occurs. I change it, and I know it changes in the database as I get back the correct ContactId FK. What I don't get back is the updated contact object. That part comes back null. If I refresh the page, the new contact shows up correctly. That's the point which is hanging me up.

**Comment by sungam3r** [comment] 2020-08-03 16:45
I do not know how I can help you with this description without even a minimal example that reproduces the problem.

**Comment by sungam3r** [comment] 2020-08-16 14:15
I am closing this issue because it appears to be unrelated to this repository.

**Closed by sungam3r** 2020-08-16 14:15 UTC
Labels: question
