### ISSUE TITLE
DocumentExecuter should raise error if operation not specified and request contains more than 1 operation

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/graphql-dotnet#3318] opened 2022-09-06 10:00 UTC
Code in `master`:
```
        /// <summary>
        /// Returns the selected <see cref="GraphQLOperationDefinition"/> given a specified <see cref="GraphQLDocument"/> and operation name.
        /// <br/><br/>
        /// Returns <c>null</c> if an operation cannot be found that matches the given criteria.
        /// Returns the first operation from the document if no operation name was specified.
        /// </summary>
        protected virtual GraphQLOperationDefinition? GetOperation(string? operationName, GraphQLDocument document)
            => document.OperationWithName(operationName);
```
From spec: https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#operation-cannot-be-determined

Either `OperationWithName` from parser project or `GetOperation` from this repo should be changed to comply the spec.

**Comment by Shane32** [comment] 2022-09-06 11:24
It already does so. The null response is an error condition and the executer returns an error condition and the server returns a 400 status code.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Execution/DocumentExecuter.cs#L119

**Comment by sungam3r** [comment] 2022-09-19 14:22
Really? From https://spec.graphql.org/draft/#GetOperation():
![изображение](https://user-images.githubusercontent.com/21261007/191039690-06dd9066-2819-4f3e-a5ad-b6cc71996be7.png)

`document.OperationWithName(operationName);` returns first operation available.

**Comment by Shane32** [comment] 2022-09-19 14:52
Makes sense.  I recommend clarifying the specific inconsistency in your issue title or description.

**Comment by Shane32** [comment] 2022-09-19 14:58
I recommend moving this issue to the parser project, and treating it as a bug -- although I understand it could be fixed here, and objectionably is a GraphQL.NET bug, not a parser bug.  Also of note this would technically be a breaking change for the parser library, not a bug -- but I would treat it as a bug, and so just have a minor version bump within the parser library.

**Comment by sungam3r** [comment] 2022-09-19 23:50
I don't decide yet how I would like to treat it - bug of parser or main project.

**Comment by Shane32** [comment] 2024-01-01 20:22
Better handling of error responses by fixing this in GraphQL.NET

**Closed** 2024-01-02 13:32 UTC
Labels: spec compliance
