### ISSUE TITLE
Generic Type Is Generated Only Once Per Schema - Resulting into having Incorrect Return Types for Fields

### ISSUE THREAD

**Issue by JakubSlonka** [graphql-dotnet/graphql-dotnet#2279] opened 2021-02-12 11:18 UTC
## Description

While using generic types in your queries/mutations, they appear only once per schema. During schema generation, only last occurrence of the generic type is kept with its underlying type, other occurences are ignored (overwritten) resulting in incorrect schema types.

The issue can be reproduced when using any of the graphql UI.

Voyager
GraphqiQl
GraphQlPlayground
Altair

### Steps to reproduce

Create Graphql Generic type 
```
 public class GeneralRequestResponseType<T, TType> : ObjectGraphType<GeneralRequestResponse<T>>
    {
        public GeneralRequestResponseType()
        {
            Name = "GenericRequestResponse";
            Field(name: "Data", type: typeof(TType), resolve: context => context.Source.Data);
            Field(name: "Messages", type: typeof(ListGraphType<StringGraphType>), resolve: context => context.Source.Messages);
        }
    }
```

Create Multiple Object Graph Types from DTOs

```
public class SomeDtoType: ObjectGraphType<SomeDto>
    {
        public SomeDtoType()
        {
            Field(x => x.Id);
            Field(x => x.SomeProperty);
        }
}

public class SomeOtherDtoType: ObjectGraphType<SomeOtherDto>
    {
        public SomeOtherDtoType()
        {
            Field(x => x.Id);
            Field(x => x.SomeOtherProperty);
        }
}
```

Use Generic Type with Multiple Graph Types In Your Query/Mutation

```
FieldAsync<GeneralRequestResponseType<SomeDto, SomeDtoType>>(
                "someDto",
                resolve: async context => await resolve);

FieldAsync<GeneralRequestResponseType<SomeOtherDto, SomeOtherDtoType>>(
                "someOtherDto",
                resolve: async context => await resolve);
```

Run Project and Access UI endpoint
See Queries and its types

### Expected result

For each field using generic type there should be generic object graph type with correct underlying object graph type

### Actual result

All fields have the same generic object graph type ( type from last occurance during generation / not respecting actual type)

### Additional Info:
This behaviour breaks all of the UIs and makes them useless for projects using GenericTypes.

I have checked the schema in GrapQlHttpMiddleware and the schema is already generated with incorrect types.

I have tracked the issue and it indeed occurs during schema type generation.

When generating _lookUp table for types, there is Union method used, which filters out duplicities. 

This is causing the issue since it does not check for underlying types and filters all generic types out, leaving us with only one occurrence.

```
 private GraphTypesLookup CreateTypesLookup()
        {
            var types = _additionalInstances
                .Union(GetRootTypes())
                .Union(_additionalTypes.Select(type => (IGraphType)_services.GetRequiredService(type.GetNamedType())));

            return GraphTypesLookup.Create(
                types,
                _directives,
                type => (IGraphType)_services.GetRequiredService(type),
                NameConverter,
                seal: true);
        }
```

this could be fixed by using Union comparer to keep generic types with different underlying types in the collection.

Unfortunately I dont know if there is any special reason for removing duplicit types, other than keeping the types collection clean. 

At this point I would need a help from the maintainers to give me a feedback.

Thanks Jakub.

**Comment by Shane32** [comment] 2021-02-12 13:45
Each schema can only have one type definition for a given type name. This is necessary, for example, so that an introspection query can return the proper type information in response to a request for a certain type name. Or so the exact type is known when an variable is parsed. 

Your solution is simple. Dynamically generate the “Name” property based on the name of the generic type. For example:

`Name = “GenericMessage” + typeof(T).Name + typeof(TType).Name;`

**Comment by Shane32** [comment] 2021-02-12 14:47
@sungam3r This scenario should throw an exception during schema initialization.

**Comment by JakubSlonka** [comment] 2021-02-12 17:20
> Each schema can only have one type definition for a given type name. This is necessary, for example, so that an introspection query can return the proper type information in response to a request for a certain type name. Or so the exact type is known when an variable is parsed.
> 
> Your solution is simple. Dynamically generate the “Name” property based on the name of the generic type. For example:
> 
> `Name = “GenericMessage” + typeof(T).Name + typeof(TType).Name;`

Thanks. This workaround works pretty well. 

Anyway, it would be nice if the mentioned scenario throws exception or if the name of the generic types are automatically generated with underlying types separated by underscore (e.g. GenericType_SomeType)

**Comment by Shane32** [comment] 2021-02-12 17:40
That’s an interesting idea - but when a generic type is registered via dependency injection, I don’t think graphql can tell that it was a generic registration and therefor to add the type suffix on it.

**Comment by Shane32** [comment] 2021-02-12 17:43
FYI for connection types, we generate type names in the following manner:

https://github.com/graphql-dotnet/graphql-dotnet/blob/5b217bc2e0ca1fd1ff70536f40f71899815bf219/src/GraphQL/Types/Relay/ConnectionType.cs#L19

**Comment by Shane32** [comment] 2021-02-12 17:47
> You would need to create a special type for `ListGraphType<SomeDtoType>` to aviod the same issue.

`ListGraphType` and `NonNullGraphType` are special cases - they are more like metadata (indicating that a field must be non-null, for instance) than an actual type.  They do not need or have names.

**Comment by JakubSlonka** [comment] 2021-02-12 18:41
In cases like this 

```
FieldAsync<GeneralRequestResponseType<IEnumerable<SomeDto>, ListGraphType<SomeDtoType>>>(
                "someQuery",
                resolve: async context => await resolve);
```
you need to make a wrapper type with a name for `ListGraphType<SomeDtoType>`, without a wrapper type the autogenerated name is following ```(GenericRequestResponseType_ListGraphType`1)``` and is causing failure in the UI

**Comment by sungam3r** [comment] 2021-02-13 00:19
> This scenario should throw an exception during schema initialization.

Of course.

**Comment by sungam3r** [comment] 2021-02-14 23:53
@JakubSlonka Could you please make a PR with a test showing an error?

**Comment by Shane32** [comment] 2021-02-23 16:35
@sungam3r I tried to write a test but it passes both in `master` and `develop`.  I guess I'm not sure what the problem is we are trying to solve.

**Comment by sungam3r** [comment] 2021-02-23 17:17
I suggest to close it till @JakubSlonka provides additional info.

**Comment by Shane32** [comment] 2021-02-23 17:34
@JakubSlonka I have created a test which demonstrates that an error is correctly thrown during schema initialization when duplicate type names are present.  The test already passes on GraphQL.NET v3.3.2 and v4.0.  If you can update the sample to demonstrate the issue you were experiencing, we can continue investigation.  Thanks!

```cs
using System;
using GraphQL.Types;
using Shouldly;
using Xunit;

namespace GraphQL.Tests.Bugs
{
    // https://github.com/graphql-dotnet/graphql-dotnet/issues/2279
    public class Bug2279DuplicateType : QueryTestBase<Bug2279Schema>
    {
        [Fact]
        public void NoDuplicateTypeNames()
        {
            var s = new Bug2279Schema();
            var e = Should.Throw<InvalidOperationException>(() => s.Initialize());
            e.Message.ShouldBe("Unable to register GraphType 'GraphQL.Tests.Bugs.Bug2279GraphType`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' with the name 'Bug2279GraphType_1';" + Environment.NewLine + "the name 'Bug2279GraphType_1' is already registered to 'GraphQL.Tests.Bugs.Bug2279GraphType`1[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.");
        }
    }

    public class Bug2279Schema : Schema
    {
        public Bug2279Schema()
        {
            Query = new Bug2279Query();
        }
    }

    public class Bug2279Query : ObjectGraphType
    {
        public Bug2279Query()
        {
            Field<Bug2279GraphType<string>>(
                "string",
                resolve: ctx => "hello");
            Field<Bug2279GraphType<int>>(
                "int",
                resolve: ctx => 3);
        }
    }

    public class Bug2279GraphType<T> : ObjectGraphType<T>
    {
        public Bug2279GraphType()
        {
            if (typeof(T) == typeof(int))
            {
                Field<IntGraphType, T>().Name("value").Resolve(x => x.Source);
            }
            else
            {
                Field<StringGraphType, T>().Name("value").Resolve(x => x.Source);
            }
        }
    }
}
```

**Closed by Shane32** 2021-02-23 17:34 UTC
