### ISSUE TITLE
GraphQL authorization

### ISSUE THREAD

**Issue by olegBryukhanov** [graphql-dotnet/graphql-dotnet#502] opened 2017-12-15 09:34 UTC
Hello. I can not resolve GraphQLUserContext class and fieldDef.RequiresPermissions and fieldDef.CanAccess methods.
Errors
```
The type or namespace name 'GraphQLUserContext' could not be found (are you missing a using directive or an assembly reference?) 
```
```
'FieldType' does not contain a definition for 'RequiresPermissions' and no extension method 'RequiresPermissions' accepting a first argument of type 'FieldType' could be found (are you missing a using directive or an assembly reference?)

```
```
'FieldType' does not contain a definition for 'CanAccess' and no extension method 'CanAccess' accepting a first argument of type 'FieldType' could be found (are you missing a using directive or an assembly reference?)
```

And where can i find an example project with Authorization ?
Thank you.
Version 2.0.0-alpha-817, .net core 2 project. 

```csharp
    public class RequiresAuthValidationRule : IValidationRule
    {
        public INodeVisitor Validate(ValidationContext context)
        {
            var userContext = context.UserContext.As<GraphQLUserContext>();
            var authenticated = userContext.User?.IsAuthenticated() ?? false;

            return new EnterLeaveListener(_ =>
            {
                _.Match<Operation>(op =>
                {
                    if (op.OperationType == OperationType.Mutation && !authenticated)
                    {
                        context.ReportError(new ValidationError(
                            context.OriginalQuery,
                            "auth-required",
                            $"Authorization is required to access {op.Name}.",
                            op));
                    }
                });

            // this could leak info about hidden fields in error messages
            // it would be better to implement a filter on the schema so it
            // acts as if they just don't exist vs. an auth denied error
            // - filtering the schema is not currently supported
            _.Match<Field>(fieldAst =>
                {
                    var fieldDef = context.TypeInfo.GetFieldDef();
                    if (fieldDef.RequiresPermissions() &&
                        (!authenticated || !fieldDef.CanAccess(userContext.User.Claims)))
                    {
                        context.ReportError(new ValidationError(
                            context.OriginalQuery,
                            "auth-required",
                            $"You are not authorized to run this query.",
                            fieldAst));
                    }
                });
            });
        }
    }
```

**Comment by joemcbride** [comment] 2017-12-15 15:31
Those extension methods are not in the project.  If you scroll a bit further down in the docs they are listed there:

http://graphql-dotnet.github.io/graphql-dotnet/learn#permission-extension-methods

That said, I have created a different project with some updated Authorization techniques uses permissions, similar to what is found in ASP.NET Core.  That doesn't have an example/docs but I can provide one later today.  https://github.com/graphql-dotnet/authorization

**Comment by olegBryukhanov** [comment] 2017-12-15 16:45
>  I can provide one later today

It would be cool! Thank you a lot!

**Comment by olegBryukhanov** [comment] 2017-12-20 08:23
@joemcbride https://github.com/graphql-dotnet/authorization Does this project contain an example of graphql authorization? Just i did not find this.

**Comment by joemcbride** [comment] 2017-12-20 20:13
@olegBryukhanov My apollogies though I wasn't able to get a sample fully updated to use Auth.  Here is an outline of what it may look like.

Key elements:

* Register the authorization classes in your container (`IAuthorizationEvaluator`, `AuthorizationSettings`, and the `AuthorizationValidationRule`).
* Provide a `UserContext` class that implements `IProvideClaimsPrincipal`.
* Add policies to the `AuthorizationSettings`.
* Apply a policy to a GraphType or Field (which implement `IProvideMetadata`).
* The `AuthorizationValidationRule` will run and verify the policies based on the registered policies.
* You can write your own `IAuthorizationRequirement`.

```csharp
public static void AddGraphQL(this IServiceCollection services)
{
    services.TryAddSingleton<IAuthorizationEvaluator, AuthorizationEvaluator>();

    services.TryAddSingleton(s =>
    {
        var authSettings = new AuthorizationSettings();

        authSettings.AddPolicy("AdminPolicy", _ => _.RequireClaim("role", "Admin"));

        return authSettings;
    });

    services.AddTransient<IValidationRule>(s => new AuthorizationValidationRule(s.GetRequiredService<IAuthorizationEvaluator>()));
}


public static void AddGraphQL(this IApplicationBuilder app)
{
    var settings = new GraphQLSettings
    {
        BuildUserContext = async ctx =>
        {
            var principalProvider = app.ApplicationServices.GetService<IPrincipalProvider>();
            var principal = await principalProvider.Principal();

            var userContext = new GraphQLUserContext
            {
                User = principal
            };
            return userContext;
        }
    };

    var rules = app.ApplicationServices.GetServices<IValidationRule>();
    settings.ValidationRules.AddRange(rules);

    app.UseMiddleware<GraphQLMiddleware>(settings);
}

public class GraphQLUserContext : IProvideClaimsPrincipal
{
    public ClaimsPrincipal User { get; set; }
}

public class GraphQLSettings
{
    public Func<HttpContext, Task<object>> BuildUserContext { get; set; }
    public object Root { get; set; }
    public IList<IValidationRule> ValidationRules { get; } = new List<IValidationRule>();
}

public class MyType : ObjectGraphType
{
    public MyType()
    {
        AuthorizeWith("AdminPolicy");
    }
}
```

**Comment by olegBryukhanov** [comment] 2017-12-21 10:10
@joemcbride Thank you for an example! But i can not find whence is IPrincipalProvider inherited?

**Comment by joemcbride** [comment] 2017-12-21 15:00
It is just a wrapper around HttpContext.User.

**Comment by joemcbride** [comment] 2017-12-21 15:00
You can use IHttpContextAccessor.

**Comment by olegBryukhanov** [comment] 2017-12-25 04:30
@joemcbride I tried to tune my configuration for authorization with the help of your guide but it did not work. My code.
Register the authorization classes
```csharp
        public static void AddGraphQL(this IServiceCollection services)
        {
            services.TryAddSingleton<IAuthorizationEvaluator, AuthorizationEvaluator>();

            services.TryAddSingleton(s =>
            {
                var authSettings = new AuthorizationSettings();

                authSettings.AddPolicy("AdminPolicy", _ => _.RequireClaim("role", "Admin"));

                return authSettings;
            });

            services.AddTransient<IValidationRule>(s => new AuthorizationValidationRule(s.GetRequiredService<IAuthorizationEvaluator>()));
        }
```
Sent GraphQLSettings to my GraphQlMiddleware
```csharp
        public static IApplicationBuilder UseGraphQl(this IApplicationBuilder builder)
        {
            var settings = new GraphQLSettings
            {
                BuildUserContext = async ctx =>
                {
                    var principalProvider = builder.ApplicationServices.GetService<IHttpContextAccessor>();
                    var principal = principalProvider.HttpContext.User;

                    var userContext = new GraphQLUserContext
                    {
                        User = principal
                    };
                    return Task.FromResult(userContext);
                }
            };

            var rules = builder.ApplicationServices.GetServices<IValidationRule>();
            settings.ValidationRules.AddRange(rules);            

            return builder.UseMiddleware<GraphQlMiddleware>(settings);
        }
```
GraphQlMiddleware's code
GraphQLSettings inject from constructor and Settings.ValidationRules send to ExecutionOptions ValidationRules, Settings.BuildUserContext to UserContext in ExecutionOptions.
```csharp
    public class GraphQlMiddleware
    {
        private RequestDelegate Next { get; }
        private ISchema Schema { get; }
        private GraphQLSettings Settings { get; }
        public GraphQlMiddleware(RequestDelegate next, ISchema schema, GraphQLSettings settings)
        {
            Next = next;
            Schema = schema;
            Settings = settings;
        }

        public async Task Invoke(HttpContext httpContext, IDocumentExecuter documentExecuter)
        {
            var sent = false;
            if (httpContext.Request.Path.StartsWithSegments("/graph"))
            {
                using (var sr = new StreamReader(httpContext.Request.Body))
                {
                    var query = await sr.ReadToEndAsync();

                    if (!String.IsNullOrWhiteSpace(query))
                    {
                        var request = JsonConvert.DeserializeObject<GraphQLDto>(query);

                        var executionOptions = new ExecutionOptions
                        {
                            Schema = Schema,
                            Query = request.Query,
                            OperationName = request.OperationName,
                            Inputs = request.Variables != null ? JsonConvert.SerializeObject(request.Variables).ToInputs() : null,
                            ValidationRules = Settings.ValidationRules,
                            UserContext = Settings.BuildUserContext
                        };


                        try
                        {
                            var result = await documentExecuter.ExecuteAsync(executionOptions).ConfigureAwait(false);
                            if (result.Errors?.Count > 0)
                            {
                                var errors = WriteErrors(result);

                                await WriteResult(httpContext, new ExecutionResult
                                {
                                    Errors = errors
                                },
                                400);
                            }
                            else
                            {
                                await WriteResult(httpContext, result, 200);
                            }

                        }
                        catch (Exception ex)
                        {
                            await WriteResult(httpContext, new ExecutionResult
                            {
                                Errors = new ExecutionErrors() { new ExecutionError(ex.Message, ex.InnerException) }
                            },
                            400);
                        }

                        sent = true;
                    }
                }
            }
            if (!sent)
            {
                await Next(httpContext);
            }
        }

        private async Task WriteResult(HttpContext httpContext, ExecutionResult result, int statusCode)
        {
            var json = new DocumentWriter(indent: true).Write(result);

            httpContext.Response.StatusCode = statusCode;
            httpContext.Response.ContentType = "application/json";
            await httpContext.Response.WriteAsync(json);
        }

        private ExecutionErrors WriteErrors(ExecutionResult result)
        {
            var errors = new ExecutionErrors();
            foreach (var error in result.Errors)
            {
                var ex = new ExecutionError(error.Message);
                if (error.InnerException != null)
                {
                    ex = new ExecutionError(error.Message, error.InnerException);
                }
                errors.Add(ex);
            }

            return errors;
        }
    }
```
Startup.cs
```csharp
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseCors("DefaultPolicy");
            app.UseAuthentication();
            app.UseGraphQl();
            app.UseMvc();
        }
```

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            ...........
            services.AddMvc();
            services.AddGraphQL();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddTransient<IAccountService, AccountService>();
            services.AddTransient<IRedisService, RedisService>();
            services.AddTransient<IUserService, UserService>();
            services.AddTransient<IRoleService, RoleService>();
            services.AddTransient<IDictionaryService, DictionaryService>();
            services.AddTransient<IWordService, WordService>();
            services.AddTransient<IConnectionFactory, ConnectionFactory>();
            services.AddTransient(typeof(IRepository<>), typeof(GenericRepository<>));
            services.AddSingleton<ErrorType>();
            services.AddSingleton<RoleType>();
            services.AddSingleton<UserType>();
            services.AddSingleton<LoginType>();
            services.AddSingleton<DictionaryType>();
            services.AddSingleton<WordType>();
            services.AddSingleton<TranslationType>();
            services.AddSingleton<LoginUserInput>();
            services.AddSingleton<DictionaryInput>();
            services.AddSingleton<WordInput>();
            services.AddSingleton<UserInputType>();
            services.AddSingleton<RegisterUserInput>();
            services.AddSingleton<GraphQLQuery>();
            services.AddSingleton<GraphQLMutation>();
            services.AddScoped<IDocumentExecuter, DocumentExecuter>();
            services.AddAutoMapper();
            services.AddSingleton<ISchema>(
                s => new GraphQLSchema(new FuncDependencyResolver(type => (GraphType)s.GetService(type))));
        }
```
I used this.AuthorizeWith("AdminPolicy"); but if I'm noy authorized, GraphQl still returns result from db,  doesnt return "not authorized" exception.
```csharp
    public class DictionaryType : ObjectGraphType<DictionaryView>
    {
        public DictionaryType(IWordService service)
        {
            this.AuthorizeWith("AdminPolicy");
            Field(x => x.Id, nullable: true, type: typeof(IdGraphType)).Description("Dictionary id");
            Field(x => x.UserId, nullable: true, type: typeof(IdGraphType)).Description("User id");
            Field(x => x.Name, nullable: true, type: typeof(StringGraphType)).Description("Name of dictionary");
            FieldAsync<ListGraphType<WordType>>(
                "words",
                resolve: async context =>
                {
                    return await service.GetListAsync(context.Source.Id);
                }
            );
        }
    }
```
Can you take a look at my code and suggest where there might be an error?

**Comment by joemcbride** [comment] 2017-12-29 06:17
BuildUserContext is a function that needs to be invoked.  Your middleware is just assigning the func to the UserContext instead of invoking the function and assigning the created GraphQLUserContext class.

**Comment by olegBryukhanov** [comment] 2017-12-29 10:58
@joemcbride I did what you said and it is working now, thank you!
And i have a question, if i want to protect my type should i call .AuthorizeWith("Policy") at each field?  If i dont want to protect field do i just not call AuthorizeWith("Policy") at field? Is there no way to protect  all type by one attribute or method?

```csharp
    public class DictionaryType : ObjectGraphType<DictionaryView>
    {
        public DictionaryType(IWordService service)
        {
            this.AuthorizeWith("AdminPolicy");
            Field(x => x.Id, nullable: true, type: typeof(IdGraphType)).Description("Dictionary id");
            Field(x => x.UserId, nullable: true, type: typeof(IdGraphType)).Description("User id").AuthorizeWith("AdminPolicy");
            Field(x => x.Name, nullable: true, type: typeof(StringGraphType)).Description("Name of dictionary").AuthorizeWith("AdminPolicy");
            FieldAsync<ListGraphType<WordType>>(
                "words",
                resolve: async context =>
                {
                    return await service.GetListAsync(context.Source.Id);
                }
            ).AuthorizeWith("AdminPolicy");
        }
    }
```

**Comment by joemcbride** [comment] 2017-12-29 14:32
Calling AuthorizeWith in the constructor applies the policy to the whole Type, which you then would not need to apply to each field.  If you have some fields you want to not apply the policy to, then you would need to not add it to the Type and add it to only the fields you want it applied to.

**Comment by olegBryukhanov** [comment] 2017-12-29 16:02
@joemcbride then ```this.AuthorizeWith("AdminPolicy");``` doesnt work. I set it in my constructor and tried to send request without authorization and did not get 401 Error, i got entity from db. But if set ```AuthorizeWith("AdminPolicy");``` for each field then i get 401 if I throw not authorized request.

An example with ```this.AuthorizeWith("AdminPolicy");``` from my code.

```csharp

    public class DictionaryType : ObjectGraphType<DictionaryView>
    {
        public DictionaryType(IWordService service)
        {            
            Field(x => x.Id, nullable: true, type: typeof(IdGraphType)).Description("Dictionary id");
            Field(x => x.UserId, nullable: true, type: typeof(IdGraphType)).Description("User id");
            Field(x => x.Name, nullable: true, type: typeof(StringGraphType)).Description("Name of dictionary");
            FieldAsync<ListGraphType<WordType>>(
                "words",
                resolve: async context =>
                {
                    return await service.GetListAsync(context.Source.Id);
                }
            );
            this.AuthorizeWith("AdminPolicy");
        }
    }

```
That example works, get 401 if is not authorized
```
    public class DictionaryType : ObjectGraphType<DictionaryView>
    {
        public DictionaryType(IWordService service)
        {            
            Field(x => x.Id, nullable: true, type: typeof(IdGraphType)).Description("Dictionary id").AuthorizeWith("AdminPolicy");
            Field(x => x.UserId, nullable: true, type: typeof(IdGraphType)).Description("User id").AuthorizeWith("AdminPolicy");
            Field(x => x.Name, nullable: true, type: typeof(StringGraphType)).Description("Name of dictionary").AuthorizeWith("AdminPolicy");
            FieldAsync<ListGraphType<WordType>>(
                "words",
                resolve: async context =>
                {
                    return await service.GetListAsync(context.Source.Id);
                }
            ).AuthorizeWith("AdminPolicy");
            this.AuthorizeWith("AdminPolicy");
        }
    }
```
queries
```csharp
    public class GraphQLQuery : ObjectGraphType
    {
        public GraphQLQuery(IDictionaryService dictionaryService, IWordService wordService)
        {
            FieldAsync<ListGraphType<DictionaryType>>(
                "dictionaries",
                Name = "Dictionaries",
                arguments: new QueryArguments(new QueryArgument<IdGraphType>() { Name = "userId" }),                
                resolve: async context =>
                {
                    var userId = context.GetArgument<Guid>("userId");
                    var result = await dictionaryService.GetListAsync(userId);
                    return result;                
                }
            );

            FieldAsync<DictionaryType>(
                "dictionary",
                Name = "Dictionary",
                arguments: new QueryArguments(new QueryArgument<IdGraphType>() { Name = "id" }),
                resolve: async context =>
                {
                    var id = context.GetArgument<Guid>("id");
                    var result = await dictionaryService.GetAsync(id);
                    return result; 
                }
            );

        }
    }
```

**Comment by joemcbride** [comment] 2017-12-29 16:14
You’re right - at present the validation rule doesn’t check the Type of the Field that is being returned, only that the current Field being requested is allowed.  Since there are no policies applied to the GraphQLQuery class it allows it.  That should probably be updated to work as you expect.  Mind adding an issue to that project?

**Comment by olegBryukhanov** [comment] 2017-12-29 17:11
@joemcbride I checked, if call ```.AuthorizeWith("AdminPolicy");``` at GraphQLQuery method then it works well, i just did not expect that need call ```.AuthorizeWith("AdminPolicy");```  at GraphQLQuery method.
This example works well, get 401 if not authorized ;)
```csharp
    public class GraphQLQuery : ObjectGraphType
    {
        public GraphQLQuery(IDictionaryService dictionaryService, IWordService wordService)
        {
            FieldAsync<ListGraphType<DictionaryType>>(
                "dictionaries",
                Name = "Dictionaries",
                arguments: new QueryArguments(new QueryArgument<IdGraphType>() { Name = "userId" }),                
                resolve: async context =>
                {
                    var userId = context.GetArgument<Guid>("userId");
                    var result = await dictionaryService.GetListAsync(userId);
                    return result;                
                }
            ).AuthorizeWith("AdminPolicy");
        }
    }
```

> Mind adding an issue to that project? 
It think, it would be better to add issue to [https://github.com/graphql-dotnet/authorization](https://github.com/graphql-dotnet/authorization) project :)

**Comment by sudhabt** [comment] 2018-05-31 10:19
@joemcbride
is there a way to add annotation based authorization, instead adding to every field ?

**Comment by joemcbride** [comment] 2018-05-31 14:46
@sudhabt you can use annotations with the Schema/handler syntax (shown in the Authorization readme).  Using annotations with Type syntax you would only be able to add an annotation to the Type and not fields (not very granular).  Using annotations with Types is not currently supported (due to its limitations).  You could write your own validation rule to support that though.

**Comment by joemcbride** [comment] 2018-07-31 05:57
Closing this as the issue is fixed in the other project.

**Closed by joemcbride** 2018-07-31 05:57 UTC
Labels: discussion, question

**Comment by drowhunter** [comment] 2018-11-19 05:36
This works well, but what would you suggest for this scenario
I have a type with three fields
each field requires a different policy
right now if any of the fields I access fails it throws an error for the whole thing.
What i would like is that any field that doesn't pass the policy just return null or default.

would this require custom field middleware?
