### ISSUE TITLE
Schema-First Mutations and Input Types

### ISSUE THREAD

**Issue by aaron-jaeger** [graphql-dotnet/graphql-dotnet#2477] opened 2021-04-05 17:40 UTC
## Summary
Ahoy! I'm attempting to create a schema-first API, but I am running into issues with mutations. When I run my mutation query:
```GraphQL
mutation createAuthor {
  createAuthor(input: {
    firstName: "Aaron",
    lastName: "Jaeger"
  }) {
    id
    firstName
    lastName
  }
}
```
I receive the following response:
```json
{
  "errors": [
    {
      "message": "Error trying to resolve field 'createAuthor'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createAuthor"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    }
  ],
  "data": {
    "createAuthor": null
  }
}
```

I've scoured the docs, and the best I've seen for mutations is they are created basically the same way as queries are for schema-first, but I've not seen any examples for creating schema-first input types. Can you please provide me some context as to what I'm doing wrong? Thanks!
## Relevant information
```Startup.cs```
```c#
using AuthorManagement.Api.Schemas;
using AuthorManagement.Api.Services;
using GraphQL;
using GraphQL.SystemTextJson;
using GraphQL.Types;
using GraphQL.Utilities.Federation;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace AuthorManagement.Api
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddControllers();

            // GraphQL types
            services
                .AddSingleton<IDocumentWriter, DocumentWriter>()
                .AddSingleton<IDocumentExecuter, DocumentExecuter>()
                .AddSingleton<AnyScalarGraphType>()
                .AddSingleton<ServiceGraphType>()
                .AddSingleton<IAuthorService, AuthorService>()
                .AddSingleton<AuthorQuery>()
                .AddSingleton<AuthorType>()
                .AddSingleton<AuthorInput>()
                .AddSingleton<ISchema>(s =>
                {
                    return Schema.For(@"
                        type Author {
                            id: ID!
                            firstName: String!
                            lastName: String!
                        }

                        input AuthorInput {
                            firstName: String
                            lastName: String
                        }

                        type Query {
                            authors: [Author!]
                            author(id: ID!): Author
                        }

                        type Mutation {
                            createAuthor(input: AuthorInput): Author
                        }
                    ", _ =>
                    {
                        _.ServiceProvider = s;
                        _.Types
                            .Include<AuthorType>();
                        _.Types
                            .Include<AuthorInput>();
                        _.Types
                            .Include<AuthorQuery>();
                        _.Types
                            .Include<AuthorMutation>();
                    });
                })
                .AddGraphQL(_ =>
                {
                    _.EnableMetrics = true;
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseGraphQLPlayground();
        }
    }
}
```

```AuthorInput.cs```
```c#
using GraphQL;

namespace AuthorManagement.Api.Schemas
{
    [GraphQLMetadata("AuthorInput")]
    public class AuthorInput
    {
        public string FirstName;
        public string LastName;
    }
}
```

```AuthorMutation.cs```
```c#
using AuthorManagement.Api.Models;
using AuthorManagement.Api.Services;
using GraphQL;
using System.Threading.Tasks;

namespace AuthorManagement.Api.Schemas
{
    [GraphQLMetadata("Mutation")]
    public class AuthorMutation
    {
        private readonly IAuthorService _service;
        public AuthorMutation(IAuthorService service)
        {
            _service = service;
        }

        [GraphQLMetadata("createAuthor")]
        public Task<Author> AddAuthorAsync(Author author)
        {
            return _service.AddAuthorAsync(author);
        }
    }
}
```

```AuthorService.cs```
```c#
using AuthorManagement.Api.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AuthorManagement.Api.Services
{
    public class AuthorService : IAuthorService
    {
        private readonly List<Author> _authors;

        public AuthorService()
        {
            _authors = new List<Author>
            {
                new Author(new Guid("ca53016d-7b9e-4e57-a432-f2861977e7e7"), "Taro", "Gomi")
            };
        }

        public Author GetAuthorById(Guid id)
        {
            return _authors
                .FirstOrDefault(a => a.Id == id);
        }

        public Task<Author> GetAuthorByIdAsync(Guid id)
        {
            return Task.FromResult(
                _authors
                    .FirstOrDefault(a => a.Id == id));
        }

        public Task<IEnumerable<Author>> GetAuthorsAsync()
        {
            return Task.FromResult(
                _authors
                    .AsEnumerable());
        }

        public Task<Author> AddAuthorAsync(Author author)
        {
            return Task.Run(() => 
            {
                author.Id = Guid.NewGuid();
                _authors.Add(author);
                return author;
            });
        }
    }

    public interface IAuthorService
    {
        Author GetAuthorById(Guid id);
        Task<Author> GetAuthorByIdAsync(Guid id);
        Task<IEnumerable<Author>> GetAuthorsAsync();
        Task<Author> AddAuthorAsync(Author author);
    }
}
```

```Author.cs```
```c#
using System;

namespace AuthorManagement.Api.Models
{
    public class Author
    {
        public Author(Guid id, string firstName, string lastName)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
        }

        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

```AuthorType.cs```
```c#
using AuthorManagement.Api.Models;
using GraphQL;
using System;

namespace AuthorManagement.Api.Schemas
{
    [GraphQLMetadata("Author", IsTypeOf=typeof(Author))]
    public class AuthorType
    {
        public Guid Id(Author author) => author.Id;
        public string FirstName(Author author) => author.FirstName;
        public string LastName(Author author) => author.LastName;
    }
}
```

For what it's worth, when I debug my request in the controller, ```request.Variables``` has ```Count = 0```. I would imagine this should have some variables in it.

```GraphQLController.cs```
```c#
using GraphQL;
using GraphQL.SystemTextJson;
using GraphQL.Types;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Net;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace AuthorManagement.Api.Controllers
{
    public class GraphQLRequest
    {
        public string Query { get; set; }
        public string OperationName { get; set; }
        [JsonConverter(typeof(ObjectDictionaryConverter))]
        public Dictionary<string, object> Variables { get; set; }
    }

    [Route("[controller]")]
    public class GraphQLController : Controller
    {
        private readonly IDocumentExecuter _executer;
        private readonly IDocumentWriter _writer;

        public GraphQLController(IDocumentExecuter executer, IDocumentWriter writer)
        {
            _executer = executer;
            _writer = writer;
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody]GraphQLRequest request, [FromServices]ISchema schema)
        {
            var result = await _executer.ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.OperationName = request.OperationName;
                _.Query = request.Query;
                _.Inputs = request.Variables.ToInputs();
                _.EnableMetrics = true;
            });

            var json = await _writer.WriteToStringAsync(result);

            var httpResult = result.Errors?.Count > 0
                ? HttpStatusCode.BadRequest
                : HttpStatusCode.OK;

            return Content(json, "application/json");
        }
    }
}
```

```AuthorManagement.Api.csproj```
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>8b559486-3562-4370-a474-98f39768f3da</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GraphQL" Version="4.2.0" />
    <PackageReference Include="GraphQL.Server.Core" Version="5.0.1" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.0.1" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.0.1" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="4.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.13" />
    <PackageReference Include="System.Text.Json" Version="5.0.1" />
  </ItemGroup>

</Project>
```
### Environment (if relevant)

Windows 10, Visual Studio 2019 CE

**Comment by aaron-jaeger** [comment] 2021-04-05 17:52
I already made one correction to this by registering my ```AuthorMutation``` class with DI in ```Startup.cs```.

```services.AddSingleton<AuthorMutation>();```

This partially helped. My issue now is my ```AuthorInput``` from the GraphQL query isn't resolving to my ```Author``` object in the Mutation parameter, and throws a null reference exception.

```AuthorMutation.cs```
```c#
using AuthorManagement.Api.Models;
using AuthorManagement.Api.Services;
using GraphQL;
using System.Threading.Tasks;

namespace AuthorManagement.Api.Schemas
{
    [GraphQLMetadata("Mutation")]
    public class AuthorMutation
    {
        private readonly IAuthorService _service;
        public AuthorMutation(IAuthorService service)
        {
            _service = service;
        }

        [GraphQLMetadata("createAuthor")]
        public Task<Author> AddAuthorAsync(Author author)
        {
            return _service.AddAuthorAsync(author);
        }
    }
}
```

```author == null```

**Comment by joemcbride** [comment] 2021-04-06 15:42
```gql
createAuthor(input: AuthorInput): Author
```

You have defined the parameter as `input`.  Schema first matches fields in C# based off of the names defined in the schema.  If you make this change, it should work:

```csharp
[GraphQLMetadata("createAuthor")]
public Task<Author> AddAuthorAsync(Author input)
{
    return _service.AddAuthorAsync(input);
}
```

**Comment by aaron-jaeger** [comment] 2021-04-06 15:59
Thanks for the quick response!

I've made the necessary changes as you've suggested:

```Schema```
```GraphQL
type Author @key(fields: ""id"") {
    id: ID!
    firstName: String!
    lastName: String!
}

input AuthorInput {
    firstName: String
    lastName: String
}

extend type Query {
    authors: [Author!]
    author(id: ID!): Author
}

extend type Mutation {
    createAuthor(input: AuthorInput): Author
}
```

```AuthorMutation.cs```
```c#
using AuthorManagement.Api.Models;
using AuthorManagement.Api.Services;
using GraphQL;
using System;
using System.Threading.Tasks;

namespace AuthorManagement.Api.Schemas
{
    [GraphQLMetadata("Mutation")]
    public class AuthorMutation
    {
        private readonly IAuthorService _service;
        public AuthorMutation(IAuthorService service)
        {
            _service = service;
        }

        [GraphQLMetadata("createAuthor")]
        public Task<Author> AddAuthorAsync(Author input)
        {
            return _service.AddAuthorAsync(input);
        }
    }
}
```

But I am still seeing an erroneous response:
```json
{
  "errors": [
    {
      "message": "Error trying to resolve field 'createAuthor'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createAuthor"
      ],
      "extensions": {
        "code": "ARGUMENT",
        "codes": [
          "ARGUMENT"
        ]
      }
    }
  ],
  "data": {
    "createAuthor": null
  }
}
```

**Comment by aaron-jaeger** [comment] 2021-04-06 16:04
Upon further futzing, I was able to get it to work. I needed to update the parameter type from ```Author``` to ```AuthorInput``` .

Does not work:
```c#
[GraphQLMetadata("createAuthor")]
public Task<Author> AddAuthorAsync(Author input)
{
    return _service.AddAuthorAsync(input);
}
```

Works:
```c#
[GraphQLMetadata("createAuthor")]
public Task<Author> AddAuthorAsync(AuthorInput input)
{
    var author = new Author(Guid.Empty, input.FirstName, input.LastName);
    return _service.AddAuthorAsync(author);
}
```

This doesn't feel as clean as just using the ```Author``` class as now I've had to add an extra line to create a new ```Author``` type.

**Comment by joemcbride** [comment] 2021-04-06 19:25
> Edit: Is this the intended behavior, or should I be able to use the `Author` object as my parameter?

I'm not fully remembering all of the internal code for this, but I would say yes, this is intended behavior by default.  GraphQL is designed to have distinct separate types for Output (Author in this case) and Input (AuthorInput) types.  You could perhaps "trick" the framework by putting a `[GraphQLMetadata("AuthorInput")]` on `Author` and registering it with the Schema.  That may not work if your `Author` class does not have a default constructor, or a constructor that does not include the `Id`, which would not exist on `AuthorInput`.  Worth a shot!

```diff
-_.Types.Include<AuthorInput>();
+_.Types.Include<Author>();
```

```csharp
namespace AuthorManagement.Api.Models
{
    [GraphQLMetadata("AuthorInput")]
    public class Author
    {
        public Author(Guid id, string firstName, string lastName)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
        }

        public Author() {}

        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
```

**Comment by aaron-jaeger** [comment] 2021-04-06 19:41
I've been a big fan of extensions in the past, and probably what I'll do moving forward on this project. Thanks for your quick and helpful feedback. Keep it up!

**Comment by joemcbride** [comment] 2021-04-06 20:10
Welcome!  I'll go ahead and close this issue.

**Closed by joemcbride** 2021-04-06 20:10 UTC
Labels: needs confirmation
