### ISSUE TITLE
(3.0.0-preview-1141) UIntGraphType is not working inside mutation argument.

### ISSUE THREAD

**Issue by WhippetsAintDogs** [graphql-dotnet/graphql-dotnet#1090] opened 2019-03-27 21:39 UTC
## Description

I've tried the 3.0.0-preview-1141, but using a field builder with an expression parameter returning a property with the `uint` type causes this error inside an `InputObjectGraphType<>`: 
```
The GraphQL type for Field: FIELD_NAME on parent type: PARENT_GRAPH_TYPE could not be derived implicitly.
``` 
If I try to specify the type to be `typeof(UIntGraphType)` in the `type` parameter of the field builder, I got this error instead with a numeric or string value (e.g. `10` or `"10"`) passed as an UInt argument: 
```
Argument ARGUMENT_NAME has invalid value {FIELD_NAME: 10 or \"10\"}.\nIn field FIELD_NAME: Expected type \"UInt\", found 10 or \"10\".
```
It works inside `ObjectGraphType<>` (query), but not as input. It seems that the `ParseLiteral` function of the `UIntGraphType` returns `null` when parsing an argument such as `10` or `"10"`. So casting a `StringValue` or a `IntValue` `as UIntValue` returns `null`...

![image](https://user-images.githubusercontent.com/9271409/55171313-7abcc000-514e-11e9-922c-8a84f9342c27.png)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/9271409/55160388-99fd2280-5139-11e9-98bf-04c5dc6676d1.png)

![image](https://user-images.githubusercontent.com/9271409/55160415-ada88900-5139-11e9-822e-f75cb3cec530.png)

Code:

![image](https://user-images.githubusercontent.com/9271409/55160496-d761b000-5139-11e9-8555-4290fe6f41d3.png)

![image](https://user-images.githubusercontent.com/9271409/55160529-ec3e4380-5139-11e9-964d-7871a5baefef.png)

### Actual result

![image](https://user-images.githubusercontent.com/9271409/55113996-2d414400-50b7-11e9-9d36-1496dcd4069f.png)

**Comment by WhippetsAintDogs** [comment] 2019-03-28 14:02
Could it be because there is no `Config<UIntValue/ULongValue/UShortValue>` inside the `AstPrinter` ? (graphql-dotnet/src/GraphQL/Utilities/AstPrinter.cs)

**Comment by WhippetsAintDogs** [comment] 2019-03-28 17:53
Changing the `ParseLiteral` method to:
```
public override object ParseLiteral(IValue value) {
    UIntValue uintValue;

    try {
        uintValue = new UIntValue(Convert.ToUInt32(value.Value));
    } catch {
        uintValue = null;
    }

    return uintValue?.Value;
}
```

fixes the problem. @joemcbride Could you update the preview-1141 with the fix please :) ?

**Comment by joemcbride** [comment] 2019-03-28 18:10
`ParseLiteral` should not be trying to convert the value.  That is what `ParseValue` is for.  In your case, what data type is the raw value?  Any conversions should be registered in `ValueConverter.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ca362c9c15f4d4c724b83a98ededa7e4b306c007/src/GraphQL/Types/UIntGraphType.cs#L18-L19

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/ValueConverter.cs

**Comment by WhippetsAintDogs** [comment] 2019-03-28 18:14
The raw value is a `uint`. But in the GraphQL payload, a numeric argument is parsed into an `astValue` of type `IntValue` which passed to `ParseLiteral` causes the expression `value as UIntValue` to be `null`.

**Comment by WhippetsAintDogs** [comment] 2019-03-29 13:32
Referencing #1091

**Comment by sungam3r** [comment] 2019-03-29 13:38
> Any conversions should be registered in ValueConverter

Yes, but not only that. The problem is that "wrong" `ValueNode` (namely `IntValue`) comes in the `ParseLiteral` method.

The fact is that the .NET primitive numeric types are more diverse than GraphQL types (actually `Int`). In fact, a GraphQL parser consider all integer values as `Int`, but later they must be converted to specific types such UInt/Short/UShort etc.

See #1091

**Comment by sungam3r** [comment] 2019-03-29 13:42
> ParseLiteral should not be trying to convert the value

Why not? See [this] https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/IntGraphType.cs#L41.

There’s exactly the same problem.

Naturally, I do not say that it should be implemented in this way )) :
```c#
 try {
        uintValue = new UIntValue(Convert.ToUInt32(value.Value));
    } catch {
        uintValue = null;
    }
```

**Comment by joemcbride** [comment] 2019-03-29 16:19
> Yes, but not only that. The problem is that "wrong" ValueNode (namely IntValue) comes in the ParseLiteral method.

Exactly.  That is the bug that should be fixed.

> Why not? See this.

Your link to the `IntGraphType` is also not converting/parsing the value in `ParseLiteral`.  It is only checking `IValue` AST (Abstract Syntax Tree) types.  Arguably we should have both an `IntGraphType` and a `LongGraphType`/`Int64GraphType`.

The process:

* Data comes in, gets converted to default JSON.NET values.
* Eventually those values get passed to `AstFromValue`, to convert from the raw value to the AST type.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ca362c9c15f4d4c724b83a98ededa7e4b306c007/src/GraphQL/GraphQLExtensions.cs#L318

* During `AstFromValue`, `ScalarGraphType.Serialize` is called.  This should serialize the value to whatever the output is expected.  Whatever output is expected, should be able to be identified and converted to its associated `IValue` type.  For `UIntGraphType`, `Serialize` should be returning a `uint`, which should get converted to an `UIntValue`.  If that's not happening, that is the bug.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ca362c9c15f4d4c724b83a98ededa7e4b306c007/src/GraphQL/GraphQLExtensions.cs#L375-L383

**Comment by sungam3r** [comment] 2019-03-29 19:12
Ok, i will look from this side.

**Comment by sungam3r** [comment] 2019-03-29 19:29
Honestly, I'm surprised. Control flow does not fall into the `AstFromValue` method. I see that it gets there only if the input values are specified via variables.
![изображение](https://user-images.githubusercontent.com/21261007/55257699-bf8d4780-5271-11e9-853c-842a9eaf58bf.png)
Yes, and from InputValue resolver for `defaultValue` field but this is not our case.

So, what are your suggestions?

**Comment by joemcbride** [comment] 2019-04-05 22:46
Using `3.0.0-preview-1141` I was able to duplicate the `could not be derived implicitly` error in a console app, but not the second one.  I'm not able to duplicate the first error with what is currently in the master branch of the project.  What I am doing here differently than your project?  Can you duplicate the second error with the given code?

```csharp
using System;
using GraphQL;
using GraphQL.Types;

namespace Bug1090
{
    class Program
    {
        static void Main(string[] args)
        {
            var inputs = "{'input': {'id':'E36A8AD5-625D-4950-8CE0-CBB49D2DC35E', 'frequency':10, 'occurrences':10} }".ToInputs();

            var schema = new Bug1090Schema();
            schema.RegisterType<RecurrenceInputType>();
            var result = schema.Execute(_ =>
            {
                _.Query = @"
                    query q($input: RecurrenceInput!) {
                        recurrence(options: $input)
                    }";
                _.Inputs = inputs;
                _.ExposeExceptions = true;
            });

            Console.WriteLine(result);
        }
    }

    public class Recurrence
    {
        public Guid Id { get; set; }
        public uint Frequency { get; set; }
        public uint Occurrences { get; set; }
    }

    public class RecurrenceInputType : InputObjectGraphType<Recurrence>
    {
        public RecurrenceInputType()
        {
            Name = "RecurrenceInput";
            Field("id", x => x.Id, type: typeof(IdGraphType));
            Field("frequency", x => x.Frequency, type: typeof(UIntGraphType));
            Field("occurrences", x => x.Occurrences, type: typeof(UIntGraphType));
        }
    }

    public class Bug1090QueryType : ObjectGraphType
    {
        public Bug1090QueryType()
        {
            Name = "Query";
            Field<StringGraphType>(
                "recurrence",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<RecurrenceInputType>> { Name = "options" }),
                resolve: context =>
                {
                    var options = context.GetArgument<Recurrence>("options");
                    return $"success: {options.Frequency} / {options.Occurrences}";
                });
        }
    }

    public class Bug1090Schema : Schema
    {
        public Bug1090Schema()
        {
            Query = new Bug1090QueryType();
        }
    }
}
```

**Comment by joemcbride** [comment] 2019-04-05 22:59
Okay I was able to duplicate it by switching from the use of variables to an inline object.

So @WhippetsAintDogs the work-around for now would be to use a variable.

```csharp
var schema = new Bug1090Schema();
schema.RegisterType<RecurrenceInputType>();
var result = schema.Execute(_ =>
{
    _.Query = @"
        query q {
            recurrence(options: { id: ""E36A8AD5-625D-4950-8CE0-CBB49D2DC35E"", frequency: 10, occurrences: 10 })
        }";
    _.ExposeExceptions = true;
});

Console.WriteLine(result);
```

**Comment by joemcbride** [comment] 2019-04-05 23:48
Because of the use of the inline object, I don't think there is a way to have it be anything other than an `IntValue` in this case.  The parser has no context of what GraphType is intended and is for the most part stuck with the "vanilla" types.  So indeed the fix would be to update the `UIntGraphType` to work with `IntValue`.  This error is coming from the `ArgumentsOfCorrectType` rule which is trying to validate the correctness of the arguments.

https://github.com/graphql-dotnet/graphql-dotnet/blob/ca362c9c15f4d4c724b83a98ededa7e4b306c007/src/GraphQL/Language/CoreToVanillaConverter.cs#L197-L213

**Comment by WhippetsAintDogs** [comment] 2019-04-06 16:52
@joemcbride Thanks for getting to the bottom of things and for the workaround in the meantime :)

**Comment by sungam3r** [comment] 2019-04-06 20:44
>  The parser has no context of what GraphType is intended and is for the most part stuck with the "vanilla" types. 

Exactly. Let's ask ourselves - is there anything bad in that support will be added to the numeric scalar types for parsing from not only their specific XXXValue, but also from universal `IntValue`? In essence, `IntValue` is only a universal container for transferring numeric value after parsing. It so happens that we are forced to obtain a more specific meaning (.net `byte/short/int/long` and signed variants) from a more general context (`Int` from GraphQL spec). And it seems to me that `ParseLiteral` is a natural place for that.

> So indeed the fix would be to update the `UIntGraphType` to work with `IntValue`. 

I just want to clarify that the described problem is related not only to the `UIntGraphType` - #1091 added support for all numeric scalar types. Thus, is it possible to consider the specified PR not contradicting the design of the library, but as a natural consequence of adapting the general GraphQL specification to .NET world?

**Comment by sungam3r** [comment] 2019-04-08 22:11
@WhippetsAintDogs  #1091 was merged into master, you can try latest prerelease version from myget:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <packageSources>
        <add key="myget-graphql-dotnet" value="https://myget.org/F/graphql-dotnet/api/v3/index.json" />
    </packageSources>
</configuration>
```

**Comment by WhippetsAintDogs** [comment] 2019-04-09 03:07
Thanks @sungam3r ! :)

**Comment by sungam3r** [comment] 2019-05-12 20:06
@WhippetsAintDogs Did you manage to solve your problem?

**Comment by sungam3r** [comment] 2019-10-12 18:59
@WhippetsAintDogs I would appreciate feedback.

**Comment by sungam3r** [comment] 2019-12-02 06:11
Closed as resolved. Feel free to reopen if not.

**Closed by sungam3r** 2019-12-02 06:11 UTC
Labels: needs confirmation
