### ISSUE TITLE
Additional information in the error response

### ISSUE THREAD

**Issue by raphaelvp** [graphql-dotnet/graphql-dotnet#1218] opened 2019-07-12 06:34 UTC
## Summary

Additional information in the error response

## Relevant information

While executing a query, if an error occurs, is there a way to provide additional information in the error message returned from the GraphQL Query execution?

For example, when a non-null field is resolved with a null value, is there a way to specify an identifier of root node in the error response?

**Comment by sgwozdz** [comment] 2019-07-12 13:21
I had to provide some additional information in error responses. What I did to support it, is just response parser after `_documentExecuter.ExecuteAsync`. 
Inside the parser I check what kind of `Exception` were thrown. Correct handler takes the custom exception data I need and put them to `ExtendedExecutionError`, which is just a simple class with `ExecutionError` as base class. On the end I replace original `ExecutionError`.

```
public class ExtendedExecutionError : ExecutionError
    {
        public ExtendedExecutionError(string code, string message)
            : base(message)
        {
            Code = code;
        }
    }
```

**Comment by sungam3r** [comment] 2019-07-18 20:12
@raphaelvp I think that in this case, in a completely natural and simple way, you can use the `Exception.Data` property. GraphQL uses `ExecutionResultJsonConverter` to serialize response. Among other things this converter also writes extended error information that it extracts from exception type and `Data` property.

Having such a code
```c#
 Field<StringGraphType>(
                "myField",
                resolve: ctx =>
                {
                    var ex = new ApplicationException("oops!");
                    ex.Data["b"] = 42;
                    ex.Data["h"] = "dddd";
                    throw ex;
                    return "blablabla";
                });
```
you will get that response
```json
{
  "data": {
    "myField": null
  },
  "errors": [
    {
      "message": "Error trying to resolve myField.",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "myField"
      ],
      "extensions": {
        "code": "APPLICATION",          <------ derived from `exception.GetType()`
        "data": {                                   <------ and here is our extended information
          "b": 42,
          "h": "dddd"
        }
      }
    }
  ]
}
```

Also note that there is no error message _oops!_ in the response. This is done by design. If you want to see the source exception message than use `ExecutionOptions.ExposeExceptions = true` which is `false` by default.

GraphQL client can interpret that information in extensions response section in any way.

Also see #1164 . This change will allow to augment (or even change exception type) any exception.

**Comment by sungam3r** [comment] 2020-02-25 06:44
Closed as resolved.

**Closed by sungam3r** 2020-02-25 06:44 UTC
Labels: question
