### ISSUE TITLE
Decouple core library from JsonNet

### ISSUE THREAD

**Issue by DSilence** [graphql-dotnet/graphql-dotnet#972] opened 2019-01-11 14:22 UTC
## Summary

The core library currently has a dependency on JsonNet, which is used all over the codebase. This prevent other serializers (like Jil, Utf8Json, SpanJson or the upcoming json formatter from .net core 3.0) to be used in place of JsonNet, as requested in https://github.com/graphql-dotnet/graphql-dotnet/issues/959. The JsonNet ingration can then be provided via a separate nuget package.

### Motivation

Will be required for complete replacement of serializer with a different one (https://github.com/graphql-dotnet/graphql-dotnet/issues/959)

**Comment by joemcbride** [comment] 2019-01-11 17:58
> which is used all over the codebase

Just want to point out that this is a bit of a stretch.  It is used in 2 places, once on input to convert from JSON.NET values to .NET Values, and once on output in the DocumentWriter.  There should be no other uses of it (if there are then we failed!), as it was a very purposeful decision to NOT have it used "all over the codebase" to enable this exact request to use a different serializer.

That said, I think there can be work done to create a smarter `DocumentWriter` so you wouldn't have to do so much work to replace it.  You _should_ be able to use another serializer with only those two things in mind.

**Comment by joemcbride** [comment] 2019-01-11 18:04
Going to close this as a duplicate of #959

**Closed by joemcbride** 2019-01-11 18:04 UTC
Labels: duplicate
