### ISSUE TITLE
Byte Array sent through Variables(graphql .net client library) receive invalid_value

### ISSUE THREAD

**Issue by eyaldar** [graphql-dotnet/graphql-dotnet#1874] opened 2020-09-22 13:56 UTC
## Description

Hi, 

I'm trying to create an InputObjectGraphType/ObjectGraphType with a property of byte array.
I'm using Json .NET for serialization.
I'm trying to receive a byte array property to my server query field resolver but it fails with INVALID_VALUE
I'd appreciate your help in understanding what am i doing wrong
Thanks a lot in advance!

### Steps to reproduce

I have this basic setup:
```
   public class BytesHolder
    {
        public byte[] Bytes { get; set; }
    }
```

```
   public class OutputBytesType : ObjectGraphType<BytesHolder>
    {
        public OutputBytesType()
        {
            Field(x => x.Bytes);
        }
    }
```

```
    public class InputBytesType : InputObjectGraphType<BytesHolder>
    {
        public InputBytesType()
        {
            Field(x => x.Bytes);
        }
    }
```

```
   public class DemoQuery : ObjectGraphType
    {
        public DemoQuery()
        {
            Field<OutputBytesType>(
                "bytes",
                arguments: new QueryArguments(new QueryArgument<InputBytesType> { Name = "bytesObject" }),
                resolve: context => 
                {
                    var bytesObject = context.GetArgument<BytesHolder>("bytesObject");
                    return bytesObject;
                }
            );
        }
    }
```

I'm sending this request through a console application client
```
            var bytesRequest = new GraphQLRequest
            {
                Query = @"
                query BytesRequest($bytesHolder: InputBytesType) {
                    bytes(bytesObject: $bytesHolder) {
                        bytes
                    }
                }",
                Variables = new
                {
                    bytesHolder = new BytesHolder
                    {
                        Bytes = new byte[] { 1, 2, 3, 4 }
                    }
                }
            };

            var graphQLResponse = await graphQLClient.SendQueryAsync<BytesHolder>(bytesRequest);
```

Upon receiving the request, the server fails to parse the request (it gets to this line:
```            
Register<string, byte>(value => byte.Parse(value, NumberFormatInfo.InvariantInfo));
```
instead of this line:
```
Register<string, byte[]>(value => Convert.FromBase64String(value)); // such a built-in conversion for string->byte[] seems useful
```

### Expected result

The server should succeed in parsing the byte array property.

### Actual result

The server fails with INVALID_VALUE due to miscalculation in the value converter

### Environment

GraphQL 3.0.0, Windows 10, Asp .NET Core 3.1

**Comment by eyaldar** [comment] 2020-09-23 10:28
After a lot of work I managed to make it work both in playground and through graphql client.
That being said, it is a very ugly workaround that is caused by missing support in Base64 string when using ListGraphType<ByteGraphType> as a property in either ObjectGraphType and InputObjectGraphType.

I'm sharing my workaround here, these are the custom scalar types required:
```
    public class ByteArrayValue: ValueNode<byte[]>, IList
    {
        public ByteArrayValue(byte[] value)
        {
            Value = value;
        }

        public object this[int index] { get => Value[index]; set => Value[index] = (byte)value; }

        public bool IsFixedSize => Value.IsFixedSize;

        public bool IsReadOnly => Value.IsReadOnly;

        public int Count => Value.Length;

        public bool IsSynchronized => Value.IsSynchronized;

        public object SyncRoot => Value.SyncRoot;

        public int Add(object value)
        {
            throw new NotImplementedException();
        }

        public void Clear()
        {
            throw new NotImplementedException();
        }

        public bool Contains(object value)
        {
            return Value.Contains((byte)value);
        }

        public void CopyTo(Array array, int index)
        {
            Value.CopyTo(array, index);
        }

        public IEnumerator GetEnumerator()
        {
            return Value.GetEnumerator();
        }

        public int IndexOf(object value)
        {
            throw new NotImplementedException();
        }

        public void Insert(int index, object value)
        {
            throw new NotImplementedException();
        }

        public void Remove(object value)
        {
            throw new NotImplementedException();
        }

        public void RemoveAt(int index)
        {
            throw new NotImplementedException();
        }

        protected override bool Equals(ValueNode<byte[]> node)
        {
            return node == this || node.Value == this.Value;
        }
    }

    public class ByteArrayValueAstValueConverter : IAstFromValueConverter
    {
        public IValue Convert(object value, IGraphType type)
        {
            if(value is IEnumerable<object> objects) 
            {
                value = objects?.Select(x => System.Convert.ToByte(x)).ToArray();
            }

            return new ByteArrayValue((byte[])value);
        }

        public bool Matches(object value, IGraphType type)
        {
            var objects = value as IEnumerable<object>;
            var results = objects?.Select(x => System.Convert.ToByte(x)).ToArray();
            return (value is IEnumerable<byte>) || (results != null && results.Length > 0);
        }
    }

    public class ByteArrayType : ScalarGraphType
    {
        public ByteArrayType()
        {
            Name = "ByteArray";
        }

        public override object ParseLiteral(IValue value)
        {
            return value;
        }

        public override object ParseValue(object value)
        {
            if(value is string)
            {
                return ValueConverter.ConvertTo(value.ToString(), typeof(byte[]));
            } 

            return value;
        }

        public override object Serialize(object value)
        {
            if(value is string)
            {
                return ValueConverter.ConvertTo(value.ToString(), typeof(byte[]));
            } 

            return value;
        }
    }
```

And these are the lines i added to the schema:
```
            ValueConverter.Register<ListValue, byte[]>(ParseListValue);
            RegisterValueConverter(new ByteArrayValueAstValueConverter());
```

**Comment by sungam3r** [comment] 2021-02-10 14:37
@eyaldar Unfortunately I was able to get to your problem quite late, although I remembered it all the time in the mail. I think the problem is outside of GraphQL.NET. I've seen similar errors before. Are you using https://github.com/graphql-dotnet/graphql-client? If so then use `List<byte>` instead of `byte[]`. graphql-client treats `byte[]` as special case, not as list type. Also see [readme](https://github.com/graphql-dotnet/graphql-client):
> Be careful when using byte[] in your variables object, as most JSON serializers will treat that as binary data! If you really need to send a list of bytes with a byte[] as a source, then convert it to a List<byte> first, which will tell the serializer to output a list of numbers instead of a base64-encoded string.


I added test in #2273 and it just works 😄 .

**Comment by Shane32** [comment] 2021-02-10 14:42
Extremely likely that the bug was fixed with the variable parsing rework.  Previously all variables were parsed, converted to an ast tree, and then parsed again.  So for example, as an ast tree the variables may not have had the correct types set on them (since the variable does not define the type), so then coercion from a "literal" to a variable failed.  The new variable parsing code walks the variables directly, using the types defined in the schema without any double-conversion.

**Comment by Shane32** [comment] 2021-02-10 14:59
> Extremely likely that the bug was fixed with the variable parsing rework. Previously all variables were parsed, converted to an ast tree, and then parsed again. So for example, as an ast tree the variables may not have had the correct types set on them (since the variable json object does not define the type), so then coercion from a "literal" to a variable failed due to type mismatch. The new variable parsing code walks the variables directly, using the types defined in the schema without any double-conversion.

That's not it.  The test works on the master branch also.

**Comment by eyaldar** [comment] 2021-02-10 15:26
> @eyaldar Unfortunately I was able to get to your problem quite late, although I remembered it all the time in the mail. I think the problem is outside of GraphQL.NET. I've seen similar errors before. Are you using https://github.com/graphql-dotnet/graphql-client? If so then use `List<byte>` instead of `byte[]`. graphql-client treats `byte[]` as special case, not as list type. Also see [readme](https://github.com/graphql-dotnet/graphql-client):
> 
> > Be careful when using byte[] in your variables object, as most JSON serializers will treat that as binary data! If you really need to send a list of bytes with a byte[] as a source, then convert it to a List first, which will tell the serializer to output a list of numbers instead of a base64-encoded string.
> 
> I added test in #2273 and it just works 😄 .

Hey, thanks for getting back to me :).

The issue here is that I had the restriction I would like to treat byte array as a base64 string when the request is sent from client to server and not as a simple byte array (Json .NET does this automatically). but upon reaching the server it failed deserializing as it would be treated as an array instead of a base64 string (exactly as mentioned here in the attached note).

like I wrote in the original post, this is due to the parser treating this case as a byte-by-byte parsing case (i.e delving into a byte type instead of trying to parse List<byte> type) instead of byte array parsing case.

**Comment by sungam3r** [comment] 2021-02-10 15:41
Well, so your description
> Upon receiving the request, the server fails to parse the request (it gets to this line:

does not match the situation. The above example works both on `develop` and `master`.  You can open another issue where you will describe the problem more precisely.

**Comment by sungam3r** [comment] 2021-02-10 15:43
Or even better - you can do a PR with a test that will show the error. You can take #2273 as a basis.

Closing this issue.

**Closed by sungam3r** 2021-02-10 15:43 UTC
Labels: needs confirmation, question

**Comment by Shane32** [comment] 2021-02-10 16:35
I think I understand now -- you want to configure the schema to automatically interpret base64 strings as byte arrays.

The thing is that GraphQL.Net is typically going to enforce that the input data will match the schema.  Scalar types are not designed to represent lists of values.  Even if you manage to get it working, it may not work with literals, and it may break with later version releases, such as version 4.

I think what you really want is a union input type, so you can pass either a `[Byte!]!` or a `String!` type as an argument to a field.  This is not yet supported by the GraphQL spec.

See: https://github.com/graphql/graphql-spec/blob/main/rfcs/InputUnion.md

In the meantime, (if you want to have a spec-compliant schema), you can probably create a scalar type that always converts byte arrays to/from base64 strings.

**Comment by eyaldar** [comment] 2021-02-10 17:01
@Shane32 thing is - GraphQL .NET already has a workaround for such cases - this line of code was extracted from GraphQL .NET's [source code](https://github.com/graphql-dotnet/graphql-dotnet/blob/dff36f52e81c3da1297373e5d65c224783ad0990/src/GraphQL/Conversion/ValueConverter.cs#L54): 
`Register<string, byte[]>(value => Convert.FromBase64String(value)); // such a built-in conversion for string->byte[] seems useful`

but by debugging the code I've noticed that in my specific case (using byte[] instead of List<Byte>) the parser opts for using the ByteType parser instead of using the ListGraphType<Byte> parser. 
unfortunately it's been almost half a year since i've debugged this scenario so i don't remember the entire path the parser goes through when trying to parse base64 string when the object type is byte array. 
I'll try to find time to write a test case to emphasize what i'm talking about.

**Comment by Shane32** [comment] 2021-02-10 17:27
That's because the code is going to walk the schema's type definitions and only call `ParseValue` once it gets to the scalar that needs to be parsed.  The schema defines a list of bytes, and when it encounters a string, it appears to be a list of `char`s.  It is unlikely that the line of code you referenced ever worked in practice; it should likely be removed.

@sungam3r Do we want to add code to especially detect string --> byte[] conversions when parsing variables?  I don't think so.  It still would not work for literals because the validation code would detect that the types do not match.  (Unless we added specific code in there also.)

**Comment by Shane32** [comment] 2021-02-10 17:46
@eyaldar So if you only supported base64 strings, then it's easy -- see #2274 . However, the `GraphTypeTypeRegistry` will not match on an array type, so you would need to specify the type manually wherever the field is defined.

**Comment by eyaldar** [comment] 2021-02-10 21:15
@Shane32 this is pretty much what I ended up doing (plus-minus supporting different variations on byte array).

tbh, this is really an edge case I'd advise most people to avoid when creating new graphql APIs.  in my case I had some strict limitations on my ability to change some legacy DTO class definitions so I needed the ability to pass byte arrays and to do it using base64 strings 🤷‍♂️.

**Comment by sungam3r** [comment] 2021-02-10 21:16
>  It is unlikely that the line of code you referenced ever worked in practice; it should likely be removed.

Why so? In case of custom scalar types this scalar type can call `ValueConverter.ConvertTo` like many existing scalar types do. Or just call `GetArgument<byte[]>` to convert from base64 to array. See `public class Bug956 : QueryTestBase<Bug956Schema>` and #956. We even _can_ add `Base64GraphType : ScalarGraphType` right now.

**Comment by Shane32** [comment] 2021-02-10 21:54
I meant that it would be useless without a custom scalar.  And if you have a custom scalar, you don't need the conversion class because you're writing the scalar yourself and would know what type of value needs conversion.  (See #2274).  And if you did write a custom scalar, and wanted to use the conversion class, you can register the conversion that you need at the same time.

I personally think that all of the scalar types should not use conversion class at all, and it should only be used within GetArgument to transform one type to another type when a cast fails.  (e.g. transforming a string within an IdGraphType to an int)  It would save a dictionary lookup for every scalar value within the variable/literal.  Better to provide a way to override a scalar's functionality if you need to support special input/output formatting.  Something to think about for v5.

**Comment by Shane32** [comment] 2021-02-10 21:55
> We even _can_ add `Base64GraphType : ScalarGraphType` right now.

If we did, that would be one thing.  But we don't.

**Comment by sungam3r** [comment] 2021-02-10 21:57
OK. Forget about scalars. `GetArgument<T>` calls `ValueConverter`, that's all.

**Comment by Shane32** [comment] 2021-02-10 22:02
> tbh, this is really an edge case I'd advise most people to avoid when creating new graphql APIs. in my case I had some strict limitations on my ability to change some legacy DTO class definitions so I needed the ability to pass byte arrays and to do it using base64 strings 🤷‍♂️.

Base64 strings should be the smallest and fastest way to pass large binary objects across graphql, in my opinion.  A byte array would make the resulting json 4x larger, and consume much more processing time within GraphQL.Net.

**Comment by sungam3r** [comment] 2021-02-10 22:05
Also remember about `ValueExecutionNode` on each array element.

**Comment by Shane32** [comment] 2021-02-10 22:11
Maybe we could ensure that some type of AddType call could override a scalar like this:

```cs
//similar to DI registration, point stringgraphtype to a particular derived type
AddType<StringGraphType, MyUppercaseStringGraphType>();

class MyUppercaseStringGraphType : StringGraphType
{
    //override parsevalue/parseliteral/serialize as required to make all strings uppercase
}
```

Then changes to scalar types could be done at schema-build-time rather than via dictionary lookups during execution.

**Comment by eyaldar** [comment] 2021-02-10 23:58
It's all a question of common use case, in my specific use case it made sense to me that strings that needs to be translated to byte array would assume that the string is a base64 string, but I also wanted both byte array and base64 variations in input variables, get argument and output. (byte array mostly for playground use cases). 

Tbh I'm having hard time figuring out why would you want to infer a string to byte array in any other way other than base64 and this is why I opened this issue in the first place (also the valueconverter option made me think that my way of thinking is supported by the library). 

@Shane32 i agree that base64 is better than plain byte array but my point was to avoid byte arrays in graphql api altogether if you can.
