### ISSUE TITLE
Error in handling Integer/Long casting

### ISSUE THREAD

**Issue by isaachaw** [graphql-dotnet/graphql-dotnet#103] opened 2016-06-12 11:35 UTC
Client's query
`query AnotherQuery($someId: Int!) { GetUser(userid: $someId) { id, created_dt, username } }`

Backend
`long userId = context.Argument<long>("userid");`

Argument parsing for long type throws exception when the given parameter can be fit with integer type eg. 10001.
The parsing is ok when $someId is passed with 1000000000000000001

**Comment by joemcbride** [comment] 2016-06-12 21:17
I'm not able to duplicate this issue, though I am able to duplicate the opposite - attempting to get an `int`.  How are you passing the variables to the `DocumentExecutor`?  Are you using `ToInputs`?  This tracks back to `AstFromValue` in the `DocumentExecutor`.  Whatever value type is passed in as `Inputs` creates either a `IntValue` or a `LongValue`.  `ToInputs` uses Newtonsoft.Deserialize to convert to a Dictionary, which defaults numbers to longs.

**Comment by joemcbride** [comment] 2016-06-12 22:54
It looks like this is also probably related to boxing, discussion on stackoverflow here: http://stackoverflow.com/questions/3541680/strange-casting-behaviour-cannot-cast-object-int-to-long

I think I found a fix for this and will push it up soon.

**Comment by isaachaw** [comment] 2016-06-13 00:17
I passed in the value as the `inputs` parameter to the `DocumentExecuter.ExecuteAsync` directly without the `ToInputs` helper function. I think that might caused the problem.

I found another issue when the value is passed in to the query without the parameter.
E.g.
`query AnotherQuery { GetUser(userid: 10001) { id, created_dt, username } }`
`context.Arguments["userid"]` returns 10001 which is correct.
However, when long value is passed in,
`query AnotherQuery { GetUser(userid: 1000000000000001) { id, created_dt, username } }`
`context.Arguments["userid"]` returns 0.

**Comment by joemcbride** [comment] 2016-06-13 03:32
That would fit then.  Right now, the [`Argument<T>` code](https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/ResolveFieldContext.cs#L55) just returns `default(TType)` if an argument key doesn't exist, so that is expected behavior.  I could see how throwing an exception there would make more sense though.

**Comment by isaachaw** [comment] 2016-06-13 05:42
Hi, I think you misunderstood. In my last finding, the argument key `userid` does exist in the arguments list, however if the value given is `long` type eg.1000000000000001 , it is parsed to 0.

**Comment by joemcbride** [comment] 2016-06-13 06:03
Sorry, I did misread.  I'll look at that.

**Comment by joemcbride** [comment] 2016-06-13 06:08
Found and fixed a bug in the parser for that one.

**Comment by joemcbride** [comment] 2016-06-13 15:42
These should be fixed in [0.9.1](https://github.com/graphql-dotnet/graphql-dotnet/releases/tag/v0.9.1), let me know if you find any other issues.

**Comment by isaachaw** [comment] 2016-06-14 02:31
Thanks for the fast response. I have tested with 0.9.1 and the problems are gone.

**Comment by joemcbride** [comment] 2016-06-14 03:19
👍  Please open new issues if you find them!

**Closed by joemcbride** 2016-06-14 03:19 UTC
Labels: bug
