### ISSUE TITLE
GraphQl Migration V0.17.3 to V2.4 "

### ISSUE THREAD

**Issue by TheRealGI** [graphql-dotnet/graphql-dotnet#1109] opened 2019-04-11 14:55 UTC
## Problem
After the migration of the GraphQl NuGet package to the latest stable version, I get a 
`Syntax Error GraphQL (1:1) Unexpected Name "null"`. The schema (docs) is blank with a loading spinner. However, the queries works just fine. 

## Migration
I followed this docs [here](https://graphql-dotnet.github.io/docs/guides/migration).

I updated the **Schema**:

**V0.17.3**
``` 
public class MySchema: Schema
    {
        public MySchema(Func<Type, GraphType> resolveType) : base(resolveType)
        {
            Query = (ObjectGraphType)resolveType(typeof(MyQuery));
        }
    }
} 
```
to **V2.4**
```
public class MySchema: Schema
    {
        public MySchema(IDependencyResolver resolverType) : base(resolveType)
        {
            Query = resolverType.Resolve<MyQuery>();
        }
    }
} 
```
and the **DependencyInjection**:

from
```
container.RegisterInstance<Func<Type, GraphType>>(type =>(GraphType)container.Resolve(type));
```
to
```
container.RegisterInstance<IDependencyResolver>(new FuncDependencyResolver(type => (GraphType)container.Resolve(type)));
```
## Versions
GraphQl 2.4
GraphQl-Parser 3.0
Unity 5.10.3
Unity.Container 5.10.3

Best Regards
Dominic

**Comment by joemcbride** [comment] 2019-04-12 16:25
Did you also update the version of GraphiQL you are using?  Older versions of GraphiQL use an older version of the graphql-js project, which conforms an older version of the GraphQL specification, which does not support the `null` keyword.

This sounds like a mis-match between GraphQL specification versions on the server vs. client.

**Comment by TheRealGI** [comment] 2019-04-17 08:48
Thanks for your suggestion@joemcbride.

Sadly, we can't use the package. The problem is, that we are using the .Net Framework 4.7.2, not .Net  Standard . Furthermore, when we used the older version of the GraphQL (without GraphiQL), there was no issues with the schema.

Are there other reasons or solution for this?
Is .Net Framework 4.7.2 still supported?
Thank you!

**Comment by joemcbride** [comment] 2019-04-17 12:12
Yes, it is supported.  See here for how .NET Standard works: https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by sungam3r** [comment] 2019-09-03 22:16
@TheRealGI Is this issus still actual?

**Comment by TheRealGI** [comment] 2019-09-04 16:09
@sungam3r Yeah, I couldn‘t fixed the problem but I also froze the migration for other projects.

**Comment by sungam3r** [comment] 2019-09-04 17:05
As @joemcbride said you can try to update GraphiQL or Playground to the latest version.

> The problem is, that we are using the .Net Framework 4.7.2, not .Net Standard.

.Net Standard is a API set (contract) which is supported by different implementations. Net Framework is one of them. https://docs.microsoft.com/en-us/dotnet/standard/net-standard states that .Net Framework 4.6.1 is the minimum version which supports netstandard2.0, so does 4.7.2

**Comment by sungam3r** [comment] 2019-10-13 22:47
@TheRealGI I think we can close this issue since the problem is most likely resolved in the current preview version. Feel free to reopen.

**Closed by sungam3r** 2019-10-13 22:47 UTC
Labels: question
