### ISSUE TITLE
Parameter Mismatch 

### ISSUE THREAD

**Issue by aaronjedwards** [graphql-dotnet/graphql-dotnet#1722] opened 2020-07-09 22:26 UTC
## Description

When I include variables in my queries/mutations I see the following error:
```csharp
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at GraphQL.ObjectExtensions.<>c__DisplayClass8_0.<AsDictionary>b__1(PropertyInfo propInfo) in C:\projects\graphql-dotnet\src\GraphQL\ObjectExtensions.cs:line 337
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at GraphQL.ObjectExtensions.AsDictionary(Object source, BindingFlags flags) in C:\projects\graphql-dotnet\src\GraphQL\ObjectExtensions.cs:line 331
   at API.GraphQL.GraphQLExtensions.ToInputs(Object obj)
```
This happens when calling `request.Variables.ToInputs()` within my controller. I am unsure exactly why this is happening. Any help is much appreciated.

### Environment
Version: 3.0.0-preview-1648
OS: macOS

**Comment by sungam3r** [comment] 2020-07-09 22:36
What is your `source` object? Does it have an indexer?

**Comment by aaronjedwards** [comment] 2020-07-09 23:19
@sungam3r I am migrating from v2 and dotnet core 2.2 (now using v3 and dotnet core 3.1).
The following is what I have now for my "Request" class:
```csharp
    public class GraphQLRequest
    {
        public string OperationName { get; set; }
        public string Query { get; set; }
        public object Variables { get; set; }
    }
```
whereas in v2 I used `public JObject Variables { get; set; }`. However I am using `System.Text.Json` instead on `Newtonsoft.Json` so that is unavailable. Not sure if that directly answered your question.

**Comment by sungam3r** [comment] 2020-07-11 12:25
Anyway I should filter indexers, thanks.

**Comment by aaronjedwards** [comment] 2020-07-13 16:54
@sungam3r I think this is still a bug but was able to workaround my issue by using the deserialize helpers from the server project instead.

**Comment by sungam3r** [comment] 2020-07-19 13:07
@aaronjedwards I just checked and saw that the `AsDictionary` method is not being used so I deleted it in #1729. Server project doesn't use it either. As you can imagine, I was unable to reproduce this bug, so I close this issue. Try to upgrade to the latest server/graphql packages and feel free to reopen if any problems remain.

**Closed by sungam3r** 2020-07-19 13:07 UTC
Labels: bug, can't reproduce
