### ISSUE TITLE
Auto generating GraphQL type classes

### ISSUE THREAD

**Issue by ravgupms** [graphql-dotnet/graphql-dotnet#576] opened 2018-02-22 22:02 UTC
I was looking at the Graph QL sample given in the readme and I was wondering is there a way to auto generate .NET classes i.e. Droid and Query in this case from GraphQL schema?  Once auto generated, I can update them and add my service specific resolving logic.

```
public class Droid
{
  public string Id { get; set; }
  public string Name { get; set; }
}

public class Query
{
  // context is optional
  public Droid Hero(ResolveFieldContext context)
  {
    return new Droid { Id = "123", Name = "R2-D2" };
  }
}

var schema = Schema.For(@"
  type Droid {
    id: String
    name: String
  }

  type Query {
    hero: Droid
  }
", _ => {
    _.Types.Include<Query>();
});

var result = schema.Execute(_ =>
{
  _.Query = "{ hero { id name } }";
});
```

**Comment by jquense** [comment] 2018-02-22 22:24
try: https://github.com/graphql-dotnet/conventions

**Comment by ravgupms** [comment] 2018-02-22 22:33
Look like it generate grpah ql schema from .NET classes but I'm look for reverse of it.

**Comment by jquense** [comment] 2018-02-22 22:38
ah ok, yeah nothing that I know of for doing that, sorry!

**Comment by KreativJos** [comment] 2018-03-15 11:09
That doesn't seem possible in the current framework, because of the resolver functions.
POCO-classes should be doable of course, like Droid, EpisodeEnum, Human etc. Maybe someone would like to build a project for that kind of purpose?

**Comment by pekkah** [comment] 2018-03-15 11:14
Could you get the schema out from the introspection endpoint?

**Comment by Sam7** [comment] 2019-11-15 00:43
I'm keen to do this as well.
Any progress on this?

**Comment by sungam3r** [comment] 2019-11-15 05:28
PRs are welcome.

**Comment by MaximS** [comment] 2019-11-15 18:34
Maybe a plugin to a [GraphQL Code Generator](https://github.com/dotansimha/graphql-code-generator)?
Like https://github.com/netspective/graphql-codegen-csharp for example? It's denoted as "experimental" though.

**Comment by sungam3r** [comment] 2019-11-15 21:27
I saw several generators when I studied this question. As a result, I wrote my own and have been using it for a long time. @ravgupms You can choose any, the main thing is that it matches your goals.

Honestly, I think it’s worth closing this issue, since this project is not intended to deal with code generation. GraphQL-dotnet implements mechanisms for the schema declaration and configuration, query validation and execution, etc. I added a note about this issue in #1326 .

**Comment by Sam7** [comment] 2019-11-17 22:43
I tried https://github.com/netspective/graphql-codegen-csharp already but couldn't get it to work. Repo looks pretty abandoned.

@sungam3r any chance I can get a copy of the one you wrote?

**Comment by sungam3r** [comment] 2019-11-18 11:29
@Sam7 There are chances.

**Comment by fenomeno83** [comment] 2020-05-11 12:07
see here!!! (2 parts)

https://stackoverflow.com/a/61726091/7520873

https://stackoverflow.com/a/61726161/7520873

**Comment by sungam3r** [comment] 2020-05-12 12:59
It looks like you (in some sort) reinvented `AutoRegisteringGraphType` class, `AddGraphTypes` extension method from server project and some DI classes from https://github.com/sungam3r/SteroidsDI

**Comment by fenomeno83** [comment] 2020-07-31 09:30
I've created a nuget packages
https://www.nuget.org/packages/GraphQlAutoTypes/

Here github project
https://github.com/fenomeno83/graphql-dotnet-auto-type

**Comment by fenomeno83** [comment] 2020-08-10 09:58
In previous post I have updated references

**Comment by PouryaMontakhab** [comment] 2021-09-29 11:17
@fenomeno83 
thank you for this useful package. I have an asp.net core 5 project that I've used graphql code-first approach. I have got some problems. I have got a class which it's name is CourseGroupMutation.cs like bellow:
`public class CourseGroupMutation : ObjectGraphType
    {
        private readonly ICourseGroupService _courseGroupService;
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public CourseGroupMutation(ICourseGroupService courseGroupService,IUnitOfWork uow,IMapper mapper)
        {
            _courseGroupService = courseGroupService;
            _uow = uow;
            _mapper = mapper;

            Name = "CourseGroupMutation";


            FieldAsync<AddCourseGroupType>(
                name: "createCourseGroup",
                arguments: new QueryArguments(new QueryArgument<NonNullGraphType<AddCourseGroupInputType>> { Name = "input" }),
                resolve: async context =>
                {
                    var courseGroup = context.GetArgument<AddCourseGroupVm>("courseGroup");
                    var result =  await _courseGroupService.AddAsync(courseGroup);
                    _uow.SaveChanges();
                    return _mapper.Map<CourseGroupListVm>(result.RelatedModel);
                });

        }
    }`
I have created a RootMutation Class like bellow : 
` public class RootMutation : ObjectGraphType
    {
        public RootMutation()
        {
            #region Training
            FieldAsync<CourseGroupMutation>("CourseGroupMutation", resolve: async context => await Task.FromResult(new { }));
            #endregion
        }
    }`
According to you, I have created two types , one of it is used for response and the other one is used for request (input and output):
`public class AddCourseGroupInputType : GraphQLInputGenericType<AddCourseGroupVm>{}
public class AddCourseGroupType : GraphQLGenericType<CourseGroupListVm>{}`

AddCourseGroupVm and CourseGroupListVm are my poco classes.

finally I have created a GraphQLMainSchema class like bellow : 
` public class GraphQLMainSchema : Schema
    {
        public GraphQLMainSchema(IServiceProvider service) : base(service)
        {
            Query = service.GetRequiredService<RootQuery>();
            Mutation = service.GetRequiredService<RootMutation>();
        }
    }`

my startup class is as follow : 
`//GraphQL Types 
            //Scan the assembly where the GraphQL schema is defined for types,
            //foreach type register a singleton in IoC container
            (from t in Assembly.GetAssembly(typeof(GraphQLMainSchema)).GetTypes()
             where t.BaseType.IsGenericType &&
             (t.BaseType.GetGenericTypeDefinition() == typeof(GraphQLGenericType<>) ||
             t.BaseType.GetGenericTypeDefinition() == typeof(GraphQLInputGenericType<>))
             select t)
            .ToList()
            .ForEach(t => services.AddScoped(t));


            //GraphQL Queries and Mutations
            //Scan the assembly where the GraphQL schema is defined for queries and mutations,
            //foreach type register a singleton in IoC container
            (from t in Assembly.GetAssembly(typeof(GraphQLMainSchema)).GetTypes()
             where !t.IsAbstract && !t.IsInterface &&
             (t.IsSubclassOf(typeof(ObjectGraphType)) ||
              t.IsSubclassOf(typeof(ObjectGraphType<>)))
             select t)
           .ToList()
           .ForEach(t => services.AddScoped(t));


            services.AddSingleton<IDocumentWriter, DocumentWriter>();
            services.AddSingleton<IDocumentExecuter, DocumentExecuter>();
            services.AddSingleton<IDataLoaderContextAccessor, DataLoaderContextAccessor>();
            services.AddSingleton<DataLoaderDocumentListener>();
            services.AddScoped<ISchema, GraphQLMainSchema>();
            //services.AddScoped<CourseGroupMutation>();
            services.AddGraphQL()
                    .AddSystemTextJson()
                    .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true);`


and I have created a middleware class like bellow;
`public class GraphQLMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly IDocumentWriter _writer;
        private readonly IDocumentExecuter _executor;
        private readonly GraphQLOptions _options;

        public GraphQLMiddleware(RequestDelegate next, IDocumentWriter writer, IDocumentExecuter executor, IOptions<GraphQLOptions> options)
        {
            _next = next;
            _writer = writer;
            _executor = executor;
            _options = options.Value;
        }

        public async Task InvokeAsync(HttpContext httpContext, ISchema schema, IServiceProvider serviceProvider)
        {
            if (httpContext.Request.Path.StartsWithSegments(_options.EndPoint) && string.Equals(httpContext.Request.Method, "POST", StringComparison.OrdinalIgnoreCase))
            {
                var request = await JsonSerializer
                                        .DeserializeAsync<GraphQLRequest>(
                                            httpContext.Request.Body,
                                            new JsonSerializerOptions
                                            {
                                                PropertyNameCaseInsensitive = true
                                            });

                var result = await _executor
                                .ExecuteAsync(doc =>
                                {
                                    doc.Schema = schema;
                                    doc.Query = request.Query;
                                    doc.Inputs = request.Variables.ToInputs();
                                    doc.Listeners.Add(serviceProvider.GetRequiredService<DataLoaderDocumentListener>());
                                }).ConfigureAwait(false);

                httpContext.Response.ContentType = "application/json";
                httpContext.Response.StatusCode = 200;

                await _writer.WriteAsync(httpContext.Response.Body, result);
            }
            else
            {
                await _next(httpContext);
            }
        }
    }

    public static class GraphQLMiddlewareExtensions
    {
        public static IApplicationBuilder UseGraphQL(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<GraphQLMiddleware>();
        }

        public static IServiceCollection AddGraphQL(this IServiceCollection services, Action<GraphQLOptions> action)
        {
            return services.Configure(action);
        }
    }`

when I run playground, I have got these errors in playground ui:
`{
  "errors": [
    {
      "message": "GraphQL.Execution.UnhandledError: Error executing document.\r\n ---> System.ArgumentNullException: Value cannot be null.\r\n   at System.RuntimeType.MakeGenericType(Type[] instantiation)\r\n   at GraphQL.AutoTypes.GraphQLGenericType`1.EmitField(PropertyInfo propertyInfo)\r\n   at GraphQL.AutoTypes.GraphQLGenericType`1.<.ctor>b__1_0(PropertyInfo pi)\r\n   at System.Collections.Generic.List`1.ForEach(Action`1 action)\r\n   at GraphQL.AutoTypes.GraphQLGenericType`1..ctor()\r\n   at HivadSystem.Api.Panel.GraphQL.Types.Training.CourseTypes.CourseType..ctor()\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)\r\n   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 29\r\n   at GraphQL.Types.SchemaTypes.<>c__DisplayClass7_0.<.ctor>b__2(Type t) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 143\r\n   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 541\r\n   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 431\r\n   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 335\r\n   at GraphQL.Types.SchemaTypes.AddTypeWithLoopCheck(IGraphType resolvedType, TypeCollectionContext context, Type namedType) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 513\r\n   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 541\r\n   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 431\r\n   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 335\r\n   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 156\r\n   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 403\r\n   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 374\r\n   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 148\r\n   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 97\r\n   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "ARGUMENT_NULL",
        "codes": [
          "ARGUMENT_NULL"
        ]
      }
    }
  ]
}`

so what is the problem ?

**Comment by fenomeno83** [comment] 2021-09-29 11:33
Hi @PouryaMontakhab , you should put a breakpoint on GraphQLGenericType.cs to understand problem .  
But I suggest you to start from this demo project (it is a configured base template for graphql with included autotypes)
https://github.com/fenomeno83/graphql-dotnet-globalization-demo

On this project, graphql-autotypes is already referenced as nuget library.
But if you want debug autotypes code, you can remove graphql-autotypes nuget and add manually GraphQLGenericType.cs and GraphQLSchemaException.cs classes in your base solution (here files: https://github.com/fenomeno83/graphql-dotnet-auto-types/tree/master/GraphQL.AutoTypes )

**Comment by Shane32** [comment] 2021-09-29 14:17
For legibility, below is a formatted copy of the stack trace.  Notice that the problem appears during initialization of the schema, while `HivadSystem.Api.Panel.GraphQL.Types.Training.CourseTypes.CourseType` is being initialized.
```
GraphQL.Execution.UnhandledError: Error executing document.
 ---> System.ArgumentNullException: Value cannot be null.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at GraphQL.AutoTypes.GraphQLGenericType`1.EmitField(PropertyInfo propertyInfo)
   at GraphQL.AutoTypes.GraphQLGenericType`1.<.ctor>b__1_0(PropertyInfo pi)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at GraphQL.AutoTypes.GraphQLGenericType`1..ctor()
   at HivadSystem.Api.Panel.GraphQL.Types.Training.CourseTypes.CourseType..ctor()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 29
   at GraphQL.Types.SchemaTypes.<>c__DisplayClass7_0.<.ctor>b__2(Type t) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 143
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 541
   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 431
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 335
   at GraphQL.Types.SchemaTypes.AddTypeWithLoopCheck(IGraphType resolvedType, TypeCollectionContext context, Type namedType) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 513
   at GraphQL.Types.SchemaTypes.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 541
   at GraphQL.Types.SchemaTypes.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 431
   at GraphQL.Types.SchemaTypes.AddType(IGraphType type, TypeCollectionContext context) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 335
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 156
   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 403
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 374
   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 148
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 97
   --- End of inner exception stack trace ---
```

**Comment by Shane32** [comment] 2021-09-29 14:42
The error can only possibly occur here, where the automapper finds a type name of `List<>`:

https://github.com/fenomeno83/graphql-dotnet-auto-types/blob/ecdf3aceb1d96950984ba504d84a41a4f82dcc68/GraphQL.AutoTypes/GraphQLGenericType.cs#L80

```cs
var listType = typeof(ListGraphType<>).MakeGenericType(gqlListType);
```

And can only be caused by a `null` being returned on the previous line from `ResolveGraphType`, and that method can only possibly return `null` due to this line:

https://github.com/fenomeno83/graphql-dotnet-auto-types/blob/ecdf3aceb1d96950984ba504d84a41a4f82dcc68/GraphQL.AutoTypes/GraphQLGenericType.cs#L17

```cs
return Assembly.GetAssembly(typeof(ISchema)).GetTypes().FirstOrDefault(t => t.Name == $"{type.Name}{(isInput ? "Input" : "")}Type");
```

Perhaps @fenomeno83 can clarify the issue further, but if I was guessing (I have not used the project) it would seem that there is a `List<T>` property being mapped, where `T` is a custom type.  The automapper is probably looking for a predefined graphql type in the assembly with a name of `TType` (e.g. for `MyObj`, it would be `MyObjType`).  Note that the code searches the GraphQL assembly, not the user's code assembly, due to the `typeof(ISchema).Assembly` reference.

Perhaps that last line of code listed above should read something like this instead:
```cs
//get all loaded assemblies
var assemblies = AppDomain.CurrentDomain.GetAssemblies();
//return first match, or throw exception if none can be found
return assemblies.SelectMany(x => x.GetTypes()).First(t => t.Name == $"{type.Name}{(isInput ? "Input" : "")}Type");
```

However, this is going to search ALL assemblies, which is probably undesired and quite slow, even if it does work.  Note that `Assembly.GetCallingAssembly()` cannot be used since the Microsoft DI framework is going to be the caller to the constructor.  And `Assembly.GetEntryAssembly()` would break tests, and in any case is a poor choice as many people have their graphs in a separate assembly than the MVC code.

Again, I've not used any of this code, and perhaps @fenomeno83 has a better understanding of how this code was intended to function.

**Comment by fenomeno83** [comment] 2021-09-29 16:44
Hi.
Automapper need that you manually register (as input or output graphtype, or both) all custom types and possibile nested types types.

For example, if you if you have classes:

        public class Class1
        {  
        
            public string Prop1 {get;set;}
            public string Prop2 {get;set;}
            public Class2 Class2 {get;set;}
        }
        
        public class Class2
        {  
        
            public string Prop1 {get;set;}
            public string Prop2 {get;set;}
        
        }


and you need to have as Input and/or output List<Class1>
you need to register:
   
    //configure class1 and class2 custom type for input
    public class Class1InputType : GraphQLInputGenericType<Class1> { }
    public class Class2InputType : GraphQLInputGenericType<Class2> { }

   //configure class1 and class2 custom type for output
    public class Class1Type : GraphQLGenericType<Class1> { }
    public class Class2Type : GraphQLGenericType<Class2> { }

**Comment by Shane32** [comment] 2023-04-23 17:47
@sungam3r Status of this issue?

**Comment by sungam3r** [comment] 2023-04-23 20:25
IMO, several issues are mixed here. I would close.

**Comment by Shane32** [comment] 2023-04-23 21:43
Participants: please open a new issue if desired.

**Closed by Shane32** 2023-04-23 21:43 UTC
Labels: question
